/**
 * Career-employer REALISM overrides — geography-related careers (2026-06-18).
 * Norway-first, real employers for the 61 geography careers added in the
 * geography expansion. Wired into getTopEmployers() in career-employers.ts.
 */
import type { Employer } from "./career-employers";

export const REALISM_EMPLOYERS_GEO: Record<string, Employer[]> = {
  "gis-analyst": [
    { name: "Kartverket", industry: "Mapping and geodata", size: "large" },
    { name: "Norkart", industry: "Geospatial software", size: "medium" },
    { name: "Geodata AS", industry: "GIS solutions", size: "medium" },
    { name: "Asplan Viak", industry: "Engineering consultancy", size: "large" },
    { name: "Statens vegvesen", industry: "Public transport infrastructure", size: "large" },
    { name: "Esri", industry: "GIS software", size: "large" },
  ],
  "gis-developer": [
    { name: "Norkart", industry: "Geospatial software", size: "medium" },
    { name: "Geodata AS", industry: "GIS solutions", size: "medium" },
    { name: "Esri", industry: "GIS software", size: "large" },
    { name: "Hexagon", industry: "Geospatial technology", size: "large" },
    { name: "Kartverket", industry: "Mapping and geodata", size: "large" },
    { name: "Statens vegvesen", industry: "Public transport infrastructure", size: "large" },
  ],
  "geospatial-analyst": [
    { name: "Multiconsult", industry: "Engineering consultancy", size: "large" },
    { name: "Asplan Viak", industry: "Engineering consultancy", size: "large" },
    { name: "Norconsult", industry: "Engineering consultancy", size: "large" },
    { name: "Kartverket", industry: "Mapping and geodata", size: "large" },
    { name: "Norges geologiske undersøkelse", industry: "Geological research", size: "medium" },
    { name: "Geodata AS", industry: "GIS solutions", size: "medium" },
  ],
  "spatial-data-analyst": [
    { name: "Norkart", industry: "Geospatial software", size: "medium" },
    { name: "Geodata AS", industry: "GIS solutions", size: "medium" },
    { name: "Kartverket", industry: "Mapping and geodata", size: "large" },
    { name: "Multiconsult", industry: "Engineering consultancy", size: "large" },
    { name: "Hexagon", industry: "Geospatial technology", size: "large" },
    { name: "Statens vegvesen", industry: "Public transport infrastructure", size: "large" },
  ],
  "cartographer": [
    { name: "Kartverket", industry: "Mapping and geodata", size: "large" },
    { name: "Norkart", industry: "Geospatial software", size: "medium" },
    { name: "Geodata AS", industry: "GIS solutions", size: "medium" },
    { name: "Statens vegvesen", industry: "Public transport infrastructure", size: "large" },
    { name: "Asplan Viak", industry: "Engineering consultancy", size: "large" },
    { name: "Esri", industry: "GIS software", size: "large" },
  ],
  "remote-sensing-specialist": [
    { name: "Kongsberg Satellite Services", industry: "Satellite services", size: "large" },
    { name: "Norges geologiske undersøkelse", industry: "Geological research", size: "medium" },
    { name: "Kartverket", industry: "Mapping and geodata", size: "large" },
    { name: "Multiconsult", industry: "Engineering consultancy", size: "large" },
    { name: "Geodata AS", industry: "GIS solutions", size: "medium" },
    { name: "Hexagon", industry: "Geospatial technology", size: "large" },
  ],
  "geomatics-specialist": [
    { name: "Kartverket", industry: "Mapping and geodata", size: "large" },
    { name: "Norkart", industry: "Geospatial software", size: "medium" },
    { name: "Statens vegvesen", industry: "Public transport infrastructure", size: "large" },
    { name: "Multiconsult", industry: "Engineering consultancy", size: "large" },
    { name: "Norconsult", industry: "Engineering consultancy", size: "large" },
    { name: "Asplan Viak", industry: "Engineering consultancy", size: "large" },
  ],
  "mapping-technician": [
    { name: "Kartverket", industry: "Mapping and geodata", size: "large" },
    { name: "Statens vegvesen", industry: "Public transport infrastructure", size: "large" },
    { name: "Norkart", industry: "Geospatial software", size: "medium" },
    { name: "Asplan Viak", industry: "Engineering consultancy", size: "large" },
    { name: "Multiconsult", industry: "Engineering consultancy", size: "large" },
    { name: "Norconsult", industry: "Engineering consultancy", size: "large" },
  ],
  "hydrographer": [
    { name: "Kartverket Sjødivisjonen", industry: "Hydrographic services", size: "large" },
    { name: "Kongsberg Maritime", industry: "Maritime technology", size: "large" },
    { name: "Multiconsult", industry: "Engineering consultancy", size: "large" },
    { name: "Norconsult", industry: "Engineering consultancy", size: "large" },
    { name: "Geodata AS", industry: "GIS solutions", size: "medium" },
    { name: "Statens vegvesen", industry: "Public transport infrastructure", size: "large" },
  ],
  "geospatial-data-scientist": [
    { name: "Norkart", industry: "Geospatial software", size: "medium" },
    { name: "Geodata AS", industry: "GIS solutions", size: "medium" },
    { name: "Kongsberg Satellite Services", industry: "Satellite services", size: "large" },
    { name: "Multiconsult", industry: "Engineering consultancy", size: "large" },
    { name: "Hexagon", industry: "Geospatial technology", size: "large" },
    { name: "Esri", industry: "GIS software", size: "large" },
  ],
  "location-intelligence-analyst": [
    { name: "Geodata AS", industry: "GIS solutions", size: "medium" },
    { name: "Norkart", industry: "Geospatial software", size: "medium" },
    { name: "Esri", industry: "GIS software", size: "large" },
    { name: "Hexagon", industry: "Geospatial technology", size: "large" },
    { name: "Asplan Viak", industry: "Engineering consultancy", size: "large" },
    { name: "Multiconsult", industry: "Engineering consultancy", size: "large" },
  ],
  "satellite-data-analyst": [
    { name: "Kongsberg Satellite Services", industry: "Satellite services", size: "large" },
    { name: "Kartverket", industry: "Mapping and geodata", size: "large" },
    { name: "Norges geologiske undersøkelse", industry: "Geological research", size: "medium" },
    { name: "Geodata AS", industry: "GIS solutions", size: "medium" },
    { name: "Hexagon", industry: "Geospatial technology", size: "large" },
    { name: "Multiconsult", industry: "Engineering consultancy", size: "large" },
  ],
  "earth-observation-specialist": [
    { name: "Kongsberg Satellite Services", industry: "Satellite services", size: "large" },
    { name: "Norges geologiske undersøkelse", industry: "Geological research", size: "medium" },
    { name: "Kartverket", industry: "Mapping and geodata", size: "large" },
    { name: "Multiconsult", industry: "Engineering consultancy", size: "large" },
    { name: "Geodata AS", industry: "GIS solutions", size: "medium" },
    { name: "Hexagon", industry: "Geospatial technology", size: "large" },
  ],
  "drone-mapping-specialist": [
    { name: "Norkart", industry: "Geospatial software", size: "medium" },
    { name: "Geodata AS", industry: "GIS solutions", size: "medium" },
    { name: "Asplan Viak", industry: "Engineering consultancy", size: "large" },
    { name: "Multiconsult", industry: "Engineering consultancy", size: "large" },
    { name: "Norconsult", industry: "Engineering consultancy", size: "large" },
    { name: "Statens vegvesen", industry: "Public transport infrastructure", size: "large" },
  ],
  "gis-manager": [
    { name: "Kartverket", industry: "Mapping and geodata", size: "large" },
    { name: "Norkart", industry: "Geospatial software", size: "medium" },
    { name: "Geodata AS", industry: "GIS solutions", size: "medium" },
    { name: "Statens vegvesen", industry: "Public transport infrastructure", size: "large" },
    { name: "Multiconsult", industry: "Engineering consultancy", size: "large" },
    { name: "Asplan Viak", industry: "Engineering consultancy", size: "large" },
  ],
  "geospatial-ai-engineer": [
    { name: "Kongsberg Satellite Services (KSAT)", industry: "Satellite services", size: "large" },
    { name: "Cognite", industry: "Industrial software", size: "medium" },
    { name: "Norkart", industry: "Geographic information systems", size: "medium" },
    { name: "Esri", industry: "Geographic information systems", size: "large" },
    { name: "Planet", industry: "Earth imaging", size: "medium" },
    { name: "SINTEF", industry: "Research", size: "large" },
  ],
  "climate-data-scientist": [
    { name: "Meteorologisk institutt", industry: "Meteorology", size: "large" },
    { name: "NORCE", industry: "Research", size: "large" },
    { name: "NVE", industry: "Water and energy", size: "large" },
    { name: "SINTEF", industry: "Research", size: "large" },
    { name: "Equinor", industry: "Energy", size: "large" },
    { name: "Microsoft", industry: "Technology", size: "large" },
  ],
  "satellite-analytics-specialist": [
    { name: "Kongsberg Satellite Services (KSAT)", industry: "Satellite services", size: "large" },
    { name: "Kongsberg Gruppen", industry: "Technology and defence", size: "large" },
    { name: "Planet", industry: "Earth imaging", size: "medium" },
    { name: "NORCE", industry: "Research", size: "large" },
    { name: "Meteorologisk institutt", industry: "Meteorology", size: "large" },
    { name: "Esri", industry: "Geographic information systems", size: "large" },
  ],
  "digital-twin-specialist": [
    { name: "Cognite", industry: "Industrial software", size: "medium" },
    { name: "Kongsberg Gruppen", industry: "Technology and defence", size: "large" },
    { name: "Equinor", industry: "Energy", size: "large" },
    { name: "SINTEF", industry: "Research", size: "large" },
    { name: "Norkart", industry: "Geographic information systems", size: "medium" },
    { name: "Microsoft", industry: "Technology", size: "large" },
  ],
  "smart-city-planner": [
    { name: "Oslo kommune", industry: "Local government", size: "large" },
    { name: "Norkart", industry: "Geographic information systems", size: "medium" },
    { name: "SINTEF", industry: "Research", size: "large" },
    { name: "Telenor", industry: "Telecommunications", size: "large" },
    { name: "NORCE", industry: "Research", size: "large" },
    { name: "Esri", industry: "Geographic information systems", size: "large" },
  ],
  "earth-observation-scientist": [
    { name: "NORCE", industry: "Research", size: "large" },
    { name: "Meteorologisk institutt", industry: "Meteorology", size: "large" },
    { name: "Kongsberg Satellite Services (KSAT)", industry: "Satellite services", size: "large" },
    { name: "NVE", industry: "Water and energy", size: "large" },
    { name: "SINTEF", industry: "Research", size: "large" },
    { name: "Planet", industry: "Earth imaging", size: "medium" },
  ],
  "autonomous-mapping-systems-engineer": [
    { name: "Kongsberg Gruppen", industry: "Technology and defence", size: "large" },
    { name: "Cognite", industry: "Industrial software", size: "medium" },
    { name: "SINTEF", industry: "Research", size: "large" },
    { name: "Equinor", industry: "Energy", size: "large" },
    { name: "Norkart", industry: "Geographic information systems", size: "medium" },
    { name: "Esri", industry: "Geographic information systems", size: "large" },
  ],
  "environmental-intelligence-analyst": [
    { name: "NVE", industry: "Water and energy", size: "large" },
    { name: "NORCE", industry: "Research", size: "large" },
    { name: "Meteorologisk institutt", industry: "Meteorology", size: "large" },
    { name: "SINTEF", industry: "Research", size: "large" },
    { name: "Cognite", industry: "Industrial software", size: "medium" },
    { name: "Esri", industry: "Geographic information systems", size: "large" },
  ],
  "meteorologist": [
    { name: "Meteorologisk institutt", industry: "Meteorology", size: "large" },
    { name: "NVE", industry: "Energy and water resources", size: "large" },
    { name: "Bjerknes Centre for Climate Research", industry: "Climate research", size: "medium" },
    { name: "NORCE", industry: "Research", size: "large" },
    { name: "SINTEF", industry: "Research", size: "large" },
    { name: "ECMWF", industry: "Meteorology", size: "medium" },
  ],
  "climatologist": [
    { name: "Cicero", industry: "Climate research", size: "medium" },
    { name: "Bjerknes Centre for Climate Research", industry: "Climate research", size: "medium" },
    { name: "Meteorologisk institutt", industry: "Meteorology", size: "large" },
    { name: "NORCE", industry: "Research", size: "large" },
    { name: "NINA", industry: "Nature research", size: "large" },
    { name: "Miljødirektoratet", industry: "Environmental governance", size: "large" },
  ],
  "weather-forecaster": [
    { name: "Meteorologisk institutt", industry: "Meteorology", size: "large" },
    { name: "NVE", industry: "Energy and water resources", size: "large" },
    { name: "Avinor", industry: "Aviation", size: "large" },
    { name: "StormGeo", industry: "Weather services", size: "medium" },
    { name: "NRK", industry: "Broadcasting", size: "large" },
    { name: "ECMWF", industry: "Meteorology", size: "medium" },
  ],
  "ecologist": [
    { name: "NINA", industry: "Nature research", size: "large" },
    { name: "Miljødirektoratet", industry: "Environmental governance", size: "large" },
    { name: "NIVA", industry: "Water research", size: "large" },
    { name: "Statsforvalteren", industry: "Public administration", size: "large" },
    { name: "NORCE", industry: "Research", size: "large" },
    { name: "Multiconsult", industry: "Consulting", size: "large" },
  ],
  "climate-change-analyst": [
    { name: "Cicero", industry: "Climate research", size: "medium" },
    { name: "Miljødirektoratet", industry: "Environmental governance", size: "large" },
    { name: "NVE", industry: "Energy and water resources", size: "large" },
    { name: "NORCE", industry: "Research", size: "large" },
    { name: "SINTEF", industry: "Research", size: "large" },
    { name: "Multiconsult", industry: "Consulting", size: "large" },
  ],
  "natural-resource-manager": [
    { name: "Miljødirektoratet", industry: "Environmental governance", size: "large" },
    { name: "NVE", industry: "Energy and water resources", size: "large" },
    { name: "Statsforvalteren", industry: "Public administration", size: "large" },
    { name: "NINA", industry: "Nature research", size: "large" },
    { name: "NIVA", industry: "Water research", size: "large" },
    { name: "Multiconsult", industry: "Consulting", size: "large" },
  ],
  "environmental-consultant": [
    { name: "Multiconsult", industry: "Consulting and engineering", size: "large" },
    { name: "Norconsult", industry: "Consulting and engineering", size: "large" },
    { name: "Asplan Viak", industry: "Consulting and engineering", size: "large" },
    { name: "Rambøll", industry: "Consulting and engineering", size: "large" },
    { name: "Sweco", industry: "Consulting and engineering", size: "large" },
    { name: "DNV", industry: "Assurance and risk management", size: "large" },
  ],
  "sustainability-consultant": [
    { name: "EY", industry: "Professional services", size: "large" },
    { name: "PwC", industry: "Professional services", size: "large" },
    { name: "Deloitte", industry: "Professional services", size: "large" },
    { name: "KPMG", industry: "Professional services", size: "large" },
    { name: "DNV", industry: "Assurance and risk management", size: "large" },
    { name: "Rambøll", industry: "Consulting and engineering", size: "large" },
  ],
  "environmental-planner": [
    { name: "Asplan Viak", industry: "Consulting and engineering", size: "large" },
    { name: "Norconsult", industry: "Consulting and engineering", size: "large" },
    { name: "Multiconsult", industry: "Consulting and engineering", size: "large" },
    { name: "Sweco", industry: "Consulting and engineering", size: "large" },
    { name: "Rambøll", industry: "Consulting and engineering", size: "large" },
    { name: "Statens vegvesen", industry: "Public infrastructure", size: "large" },
  ],
  "climate-risk-analyst": [
    { name: "DNV", industry: "Assurance and risk management", size: "large" },
    { name: "Storebrand", industry: "Finance and insurance", size: "large" },
    { name: "DNB", industry: "Banking and finance", size: "large" },
    { name: "Cicero", industry: "Climate research", size: "medium" },
    { name: "EY", industry: "Professional services", size: "large" },
    { name: "Equinor", industry: "Energy", size: "large" },
  ],
  "environmental-risk-consultant": [
    { name: "DNV", industry: "Assurance and risk management", size: "large" },
    { name: "Multiconsult", industry: "Consulting and engineering", size: "large" },
    { name: "Norconsult", industry: "Consulting and engineering", size: "large" },
    { name: "Rambøll", industry: "Consulting and engineering", size: "large" },
    { name: "Sweco", industry: "Consulting and engineering", size: "large" },
    { name: "Asplan Viak", industry: "Consulting and engineering", size: "large" },
  ],
  "sustainability-manager": [
    { name: "Equinor", industry: "Energy", size: "large" },
    { name: "Storebrand", industry: "Finance and insurance", size: "large" },
    { name: "DNB", industry: "Banking and finance", size: "large" },
    { name: "DNV", industry: "Assurance and risk management", size: "large" },
    { name: "Norsk Hydro", industry: "Materials and manufacturing", size: "large" },
    { name: "Rambøll", industry: "Consulting and engineering", size: "large" },
  ],
  "esg-consultant": [
    { name: "PwC", industry: "Professional services", size: "large" },
    { name: "EY", industry: "Professional services", size: "large" },
    { name: "Deloitte", industry: "Professional services", size: "large" },
    { name: "KPMG", industry: "Professional services", size: "large" },
    { name: "DNV", industry: "Assurance and risk management", size: "large" },
    { name: "Cicero", industry: "Climate research", size: "medium" },
  ],
  "market-location-analyst": [
    { name: "NorgesGruppen", industry: "Retail", size: "large" },
    { name: "REMA 1000", industry: "Retail", size: "large" },
    { name: "Coop Norge", industry: "Retail", size: "large" },
    { name: "Asplan Viak", industry: "Consulting and engineering", size: "large" },
    { name: "Sweco", industry: "Consulting and engineering", size: "large" },
    { name: "SSB", industry: "Public statistics", size: "large" },
  ],
  "business-intelligence-analyst": [
    { name: "DNB", industry: "Banking and finance", size: "large" },
    { name: "Telenor", industry: "Telecommunications", size: "large" },
    { name: "Equinor", industry: "Energy", size: "large" },
    { name: "EY", industry: "Professional services", size: "large" },
    { name: "Deloitte", industry: "Professional services", size: "large" },
    { name: "Storebrand", industry: "Finance and insurance", size: "large" },
  ],
  "population-analyst": [
    { name: "SSB", industry: "Public statistics", size: "large" },
    { name: "Oslo kommune", industry: "Local government", size: "large" },
    { name: "Asplan Viak", industry: "Consulting and engineering", size: "large" },
    { name: "Norconsult", industry: "Consulting and engineering", size: "large" },
    { name: "NIBR", industry: "Research institute", size: "medium" },
    { name: "Rambøll", industry: "Consulting and engineering", size: "large" },
  ],
  "demographer": [
    { name: "SSB", industry: "Public statistics", size: "large" },
    { name: "Universitetet i Oslo", industry: "Higher education", size: "large" },
    { name: "NIBR", industry: "Research institute", size: "medium" },
    { name: "Institutt for samfunnsforskning", industry: "Research institute", size: "medium" },
    { name: "Folkehelseinstituttet", industry: "Public health", size: "large" },
    { name: "NTNU", industry: "Higher education", size: "large" },
  ],
  "social-researcher": [
    { name: "SSB", industry: "Public statistics", size: "large" },
    { name: "Institutt for samfunnsforskning", industry: "Research institute", size: "medium" },
    { name: "NIBR", industry: "Research institute", size: "medium" },
    { name: "Fafo", industry: "Research institute", size: "medium" },
    { name: "Universitetet i Oslo", industry: "Higher education", size: "large" },
    { name: "NTNU", industry: "Higher education", size: "large" },
  ],
  "town-planner": [
    { name: "Oslo kommune", industry: "Local government", size: "large" },
    { name: "Bergen kommune", industry: "Local government", size: "large" },
    { name: "Trondheim kommune", industry: "Local government", size: "large" },
    { name: "Asplan Viak", industry: "Planning consultancy", size: "large" },
    { name: "Multiconsult", industry: "Consultancy and engineering", size: "large" },
    { name: "Rambøll", industry: "Consultancy and engineering", size: "large" },
  ],
  "regional-planner": [
    { name: "Viken fylkeskommune", industry: "County government", size: "large" },
    { name: "Vestland fylkeskommune", industry: "County government", size: "large" },
    { name: "Statsforvalteren", industry: "Regional state administration", size: "large" },
    { name: "Kommunal- og distriktsdepartementet", industry: "Central government", size: "large" },
    { name: "Asplan Viak", industry: "Planning consultancy", size: "large" },
    { name: "Rambøll", industry: "Consultancy and engineering", size: "large" },
  ],
  "transport-planner": [
    { name: "Statens vegvesen", industry: "Roads and transport", size: "large" },
    { name: "Ruter", industry: "Public transport", size: "large" },
    { name: "Oslo kommune", industry: "Local government", size: "large" },
    { name: "Multiconsult", industry: "Consultancy and engineering", size: "large" },
    { name: "Rambøll", industry: "Consultancy and engineering", size: "large" },
    { name: "Asplan Viak", industry: "Planning consultancy", size: "large" },
  ],
  "infrastructure-planner": [
    { name: "Statens vegvesen", industry: "Roads and transport", size: "large" },
    { name: "Bane NOR", industry: "Rail infrastructure", size: "large" },
    { name: "Multiconsult", industry: "Consultancy and engineering", size: "large" },
    { name: "Rambøll", industry: "Consultancy and engineering", size: "large" },
    { name: "Norconsult", industry: "Consultancy and engineering", size: "large" },
    { name: "Oslo kommune", industry: "Local government", size: "large" },
  ],
  "land-use-planner": [
    { name: "Oslo kommune", industry: "Local government", size: "large" },
    { name: "Bergen kommune", industry: "Local government", size: "large" },
    { name: "Statsforvalteren", industry: "Regional state administration", size: "large" },
    { name: "Kommunal- og distriktsdepartementet", industry: "Central government", size: "large" },
    { name: "Asplan Viak", industry: "Planning consultancy", size: "large" },
    { name: "Norconsult", industry: "Consultancy and engineering", size: "large" },
  ],
  "development-planner": [
    { name: "Oslo kommune", industry: "Local government", size: "large" },
    { name: "Trondheim kommune", industry: "Local government", size: "large" },
    { name: "Asplan Viak", industry: "Planning consultancy", size: "large" },
    { name: "Multiconsult", industry: "Consultancy and engineering", size: "large" },
    { name: "Rambøll", industry: "Consultancy and engineering", size: "large" },
    { name: "Norconsult", industry: "Consultancy and engineering", size: "large" },
  ],
  "housing-policy-officer": [
    { name: "Husbanken", industry: "Housing finance and policy", size: "large" },
    { name: "Kommunal- og distriktsdepartementet", industry: "Central government", size: "large" },
    { name: "Oslo kommune", industry: "Local government", size: "large" },
    { name: "Bergen kommune", industry: "Local government", size: "large" },
    { name: "Statsforvalteren", industry: "Regional state administration", size: "large" },
    { name: "Statistisk sentralbyrå", industry: "Statistics and research", size: "large" },
  ],
  "policy-analyst": [
    { name: "Kommunal- og distriktsdepartementet", industry: "Central government", size: "large" },
    { name: "Statistisk sentralbyrå", industry: "Statistics and research", size: "large" },
    { name: "Statsforvalteren", industry: "Regional state administration", size: "large" },
    { name: "Oslo kommune", industry: "Local government", size: "large" },
    { name: "Rambøll", industry: "Consultancy and research", size: "large" },
    { name: "OECD", industry: "International organisation", size: "large" },
  ],
  "emergency-management-officer": [
    { name: "DSB", industry: "Civil protection and emergency", size: "large" },
    { name: "Politiet", industry: "Police and public safety", size: "large" },
    { name: "Oslo kommune", industry: "Local government", size: "large" },
    { name: "Statsforvalteren", industry: "Regional state administration", size: "large" },
    { name: "Helsedirektoratet", industry: "Health administration", size: "large" },
    { name: "Sivilforsvaret", industry: "Civil defence", size: "large" },
  ],
  "civil-service-officer": [
    { name: "Kommunal- og distriktsdepartementet", industry: "Central government", size: "large" },
    { name: "Statsforvalteren", industry: "Regional state administration", size: "large" },
    { name: "Oslo kommune", industry: "Local government", size: "large" },
    { name: "Bergen kommune", industry: "Local government", size: "large" },
    { name: "NAV", industry: "Welfare administration", size: "large" },
    { name: "Skatteetaten", industry: "Tax administration", size: "large" },
  ],
  "border-migration-analyst": [
    { name: "UDI", industry: "Immigration administration", size: "large" },
    { name: "Politiet", industry: "Police and public safety", size: "large" },
    { name: "Kripos", industry: "Police analysis", size: "large" },
    { name: "Statistisk sentralbyrå", industry: "Statistics and research", size: "large" },
    { name: "Justis- og beredskapsdepartementet", industry: "Central government", size: "large" },
    { name: "Frontex", industry: "European border agency", size: "large" },
  ],
  "disaster-risk-specialist": [
    { name: "DSB", industry: "Civil protection and emergency", size: "large" },
    { name: "NVE", industry: "Water and energy directorate", size: "large" },
    { name: "NGI", industry: "Geotechnical research", size: "medium" },
    { name: "Statsforvalteren", industry: "Regional state administration", size: "large" },
    { name: "Multiconsult", industry: "Consultancy and engineering", size: "large" },
    { name: "Norconsult", industry: "Consultancy and engineering", size: "large" },
  ],
  "local-government-officer": [
    { name: "Oslo kommune", industry: "Local government", size: "large" },
    { name: "Bergen kommune", industry: "Local government", size: "large" },
    { name: "Trondheim kommune", industry: "Local government", size: "large" },
    { name: "Stavanger kommune", industry: "Local government", size: "large" },
    { name: "Statsforvalteren", industry: "Regional state administration", size: "large" },
    { name: "KS", industry: "Local government association", size: "large" },
  ],
  "supply-chain-analyst": [
    { name: "Posten Bring", industry: "Postal and logistics", size: "large" },
    { name: "ASKO", industry: "Wholesale and distribution", size: "large" },
    { name: "DSV", industry: "Freight and logistics", size: "large" },
    { name: "Schenker", industry: "Freight and logistics", size: "large" },
    { name: "Elkjøp", industry: "Retail", size: "large" },
    { name: "Equinor", industry: "Energy", size: "large" },
  ],
  "logistics-planner": [
    { name: "Posten Bring", industry: "Postal and logistics", size: "large" },
    { name: "Kuehne+Nagel", industry: "Freight and logistics", size: "large" },
    { name: "DSV", industry: "Freight and logistics", size: "large" },
    { name: "Schenker", industry: "Freight and logistics", size: "large" },
    { name: "ASKO", industry: "Wholesale and distribution", size: "large" },
    { name: "Wilhelmsen", industry: "Maritime services", size: "large" },
  ],
  "international-development-officer": [
    { name: "Norad", industry: "Development cooperation", size: "large" },
    { name: "Flyktninghjelpen", industry: "Humanitarian aid", size: "large" },
    { name: "Kirkens Nødhjelp", industry: "Humanitarian aid", size: "medium" },
    { name: "Redd Barna", industry: "Children's rights", size: "large" },
    { name: "Røde Kors", industry: "Humanitarian aid", size: "large" },
    { name: "UNDP", industry: "International organisation", size: "large" },
  ],
  "humanitarian-aid-worker": [
    { name: "Røde Kors", industry: "Humanitarian aid", size: "large" },
    { name: "Flyktninghjelpen", industry: "Humanitarian aid", size: "large" },
    { name: "Leger Uten Grenser", industry: "Medical humanitarian aid", size: "large" },
    { name: "Kirkens Nødhjelp", industry: "Humanitarian aid", size: "medium" },
    { name: "Redd Barna", industry: "Children's rights", size: "large" },
    { name: "UNDP", industry: "International organisation", size: "large" },
  ],
  "ngo-programme-manager": [
    { name: "Flyktninghjelpen", industry: "Humanitarian aid", size: "large" },
    { name: "Røde Kors", industry: "Humanitarian aid", size: "large" },
    { name: "Redd Barna", industry: "Children's rights", size: "large" },
    { name: "Kirkens Nødhjelp", industry: "Humanitarian aid", size: "medium" },
    { name: "Norad", industry: "Development cooperation", size: "large" },
    { name: "UNDP", industry: "International organisation", size: "large" },
  ],
  "research-scientist": [
    { name: "SINTEF", industry: "Applied research", size: "large" },
    { name: "NORCE", industry: "Applied research", size: "large" },
    { name: "NTNU", industry: "University", size: "large" },
    { name: "University of Oslo", industry: "University", size: "large" },
    { name: "NINA", industry: "Nature research", size: "medium" },
    { name: "Folkehelseinstituttet", industry: "Public health research", size: "large" },
  ],
  "field-researcher": [
    { name: "NINA", industry: "Nature research", size: "medium" },
    { name: "NORCE", industry: "Applied research", size: "large" },
    { name: "SINTEF", industry: "Applied research", size: "large" },
    { name: "NTNU", industry: "University", size: "large" },
    { name: "University of Oslo", industry: "University", size: "large" },
    { name: "Folkehelseinstituttet", industry: "Public health research", size: "large" },
  ],
};
