/**
 * Career-employer REALISM overrides — high-earning additions (2026-06-15).
 * Employer lists for the ~32 senior high-earning careers added alongside the
 * Career Radar "High-Earning Careers" filter rebuild. Norway-first, real.
 */
import type { Employer } from './career-employers';

export const REALISM_EMPLOYERS_HIGHEARN: Record<string, Employer[]> = {
  "ai-infrastructure-architect": [
    { name: "Cognite", industry: "Industrial Software", size: "Large" },
    { name: "nscale", industry: "AI Infrastructure", size: "Medium" },
    { name: "Telenor", industry: "Telecommunications", size: "Large" },
    { name: "Equinor", industry: "Energy", size: "Large" },
    { name: "Schibsted", industry: "Media & Technology", size: "Large" },
    { name: "Visma", industry: "Software", size: "Large" },
  ],
  "asset-manager": [
    { name: "DNB Asset Management", industry: "Asset Management", size: "Large" },
    { name: "Storebrand", industry: "Asset Management", size: "Large" },
    { name: "KLP", industry: "Pension & Insurance", size: "Large" },
    { name: "Norges Bank Investment Management", industry: "Asset Management", size: "Large" },
    { name: "Nordea Asset Management", industry: "Asset Management", size: "Large" },
  ],
  "associate-partner": [
    { name: "McKinsey & Company", industry: "Management Consulting", size: "Large" },
    { name: "Boston Consulting Group", industry: "Management Consulting", size: "Large" },
    { name: "Bain & Company", industry: "Management Consulting", size: "Large" },
    { name: "PwC", industry: "Professional Services", size: "Large" },
    { name: "Accenture", industry: "Technology Consulting", size: "Large" },
  ],
  "aviation-director": [
    { name: "SAS", industry: "Aviation", size: "Large" },
    { name: "Norwegian", industry: "Aviation", size: "Large" },
    { name: "Widerøe", industry: "Aviation", size: "Large" },
    { name: "Avinor", industry: "Airport Operations", size: "Large" },
    { name: "Forsvaret", industry: "Defence", size: "Large" },
  ],
  "chief-commercial-officer": [
    { name: "Telenor", industry: "Telecommunications", size: "Large" },
    { name: "Visma", industry: "Software", size: "Large" },
    { name: "Cognite", industry: "Industrial Software", size: "Large" },
    { name: "Schibsted", industry: "Media & Technology", size: "Large" },
    { name: "Orkla", industry: "Consumer Goods", size: "Large" },
  ],
  "chief-information-security-officer": [
    { name: "DNB", industry: "Banking", size: "Large" },
    { name: "Telenor", industry: "Telecommunications", size: "Large" },
    { name: "Equinor", industry: "Energy", size: "Large" },
    { name: "Schibsted", industry: "Media & Technology", size: "Large" },
    { name: "Visma", industry: "Software", size: "Large" },
    { name: "Kongsberg Gruppen", industry: "Defence & Technology", size: "Large" },
  ],
  "chief-revenue-officer": [
    { name: "Cognite", industry: "Industrial Software", size: "Large" },
    { name: "Visma", industry: "Software", size: "Large" },
    { name: "Telenor", industry: "Telecommunications", size: "Large" },
    { name: "Schibsted", industry: "Media & Technology", size: "Large" },
    { name: "Kahoot!", industry: "EdTech", size: "Large" },
  ],
  "chief-sales-officer": [
    { name: "Telenor", industry: "Telecommunications", size: "Large" },
    { name: "Visma", industry: "Software", size: "Large" },
    { name: "Cognite", industry: "Industrial Software", size: "Large" },
    { name: "Schibsted", industry: "Media & Technology", size: "Large" },
    { name: "Tomra", industry: "Industrial Technology", size: "Large" },
  ],
  "commercial-real-estate-director": [
    { name: "Entra", industry: "Commercial Real Estate", size: "Large" },
    { name: "Aspelin Ramm", industry: "Real Estate", size: "Large" },
    { name: "DNB Næringseiendom", industry: "Real Estate", size: "Large" },
    { name: "Storebrand Eiendom", industry: "Real Estate", size: "Large" },
    { name: "OBOS", industry: "Real Estate", size: "Large" },
  ],
  "company-president": [
    { name: "Equinor", industry: "Energy", size: "Large" },
    { name: "Telenor", industry: "Telecommunications", size: "Large" },
    { name: "DNB", industry: "Banking", size: "Large" },
    { name: "Orkla", industry: "Consumer Goods", size: "Large" },
    { name: "Aker ASA", industry: "Industrial Holding", size: "Large" },
  ],
  "consulting-firm-partner": [
    { name: "McKinsey & Company", industry: "Management Consulting", size: "Large" },
    { name: "Boston Consulting Group", industry: "Management Consulting", size: "Large" },
    { name: "Bain & Company", industry: "Management Consulting", size: "Large" },
    { name: "Deloitte", industry: "Professional Services", size: "Large" },
    { name: "EY", industry: "Professional Services", size: "Large" },
    { name: "KPMG", industry: "Professional Services", size: "Large" },
  ],
  "corporate-finance-director": [
    { name: "DNB", industry: "Banking", size: "Large" },
    { name: "Equinor", industry: "Energy", size: "Large" },
    { name: "Telenor", industry: "Telecommunications", size: "Large" },
    { name: "Aker ASA", industry: "Industrial Holding", size: "Large" },
    { name: "Orkla", industry: "Consumer Goods", size: "Large" },
  ],
  "distinguished-engineer": [
    { name: "Cognite", industry: "Industrial Software", size: "Large" },
    { name: "Schibsted", industry: "Media & Technology", size: "Large" },
    { name: "Visma", industry: "Software", size: "Large" },
    { name: "Kongsberg Gruppen", industry: "Defence & Technology", size: "Large" },
    { name: "DNB", industry: "Banking", size: "Large" },
    { name: "Bekk", industry: "Technology Consulting", size: "Medium" },
  ],
  "drilling-manager": [
    { name: "Equinor", industry: "Energy", size: "Large" },
    { name: "Odfjell Drilling", industry: "Drilling", size: "Large" },
    { name: "Aker BP", industry: "Energy", size: "Large" },
    { name: "Vår Energi", industry: "Energy", size: "Large" },
    { name: "Transocean Norway", industry: "Drilling", size: "Large" },
  ],
  "flight-operations-director": [
    { name: "SAS", industry: "Aviation", size: "Large" },
    { name: "Norwegian", industry: "Aviation", size: "Large" },
    { name: "Widerøe", industry: "Aviation", size: "Large" },
    { name: "Avinor", industry: "Airport Operations", size: "Large" },
    { name: "Forsvaret", industry: "Defence", size: "Large" },
  ],
  "hedge-fund-software-engineer": [
    { name: "DNB Markets", industry: "Investment Banking", size: "Large" },
    { name: "Storebrand", industry: "Asset Management", size: "Large" },
    { name: "Sector Asset Management", industry: "Hedge Fund", size: "Medium" },
    { name: "Norges Bank Investment Management", industry: "Asset Management", size: "Large" },
    { name: "Varies / many firms", industry: "Finance", size: "Varies" },
  ],
  "law-firm-partner": [
    { name: "Wikborg Rein", industry: "Law Firm", size: "Large" },
    { name: "BAHR", industry: "Law Firm", size: "Large" },
    { name: "Thommessen", industry: "Law Firm", size: "Large" },
    { name: "Schjødt", industry: "Law Firm", size: "Large" },
    { name: "Wiersholm", industry: "Law Firm", size: "Large" },
  ],
  "lng-operations-director": [
    { name: "Equinor", industry: "Energy", size: "Large" },
    { name: "Gassco", industry: "Gas Transport", size: "Large" },
    { name: "Höegh LNG", industry: "LNG Shipping", size: "Large" },
    { name: "Vår Energi", industry: "Energy", size: "Large" },
    { name: "Gasum", industry: "Energy", size: "Large" },
  ],
  "ma-telecom-advisor": [
    { name: "Analysys Mason", industry: "Telecom Consulting", size: "Medium" },
    { name: "DNB Markets", industry: "Investment Banking", size: "Large" },
    { name: "PwC", industry: "Professional Services", size: "Large" },
    { name: "EY", industry: "Professional Services", size: "Large" },
    { name: "Deloitte", industry: "Professional Services", size: "Large" },
  ],
  "managing-consultant": [
    { name: "Accenture", industry: "Technology Consulting", size: "Large" },
    { name: "Deloitte", industry: "Professional Services", size: "Large" },
    { name: "PwC", industry: "Professional Services", size: "Large" },
    { name: "Sopra Steria", industry: "Technology Consulting", size: "Large" },
    { name: "Bekk", industry: "Technology Consulting", size: "Medium" },
  ],
  "offshore-construction-manager": [
    { name: "Aker Solutions", industry: "Energy Engineering", size: "Large" },
    { name: "Subsea7", industry: "Subsea Engineering", size: "Large" },
    { name: "Equinor", industry: "Energy", size: "Large" },
    { name: "Aker BP", industry: "Energy", size: "Large" },
    { name: "DOF Group", industry: "Offshore Services", size: "Large" },
  ],
  "offshore-installation-manager": [
    { name: "Equinor", industry: "Energy", size: "Large" },
    { name: "Aker BP", industry: "Energy", size: "Large" },
    { name: "Vår Energi", industry: "Energy", size: "Large" },
    { name: "ConocoPhillips Norway", industry: "Energy", size: "Large" },
    { name: "Odfjell Drilling", industry: "Drilling", size: "Large" },
  ],
  "portfolio-manager": [
    { name: "DNB Asset Management", industry: "Asset Management", size: "Large" },
    { name: "Storebrand", industry: "Asset Management", size: "Large" },
    { name: "Norges Bank Investment Management", industry: "Asset Management", size: "Large" },
    { name: "KLP", industry: "Pension & Insurance", size: "Large" },
    { name: "Sector Asset Management", industry: "Asset Management", size: "Medium" },
  ],
  "private-equity-partner": [
    { name: "Norvestor", industry: "Private Equity", size: "Medium" },
    { name: "FSN Capital", industry: "Private Equity", size: "Medium" },
    { name: "EQT", industry: "Private Equity", size: "Large" },
    { name: "Verdane", industry: "Private Equity", size: "Medium" },
    { name: "Summa Equity", industry: "Private Equity", size: "Medium" },
  ],
  "real-estate-fund-manager": [
    { name: "DNB Næringseiendom", industry: "Real Estate", size: "Large" },
    { name: "Storebrand Eiendom", industry: "Real Estate", size: "Large" },
    { name: "Entra", industry: "Commercial Real Estate", size: "Large" },
    { name: "KLP Eiendom", industry: "Real Estate", size: "Large" },
    { name: "Aspelin Ramm", industry: "Real Estate", size: "Large" },
  ],
  "renewable-energy-director": [
    { name: "Equinor", industry: "Energy", size: "Large" },
    { name: "Statkraft", industry: "Renewable Energy", size: "Large" },
    { name: "Aker Horizons", industry: "Renewable Energy", size: "Large" },
    { name: "Scatec", industry: "Renewable Energy", size: "Large" },
    { name: "Hafslund", industry: "Energy", size: "Large" },
  ],
  "technology-founder": [
    { name: "Self-founded / startup", industry: "Technology", size: "Varies" },
    { name: "Antler", industry: "Startup Generator", size: "Medium" },
    { name: "StartupLab", industry: "Startup Incubator", size: "Medium" },
    { name: "Cognite", industry: "Industrial Software", size: "Large" },
    { name: "Varies / many firms", industry: "Technology", size: "Varies" },
  ],
  "telecom-practice-lead": [
    { name: "Analysys Mason", industry: "Telecom Consulting", size: "Medium" },
    { name: "Accenture", industry: "Technology Consulting", size: "Large" },
    { name: "Sopra Steria", industry: "Technology Consulting", size: "Large" },
    { name: "Capgemini", industry: "Technology Consulting", size: "Large" },
    { name: "Telenor", industry: "Telecommunications", size: "Large" },
  ],
  "telecom-principal-consultant": [
    { name: "Analysys Mason", industry: "Telecom Consulting", size: "Medium" },
    { name: "Accenture", industry: "Technology Consulting", size: "Large" },
    { name: "Sopra Steria", industry: "Technology Consulting", size: "Large" },
    { name: "Telenor", industry: "Telecommunications", size: "Large" },
    { name: "Cisco", industry: "Networking", size: "Large" },
  ],
  "test-pilot": [
    { name: "Forsvaret", industry: "Defence", size: "Large" },
    { name: "Kongsberg Gruppen", industry: "Defence & Aerospace", size: "Large" },
    { name: "SAS", industry: "Aviation", size: "Large" },
    { name: "Widerøe", industry: "Aviation", size: "Large" },
    { name: "Varies / many firms", industry: "Aerospace", size: "Varies" },
  ],
  "venture-capital-partner": [
    { name: "Alliance Venture", industry: "Venture Capital", size: "Small" },
    { name: "Antler", industry: "Venture Capital", size: "Medium" },
    { name: "Northzone", industry: "Venture Capital", size: "Medium" },
    { name: "Verdane", industry: "Venture Capital", size: "Medium" },
    { name: "Schibsted Ventures", industry: "Venture Capital", size: "Medium" },
  ],
  "vp-sales": [
    { name: "Telenor", industry: "Telecommunications", size: "Large" },
    { name: "Visma", industry: "Software", size: "Large" },
    { name: "Cognite", industry: "Industrial Software", size: "Large" },
    { name: "Schibsted", industry: "Media & Technology", size: "Large" },
    { name: "Kahoot!", industry: "EdTech", size: "Large" },
  ],
};
