/**
 * AUTO-GENERATED — do not edit by hand.
 *
 * AI-verified accuracy corrections to the heuristically-derived Career DNA.
 * For each career id, a partial map of judgment-trait → corrected score (0–10).
 * Two independent agents reviewed every career's derived scores; only
 * corrections confirmed by an adversarial verifier are recorded here.
 *
 * Regenerate with: npx tsx scripts/build-career-dna-overrides.ts
 * (reads /tmp/dna-corrections/final-*.json from the verification workflow).
 *
 * Out of scope (never overridden): income-potential, education-length —
 * those are computed deterministically from salary / education data.
 */
import type { CareerDNATraitId } from '@/types/career-dna';

export const DNA_TRAIT_OVERRIDES: Record<string, Partial<Record<CareerDNATraitId, number>>> = {
  "accountant": { 'ai-exposure': 5, 'technical-depth': 5 },
  "acquisitions-manager": { 'independence': 7 },
  "addiction-counsellor": { 'work-life-balance': 3 },
  "adoption-specialist": { 'problem-solving': 8 },
  "adventure-sports-coach": { 'people-interaction': 8 },
  "aerospace-technician": { 'creativity': 3 },
  "affiliate-marketer": { 'people-interaction': 5, 'technical-depth': 5 },
  "agile-coach": { 'leadership': 7 },
  "agricultural-geneticist": { 'creativity': 5 },
  "ai-agent-operations-specialist": { 'creativity': 5 },
  "ai-architect": { 'leadership': 8 },
  "ai-business-analyst": { 'technical-depth': 5 },
  "ai-consultant": { 'leadership': 7 },
  "ai-ethics-specialist": { 'leadership': 6, 'technical-depth': 5, 'work-life-balance': 6 },
  "ai-genomics-researcher": { 'creativity': 8 },
  "ai-governance-specialist": { 'creativity': 3 },
  "ai-infrastructure-architect": { 'leadership': 6 },
  "ai-innovation-lead": { 'problem-solving': 9 },
  "ai-orchestration-engineer": { 'creativity': 5 },
  "ai-platform-engineer": { 'creativity': 5 },
  "ai-platform-operations-engineer": { 'problem-solving': 8 },
  "ai-practice-lead": { 'creativity': 5, 'problem-solving': 8 },
  "ai-product-manager": { 'technical-depth': 5 },
  "ai-research-scientist": { 'creativity': 8, 'technical-depth': 9 },
  "ai-researcher": { 'creativity': 8, 'independence': 6, 'technical-depth': 9 },
  "ai-risk-manager": { 'leadership': 6 },
  "ai-security-engineer": { 'creativity': 5 },
  "ai-site-reliability-engineer": { 'problem-solving': 8 },
  "ai-solutions-architect": { 'leadership': 7, 'work-life-balance': 6 },
  "ai-solutions-engineer": { 'creativity': 6 },
  "ai-systems-architect": { 'leadership': 6 },
  "ai-transformation-consultant": { 'leadership': 7 },
  "air-force-technician": { 'ai-exposure': 5, 'independence': 5 },
  "air-traffic-controller": { 'creativity': 2, 'independence': 2, 'problem-solving': 9, 'technical-depth': 8 },
  "aircraft-maintenance-engineer": { 'creativity': 3 },
  "aircraft-mechanic": { 'creativity': 3 },
  "aircraft-structures-technician": { 'creativity': 3 },
  "airline-pilot": { 'problem-solving': 8 },
  "alliances-director": { 'work-life-balance': 5 },
  "analytics-engineer": { 'creativity': 4 },
  "anesthesiologist": { 'problem-solving': 8 },
  "animator": { 'ai-exposure': 6, 'creativity': 8, 'problem-solving': 6, 'technical-depth': 6 },
  "anti-corruption-investigator": { 'ai-exposure': 5, 'creativity': 3 },
  "anti-money-laundering-investigator": { 'creativity': 3 },
  "ar-vr-developer": { 'ai-exposure': 6, 'technical-depth': 8 },
  "armed-response-officer": { 'ai-exposure': 3, 'work-life-balance': 3 },
  "art-director": { 'creativity': 8 },
  "art-teacher": { 'ai-exposure': 3 },
  "art-therapist": { 'ai-exposure': 2 },
  "artillery-officer": { 'leadership': 7, 'problem-solving': 7 },
  "asphalt-paver": { 'ai-exposure': 2, 'technical-depth': 4 },
  "asset-management-director": { 'ai-exposure': 6 },
  "asset-manager": { 'ai-exposure': 8 },
  "assistant-coach": { 'ai-exposure': 4 },
  "associate-professor": { 'leadership': 7 },
  "astronaut": { 'problem-solving': 8, 'work-life-balance': 3 },
  "astronautical-engineer": { 'ai-exposure': 6 },
  "athletic-trainer": { 'ai-exposure': 3 },
  "auditor": { 'ai-exposure': 5, 'creativity': 3 },
  "auto-mechanic": { 'creativity': 4 },
  "automation-engineer": { 'creativity': 5, 'people-interaction': 5 },
  "autonomous-vehicle-engineer": { 'creativity': 6 },
  "autonomous-workflow-designer": { 'independence': 6 },
  "aviation-director": { 'ai-exposure': 5 },
  "avionics-engineer": { 'people-interaction': 5 },
  "avionics-technician": { 'people-interaction': 5 },
  "backend-engineer-distributed": { 'technical-depth': 9 },
  "baggage-handler": { 'creativity': 3 },
  "bailiff": { 'ai-exposure': 4 },
  "ballistics-expert": { 'ai-exposure': 5 },
  "barista": { 'ai-exposure': 3 },
  "base-jumper": { 'independence': 9, 'people-interaction': 2, 'work-life-balance': 2 },
  "beautician": { 'ai-exposure': 2 },
  "bilingual-customer-support-specialist": { 'creativity': 3, 'problem-solving': 6 },
  "bioinformatics-director": { 'creativity': 6 },
  "biology-teacher": { 'ai-exposure': 4, 'creativity': 5 },
  "biomarker-scientist": { 'creativity': 6, 'work-life-balance': 6 },
  "biomedical-scientist": { 'independence': 5 },
  "bioprocess-scientist": { 'creativity': 6, 'work-life-balance': 5 },
  "biotechnology-executive": { 'ai-exposure': 5, 'leadership': 9 },
  "biotechnology-scientist": { 'creativity': 5, 'work-life-balance': 5 },
  "blockchain-developer": { 'problem-solving': 7, 'technical-depth': 8 },
  "bloodstain-pattern-analyst": { 'ai-exposure': 6 },
  "bomb-disposal-officer": { 'ai-exposure': 4, 'technical-depth': 7, 'work-life-balance': 2 },
  "border-force-officer": { 'ai-exposure': 6, 'work-life-balance': 2 },
  "boxer": { 'ai-exposure': 3 },
  "brand-manager": { 'technical-depth': 4 },
  "breast-surgeon": { 'ai-exposure': 5, 'problem-solving': 8, 'technical-depth': 7 },
  "bricklayer": { 'ai-exposure': 2, 'creativity': 2, 'people-interaction': 3 },
  "building-surveyor": { 'creativity': 3 },
  "bus-driver": { 'ai-exposure': 6 },
  "business-development-director": { 'problem-solving': 8 },
  "business-unit-director": { 'creativity': 5 },
  "busker": { 'ai-exposure': 2, 'people-interaction': 7, 'work-life-balance': 3 },
  "camera-operator": { 'ai-exposure': 5, 'creativity': 5, 'technical-depth': 5 },
  "cancer-genomics-specialist": { 'technical-depth': 9, 'work-life-balance': 5 },
  "capital-markets-adviser": { 'people-interaction': 7 },
  "cardiac-surgeon": { 'creativity': 3, 'technical-depth': 9 },
  "cardiologist": { 'technical-depth': 9 },
  "cardiothoracic-surgeon": { 'creativity': 3, 'technical-depth': 9 },
  "care-assistant": { 'ai-exposure': 2, 'problem-solving': 4 },
  "caregiver": { 'ai-exposure': 2, 'leadership': 2 },
  "carpenter": { 'ai-exposure': 2 },
  "case-worker": { 'problem-solving': 8 },
  "chartered-surveyor": { 'ai-exposure': 3, 'creativity': 2, 'people-interaction': 4, 'problem-solving': 4 },
  "chef": { 'ai-exposure': 2 },
  "chemistry-teacher": { 'ai-exposure': 4 },
  "chief-digital-officer": { 'creativity': 6, 'technical-depth': 4 },
  "chief-executive-officer": { 'creativity': 6 },
  "chief-financial-officer": { 'people-interaction': 7 },
  "chief-information-security-officer": { 'work-life-balance': 3 },
  "chief-marine-engineer": { 'creativity': 3, 'people-interaction': 8, 'work-life-balance': 4 },
  "chief-people-officer": { 'ai-exposure': 5, 'creativity': 5, 'independence': 6 },
  "chief-risk-officer": { 'ai-exposure': 7 },
  "chief-sales-officer": { 'technical-depth': 3 },
  "child-protection-officer": { 'ai-exposure': 2, 'people-interaction': 8, 'work-life-balance': 2 },
  "chiropractor": { 'ai-exposure': 3 },
  "cinematographer": { 'people-interaction': 7, 'technical-depth': 7 },
  "civil-defence-officer": { 'ai-exposure': 4, 'leadership': 7, 'problem-solving': 8 },
  "civil-servant": { 'leadership': 7, 'people-interaction': 4 },
  "civil-works-foreman": { 'leadership': 7, 'people-interaction': 8 },
  "clinical-operations-director": { 'creativity': 2, 'technical-depth': 7 },
  "clinical-researcher": { 'people-interaction': 5 },
  "close-protection-officer": { 'work-life-balance': 3 },
  "cloud-platform-lead": { 'creativity': 6, 'problem-solving': 8 },
  "coast-guard-officer": { 'ai-exposure': 6, 'leadership': 8, 'people-interaction': 8, 'problem-solving': 8 },
  "coast-guard-rescue-swimmer": { 'ai-exposure': 2 },
  "color-grading-specialist": { 'creativity': 7, 'technical-depth': 7 },
  "colorectal-surgeon": { 'technical-depth': 8 },
  "combat-engineer": { 'problem-solving': 7 },
  "commercial-director": { 'people-interaction': 7 },
  "commercial-diver": { 'technical-depth': 6 },
  "commercial-fisherman": { 'ai-exposure': 2, 'creativity': 2, 'technical-depth': 4 },
  "commercial-real-estate-agent": { 'ai-exposure': 4 },
  "commercial-video-producer": { 'leadership': 7 },
  "commissioning-contractor": { 'technical-depth': 6 },
  "commodities-trader": { 'work-life-balance': 4 },
  "community-development-worker": { 'ai-exposure': 3, 'creativity': 6, 'leadership': 6, 'technical-depth': 5 },
  "community-organiser": { 'ai-exposure': 2, 'leadership': 6, 'problem-solving': 6, 'work-life-balance': 4 },
  "company-president": { 'leadership': 9 },
  "company-secretary": { 'ai-exposure': 5 },
  "compliance-director": { 'people-interaction': 5, 'technical-depth': 6 },
  "composer": { 'creativity': 8 },
  "computational-genomics-scientist": { 'creativity': 6, 'independence': 7 },
  "computer-vision-researcher": { 'creativity': 6, 'independence': 7 },
  "concrete-finisher": { 'technical-depth': 4 },
  "confined-space-rescue-technician": { 'ai-exposure': 4 },
  "conservation-geneticist": { 'creativity': 6 },
  "construction-manager": { 'technical-depth': 6 },
  "construction-program-director": { 'people-interaction': 7 },
  "construction-project-manager": { 'ai-exposure': 5 },
  "construction-site-supervisor": { 'people-interaction': 8, 'technical-depth': 4 },
  "construction-worker": { 'people-interaction': 5 },
  "content-creator": { 'leadership': 4, 'problem-solving': 6 },
  "contract-manager": { 'leadership': 6 },
  "control-room-operator": { 'ai-exposure': 8 },
  "controlled-demolition-specialist": { 'technical-depth': 7 },
  "copywriter": { 'creativity': 8, 'technical-depth': 2 },
  "corporate-development-director": { 'technical-depth': 6 },
  "corporate-lawyer": { 'people-interaction': 5, 'technical-depth': 7 },
  "corporate-trainer": { 'problem-solving': 6 },
  "corporate-videographer": { 'ai-exposure': 4 },
  "corrections-officer": { 'ai-exposure': 4 },
  "cosmetic-surgeon": { 'ai-exposure': 4, 'creativity': 5 },
  "counsellor": { 'creativity': 6, 'independence': 7 },
  "country-manager": { 'independence': 7 },
  "courier": { 'ai-exposure': 5 },
  "crane-operator": { 'creativity': 3 },
  "crime-analyst": { 'creativity': 5 },
  "crime-scene-investigator": { 'technical-depth': 6 },
  "criminal-intelligence-analyst": { 'creativity': 5 },
  "criminal-profiler": { 'work-life-balance': 5 },
  "crisis-intervention-specialist": { 'creativity': 5 },
  "crispr-engineer": { 'work-life-balance': 5 },
  "crop-improvement-scientist": { 'creativity': 5 },
  "cross-api-integration-architect": { 'ai-exposure': 6 },
  "cross-oss-bss-product-mgr": { 'creativity': 5, 'technical-depth': 4 },
  "cross-platform-product-owner": { 'creativity': 3, 'technical-depth': 4 },
  "crypto-trader": { 'creativity': 3, 'independence': 8, 'work-life-balance': 2 },
  "curriculum-developer": { 'people-interaction': 5 },
  "customer-service-rep": { 'problem-solving': 5 },
  "customs-officer": { 'ai-exposure': 4 },
  "cyber-security-manager": { 'ai-exposure': 6, 'technical-depth': 6 },
  "cyber-warfare-specialist": { 'ai-exposure': 8, 'creativity': 7, 'independence': 7, 'problem-solving': 8, 'technical-depth': 9 },
  "cybercrime-investigator": { 'creativity': 3 },
  "cyberforsvaret-cyber-officer": { 'ai-exposure': 8, 'leadership': 8, 'technical-depth': 6 },
  "cybersecurity-analyst": { 'problem-solving': 6 },
  "data-engineer": { 'creativity': 3, 'people-interaction': 5 },
  "data-science-director": { 'technical-depth': 5 },
  "day-trader": { 'independence': 8, 'technical-depth': 5, 'work-life-balance': 3 },
  "deckhand": { 'ai-exposure': 2 },
  "delivery-driver": { 'people-interaction': 5 },
  "demolition-worker": { 'technical-depth': 4 },
  "dental-technician": { 'technical-depth': 6 },
  "derivatives-trader": { 'ai-exposure': 7, 'problem-solving': 8, 'technical-depth': 8, 'work-life-balance': 4 },
  "dermatologic-surgeon": { 'ai-exposure': 4, 'independence': 7, 'technical-depth': 7 },
  "dermatologist": { 'technical-depth': 8 },
  "detective": { 'independence': 6, 'leadership': 6 },
  "dietitian": { 'technical-depth': 7, 'work-life-balance': 5 },
  "diplomat": { 'ai-exposure': 4, 'leadership': 7 },
  "director-of-engineering": { 'technical-depth': 5 },
  "director-of-product": { 'creativity': 5 },
  "disability-support-worker": { 'ai-exposure': 3, 'technical-depth': 3 },
  "dispositions-manager": { 'creativity': 5 },
  "distinguished-engineer": { 'leadership': 8 },
  "district-heating-technician": { 'ai-exposure': 5, 'people-interaction': 6, 'problem-solving': 6 },
  "dj": { 'people-interaction': 7, 'technical-depth': 5, 'work-life-balance': 3 },
  "dna-evidence-specialist": { 'ai-exposure': 3 },
  "documentary-filmmaker": { 'creativity': 8, 'leadership': 7, 'people-interaction': 7 },
  "dog-groomer": { 'people-interaction': 8 },
  "domestic-violence-advocate": { 'creativity': 5, 'independence': 6 },
  "drilling-manager": { 'problem-solving': 8, 'work-life-balance': 2 },
  "drilling-technician": { 'problem-solving': 7, 'technical-depth': 6 },
  "driving-instructor": { 'ai-exposure': 2 },
  "drone-operator-uav": { 'independence': 5, 'people-interaction': 6 },
  "drone-videographer": { 'ai-exposure': 4, 'creativity': 5 },
  "drug-discovery-scientist": { 'work-life-balance': 5 },
  "drug-enforcement-investigator": { 'ai-exposure': 5, 'work-life-balance': 4 },
  "dynamic-positioning-operator": { 'technical-depth': 7 },
  "education-consultant": { 'work-life-balance': 5 },
  "electrical-commissioning-technician": { 'ai-exposure': 4, 'creativity': 3 },
  "electrical-contractor": { 'ai-exposure': 5 },
  "electrical-engineer": { 'ai-exposure': 7 },
  "electrician": { 'people-interaction': 6, 'technical-depth': 7 },
  "electro-technical-officer": { 'work-life-balance': 3 },
  "embedded-developer": { 'people-interaction': 4 },
  "emergency-dispatcher": { 'people-interaction': 8 },
  "emergency-medicine-physician": { 'technical-depth': 8 },
  "emt": { 'ai-exposure': 2 },
  "endocrine-surgeon": { 'technical-depth': 7 },
  "energy-commissioning-technician": { 'people-interaction': 5 },
  "energy-trading-manager": { 'ai-exposure': 7 },
  "energy-transition-consultant": { 'ai-exposure': 5, 'work-life-balance': 4 },
  "enterprise-architect": { 'leadership': 7 },
  "environmental-genomics-scientist": { 'creativity': 6 },
  "environmental-lawyer": { 'ai-exposure': 6 },
  "eod-technician": { 'ai-exposure': 4, 'work-life-balance': 2 },
  "epigenetics-researcher": { 'creativity': 5 },
  "equipment-manager": { 'ai-exposure': 4, 'leadership': 3, 'people-interaction': 3 },
  "escrow-officer": { 'creativity': 2 },
  "esg-counsel": { 'ai-exposure': 6 },
  "esg-director": { 'ai-exposure': 5 },
  "estate-manager": { 'ai-exposure': 4 },
  "etjenesten-sigint-analyst": { 'ai-exposure': 7, 'people-interaction': 4, 'technical-depth': 6 },
  "event-photographer": { 'ai-exposure': 4 },
  "evolutionary-biologist": { 'creativity': 5 },
  "executive-assistant": { 'people-interaction': 6 },
  "expedition-leader": { 'problem-solving': 8 },
  "extreme-sports-athlete": { 'leadership': 2, 'people-interaction': 2, 'work-life-balance': 2 },
  "extreme-sports-event-organizer": { 'creativity': 6 },
  "extreme-sports-photographer": { 'independence': 8 },
  "extreme-sports-safety-coordinator": { 'ai-exposure': 3, 'leadership': 7, 'problem-solving': 8, 'work-life-balance': 3 },
  "extreme-sports-videographer": { 'independence': 8, 'people-interaction': 5 },
  "facility-manager": { 'ai-exposure': 5, 'work-life-balance': 4 },
  "family-support-worker": { 'ai-exposure': 2, 'work-life-balance': 2 },
  "farmer": { 'leadership': 2, 'work-life-balance': 3 },
  "fashion-designer": { 'creativity': 8 },
  "film-composer": { 'creativity': 8 },
  "film-director": { 'people-interaction': 8, 'problem-solving': 8 },
  "finance-director": { 'problem-solving': 7 },
  "finance-project-manager": { 'independence': 5 },
  "financial-analyst": { 'people-interaction': 6, 'work-life-balance': 5 },
  "financial-crime-investigator": { 'technical-depth': 7 },
  "fingerprint-examiner": { 'creativity': 4, 'problem-solving': 6 },
  "firefighter": { 'creativity': 3, 'technical-depth': 6 },
  "fitness-instructor": { 'ai-exposure': 2 },
  "flight-dynamics-engineer": { 'ai-exposure': 8, 'problem-solving': 8 },
  "flight-engineer-space": { 'work-life-balance': 3 },
  "flight-operations-director": { 'ai-exposure': 5, 'problem-solving': 7 },
  "food-delivery-rider": { 'people-interaction': 3, 'technical-depth': 2 },
  "food-safety-inspector": { 'ai-exposure': 3, 'creativity': 3, 'people-interaction': 5 },
  "food-technologist": { 'ai-exposure': 5 },
  "footballer": { 'work-life-balance': 2 },
  "forensic-dna-analyst": { 'creativity': 3 },
  "forensic-toxicologist": { 'ai-exposure': 5, 'creativity': 4 },
  "forestry-worker": { 'ai-exposure': 2, 'leadership': 1 },
  "forex-trader": { 'independence': 8, 'work-life-balance': 3 },
  "forsvaret-chaplain": { 'ai-exposure': 3 },
  "forsvaret-combat-medic": { 'ai-exposure': 3, 'creativity': 3 },
  "forsvaret-cryptologist": { 'independence': 7, 'people-interaction': 3 },
  "forsvaret-military-lawyer": { 'ai-exposure': 5, 'technical-depth': 7 },
  "forsvaret-signals-officer": { 'leadership': 7 },
  "forsvaret-space-operations-officer": { 'leadership': 7 },
  "foster-care-coordinator": { 'ai-exposure': 4, 'problem-solving': 8 },
  "fractional-chief-architect": { 'independence': 8 },
  "fractional-cio": { 'independence': 8, 'leadership': 7 },
  "fractional-ciso": { 'ai-exposure': 6, 'creativity': 3, 'independence': 8, 'leadership': 7, 'technical-depth': 6 },
  "fractional-cto": { 'independence': 8, 'leadership': 7 },
  "freediving-instructor": { 'ai-exposure': 3 },
  "freelance-photographer": { 'ai-exposure': 4, 'creativity': 6 },
  "freestyle-ski-instructor": { 'ai-exposure': 2 },
  "freestyle-snowboard-instructor": { 'ai-exposure': 2 },
  "freight-driver": { 'ai-exposure': 5 },
  "freight-forwarder": { 'ai-exposure': 5 },
  "freight-handler": { 'ai-exposure': 6 },
  "fund-manager": { 'people-interaction': 6 },
  "game-designer": { 'creativity': 8, 'technical-depth': 5 },
  "game-director": { 'ai-exposure': 5, 'technical-depth': 5 },
  "gaming-streamer": { 'people-interaction': 8 },
  "gardener": { 'ai-exposure': 2, 'people-interaction': 5, 'problem-solving': 5 },
  "gas-network-technician": { 'ai-exposure': 4, 'work-life-balance': 5 },
  "gas-turbine-technician": { 'work-life-balance': 3 },
  "general-counsel": { 'leadership': 8, 'technical-depth': 7 },
  "general-manager": { 'creativity': 5, 'independence': 7 },
  "general-practitioner": { 'technical-depth': 8 },
  "general-surgeon": { 'technical-depth': 8 },
  "generative-ai-research-scientist": { 'independence': 7 },
  "genetic-counsellor": { 'technical-depth': 6 },
  "genetic-data-analyst": { 'creativity': 4 },
  "genomic-data-scientist": { 'creativity': 6 },
  "genomics-product-manager": { 'ai-exposure': 7, 'creativity': 6 },
  "global-account-director": { 'creativity': 5 },
  "global-brand-director": { 'ai-exposure': 5 },
  "grid-transformation-lead": { 'ai-exposure': 7 },
  "ground-control-operator": { 'ai-exposure': 5, 'creativity': 2, 'work-life-balance': 3 },
  "groundskeeper": { 'ai-exposure': 4, 'people-interaction': 2, 'problem-solving': 2 },
  "group-product-manager": { 'creativity': 5 },
  "hairdresser": { 'ai-exposure': 2 },
  "hairstylist": { 'creativity': 6 },
  "hand-surgeon": { 'ai-exposure': 5, 'independence': 7, 'technical-depth': 8 },
  "hang-gliding-instructor": { 'ai-exposure': 2 },
  "head-of-cloud": { 'technical-depth': 6 },
  "head-of-cyber-security": { 'ai-exposure': 6, 'technical-depth': 6 },
  "head-of-data-engineering": { 'creativity': 6 },
  "head-of-enterprise-architecture": { 'creativity': 6 },
  "head-of-legal": { 'independence': 6, 'technical-depth': 7 },
  "head-of-network-transformation": { 'problem-solving': 7 },
  "head-of-product": { 'creativity': 5 },
  "head-of-provisioning": { 'problem-solving': 7 },
  "head-of-revenue": { 'problem-solving': 8 },
  "head-of-talent": { 'people-interaction': 7 },
  "healthcare-data-scientist": { 'ai-exposure': 9 },
  "healthcare-worker": { 'ai-exposure': 2, 'problem-solving': 3, 'technical-depth': 2 },
  "heavy-equipment-mechanic": { 'technical-depth': 6 },
  "heavy-equipment-operator": { 'ai-exposure': 3, 'creativity': 2 },
  "hedge-fund-manager": { 'independence': 8, 'technical-depth': 7 },
  "helicopter-pilot": { 'problem-solving': 8, 'technical-depth': 7 },
  "hepatobiliary-surgeon": { 'ai-exposure': 5 },
  "high-voltage-electrician": { 'ai-exposure': 3 },
  "homelessness-support-worker": { 'work-life-balance': 2 },
  "homicide-detective": { 'work-life-balance': 3 },
  "hospital-administrator": { 'ai-exposure': 4, 'leadership': 9 },
  "hostage-negotiator": { 'creativity': 6, 'leadership': 6, 'problem-solving': 8, 'work-life-balance': 2 },
  "hotel-housekeeper": { 'ai-exposure': 2, 'technical-depth': 2 },
  "house-cleaner": { 'technical-depth': 2 },
  "housing-support-officer": { 'ai-exposure': 4 },
  "hr-director": { 'creativity': 5, 'problem-solving': 6 },
  "human-genetics-researcher": { 'creativity': 5 },
  "human-rights-lawyer": { 'ai-exposure': 5 },
  "human-trafficking-investigator": { 'work-life-balance': 4 },
  "hydraulic-systems-technician": { 'technical-depth': 7 },
  "iac-specialist": { 'independence': 6 },
  "ice-climbing-guide": { 'ai-exposure': 2 },
  "illustrator": { 'ai-exposure': 4, 'creativity': 8 },
  "immigration-lawyer": { 'ai-exposure': 5 },
  "immigration-officer": { 'ai-exposure': 5, 'people-interaction': 8 },
  "independent-consultant": { 'ai-exposure': 6 },
  "independent-contractor-technical": { 'people-interaction': 4 },
  "industrial-abseiler": { 'ai-exposure': 3 },
  "industrial-cleaner": { 'technical-depth': 3 },
  "industrial-electrician": { 'ai-exposure': 4 },
  "industrial-fitter": { 'technical-depth': 5 },
  "industrial-instrumentation-technician": { 'people-interaction': 5 },
  "infantry-officer": { 'ai-exposure': 3, 'leadership': 8, 'problem-solving': 7 },
  "infrastructure-investment-manager": { 'independence': 8, 'technical-depth': 6 },
  "infrastructure-program-director": { 'ai-exposure': 4 },
  "instagram-influencer": { 'problem-solving': 6 },
  "instrumentation-contractor": { 'technical-depth': 6 },
  "instrumentation-technician": { 'ai-exposure': 3 },
  "insurance-advisor": { 'ai-exposure': 4 },
  "intensive-care-physician": { 'work-life-balance': 2 },
  "international-trade-lawyer": { 'ai-exposure': 6 },
  "interpreter": { 'ai-exposure': 2, 'problem-solving': 7, 'work-life-balance': 2 },
  "investment-analyst": { 'people-interaction': 4 },
  "investment-banker": { 'technical-depth': 7 },
  "investment-manager": { 'independence': 6 },
  "irrigation-technician": { 'technical-depth': 6 },
  "it-programme-manager": { 'technical-depth': 3 },
  "journalist": { 'people-interaction': 7, 'technical-depth': 3 },
  "judge": { 'creativity': 4, 'problem-solving': 8, 'technical-depth': 7 },
  "kitchen-porter": { 'creativity': 2 },
  "lab-technician": { 'ai-exposure': 5, 'problem-solving': 5 },
  "language-data-annotator": { 'problem-solving': 4, 'technical-depth': 4 },
  "launch-operations-engineer": { 'work-life-balance': 3 },
  "lead-enterprise-architect": { 'creativity': 6, 'work-life-balance': 5 },
  "learning-support-specialist": { 'ai-exposure': 3 },
  "leasing-agent": { 'ai-exposure': 3 },
  "level-iii-ndt-inspector": { 'ai-exposure': 5, 'work-life-balance': 5 },
  "lexicographer": { 'ai-exposure': 6 },
  "licensed-aircraft-engineer": { 'creativity': 3 },
  "lifeguard": { 'ai-exposure': 3 },
  "lighting-technician": { 'ai-exposure': 2 },
  "linguist": { 'independence': 7, 'people-interaction': 3 },
  "llm-engineer": { 'ai-exposure': 8 },
  "lng-operations-director": { 'ai-exposure': 7 },
  "loan-officer": { 'ai-exposure': 5 },
  "logistics-coordinator": { 'people-interaction': 6 },
  "logistics-driver": { 'ai-exposure': 5 },
  "logistics-officer": { 'ai-exposure': 5 },
  "ma-director": { 'creativity': 5, 'technical-depth': 6, 'work-life-balance': 3 },
  "ma-telecom-advisor": { 'problem-solving': 7 },
  "magistrate": { 'creativity': 4, 'technical-depth': 6 },
  "maintenance-release-engineer": { 'creativity': 2, 'leadership': 2 },
  "maintenance-shutdown-contractor": { 'ai-exposure': 5, 'technical-depth': 6 },
  "malware-analyst": { 'creativity': 3 },
  "managing-director": { 'creativity': 5, 'independence': 8 },
  "marine": { 'ai-exposure': 2, 'technical-depth': 5 },
  "marine-electrician": { 'ai-exposure': 5, 'people-interaction': 4, 'work-life-balance': 3 },
  "marine-engineer": { 'work-life-balance': 3 },
  "market-analyst": { 'work-life-balance': 4 },
  "marketing-manager": { 'technical-depth': 4 },
  "massage-therapist": { 'ai-exposure': 2 },
  "material-handler": { 'technical-depth': 3 },
  "materials-engineer": { 'ai-exposure': 5 },
  "mechanical-commissioning-technician": { 'technical-depth': 5 },
  "mechanical-maintenance-contractor": { 'ai-exposure': 4 },
  "medical-assistant": { 'problem-solving': 3, 'technical-depth': 3 },
  "medical-laboratory-technician": { 'work-life-balance': 6 },
  "medical-science-liaison": { 'technical-depth': 8 },
  "medical-secretary": { 'leadership': 2 },
  "mental-health-support-worker": { 'ai-exposure': 3, 'work-life-balance': 3 },
  "merchant-navy-sailor": { 'ai-exposure': 2 },
  "military-intelligence-analyst": { 'ai-exposure': 6, 'independence': 6 },
  "military-officer": { 'leadership': 7, 'problem-solving': 7 },
  "military-pilot": { 'independence': 6, 'people-interaction': 5, 'problem-solving': 8, 'technical-depth': 8 },
  "military-police": { 'ai-exposure': 5, 'creativity': 4 },
  "mission-specialist": { 'work-life-balance': 3 },
  "mma-fighter": { 'ai-exposure': 3 },
  "molecular-diagnostics-scientist": { 'creativity': 5 },
  "mortgage-advisor": { 'ai-exposure': 5 },
  "motion-graphics-designer": { 'problem-solving': 5, 'technical-depth': 7 },
  "motocross-rider": { 'ai-exposure': 2 },
  "mountain-rescue-specialist": { 'ai-exposure': 2, 'work-life-balance': 3 },
  "mountaineering-guide": { 'ai-exposure': 2 },
  "mounted-police-officer": { 'work-life-balance': 4 },
  "music-lecturer": { 'creativity': 7, 'independence': 6, 'leadership': 6 },
  "music-teacher": { 'creativity': 5, 'problem-solving': 6 },
  "musician": { 'ai-exposure': 3, 'creativity': 8 },
  "nail-technician": { 'ai-exposure': 2 },
  "nav-case-worker": { 'ai-exposure': 5, 'people-interaction': 8 },
  "naval-officer": { 'leadership': 8, 'people-interaction': 8, 'problem-solving': 7, 'technical-depth': 6 },
  "navy-diver": { 'ai-exposure': 2, 'work-life-balance': 2 },
  "neurologist": { 'technical-depth': 8 },
  "neurosurgeon": { 'technical-depth': 9 },
  "nlp-engineer": { 'creativity': 6, 'people-interaction': 4 },
  "nlp-research-scientist": { 'independence': 7 },
  "non-destructive-testing-technician": { 'ai-exposure': 5, 'creativity': 2 },
  "nutritionist": { 'creativity': 6 },
  "obstetrician-gynaecologist": { 'technical-depth': 8 },
  "occupational-therapist": { 'ai-exposure': 4 },
  "occupational-therapy-assistant": { 'ai-exposure': 2, 'problem-solving': 6 },
  "offensive-security-engineer": { 'creativity': 7, 'people-interaction': 4 },
  "office-administrator": { 'ai-exposure': 4, 'people-interaction': 5 },
  "offshore-construction-manager": { 'problem-solving': 8, 'work-life-balance': 2 },
  "offshore-installation-manager": { 'problem-solving': 8, 'technical-depth': 7 },
  "offshore-instrumentation-technician": { 'problem-solving': 8, 'technical-depth': 6 },
  "offshore-mechanical-technician": { 'work-life-balance': 3 },
  "offshore-production-technician": { 'technical-depth': 6 },
  "offshore-service-contractor": { 'leadership': 6 },
  "offshore-wind-technician": { 'creativity': 3, 'work-life-balance': 4 },
  "oncological-surgeon": { 'ai-exposure': 5, 'technical-depth': 7 },
  "oncologist": { 'problem-solving': 8, 'technical-depth': 7 },
  "operations-director": { 'creativity': 5, 'independence': 6 },
  "ophthalmic-surgeon": { 'ai-exposure': 5, 'technical-depth': 8 },
  "ophthalmologist": { 'technical-depth': 8 },
  "optician": { 'ai-exposure': 5 },
  "options-trader": { 'ai-exposure': 7, 'technical-depth': 8, 'work-life-balance': 4 },
  "oral-maxillofacial-surgeon": { 'ai-exposure': 5, 'problem-solving': 7, 'technical-depth': 7 },
  "orchestra-member": { 'ai-exposure': 2, 'work-life-balance': 7 },
  "org-transformation-director": { 'people-interaction': 7 },
  "organized-crime-investigator": { 'ai-exposure': 6 },
  "orthodontist": { 'ai-exposure': 4 },
  "orthopaedic-surgeon": { 'creativity': 3, 'technical-depth': 8 },
  "osint-analyst": { 'creativity': 5 },
  "oss-bss-transformation-lead": { 'technical-depth': 6 },
  "outdoor-survival-instructor": { 'ai-exposure': 2 },
  "outreach-worker": { 'ai-exposure': 2, 'work-life-balance': 2 },
  "overhead-line-equipment-technician": { 'technical-depth': 7, 'work-life-balance': 5 },
  "painter": { 'ai-exposure': 2 },
  "painter-decorator": { 'ai-exposure': 2, 'people-interaction': 3 },
  "paragliding-instructor": { 'ai-exposure': 2 },
  "paramedic": { 'ai-exposure': 4, 'problem-solving': 8 },
  "paratrooper": { 'ai-exposure': 2 },
  "park-ranger": { 'work-life-balance': 6 },
  "pastry-chef": { 'ai-exposure': 3, 'technical-depth': 5 },
  "patient-navigator": { 'ai-exposure': 2 },
  "payload-specialist": { 'work-life-balance': 3 },
  "pediatrician": { 'technical-depth': 8 },
  "pension-fund-manager": { 'work-life-balance': 5 },
  "performance-marketing-director": { 'creativity': 3, 'technical-depth': 7 },
  "peripheral-nerve-surgeon": { 'ai-exposure': 5, 'technical-depth': 8 },
  "petroleum-engineer": { 'technical-depth': 9 },
  "pharmacogenomics-specialist": { 'work-life-balance': 5 },
  "pharmacy-technician": { 'ai-exposure': 5, 'work-life-balance': 5 },
  "phlebotomist": { 'ai-exposure': 2, 'problem-solving': 5, 'technical-depth': 4 },
  "photojournalist": { 'ai-exposure': 4, 'creativity': 6, 'problem-solving': 8, 'work-life-balance': 2 },
  "piercing-specialist": { 'ai-exposure': 2 },
  "pipefitter": { 'problem-solving': 6 },
  "plant-geneticist": { 'creativity': 5 },
  "plastic-surgeon": { 'ai-exposure': 4, 'creativity': 6, 'technical-depth': 8 },
  "platform-architect": { 'leadership': 6 },
  "platform-director-media": { 'ai-exposure': 6, 'technical-depth': 5 },
  "platform-engineer": { 'creativity': 5, 'people-interaction': 5 },
  "plumber": { 'people-interaction': 7, 'technical-depth': 7 },
  "podcast-host": { 'people-interaction': 8, 'problem-solving': 7, 'technical-depth': 5 },
  "police-dog-handler": { 'ai-exposure': 2, 'work-life-balance': 4 },
  "police-officer": { 'creativity': 3 },
  "population-geneticist": { 'creativity': 5 },
  "portfolio-manager": { 'ai-exposure': 7, 'leadership': 8 },
  "post-production-specialist": { 'creativity': 6, 'technical-depth': 7 },
  "power-line-technician": { 'ai-exposure': 2 },
  "power-plant-technician": { 'technical-depth': 7, 'work-life-balance': 3 },
  "precision-medicine-data-scientist": { 'ai-exposure': 8 },
  "precision-medicine-specialist": { 'work-life-balance': 6 },
  "prenatal-genetic-counsellor": { 'ai-exposure': 3 },
  "principal-ai-engineer": { 'technical-depth': 9 },
  "principal-data-scientist": { 'creativity': 7 },
  "principal-enterprise-architect": { 'work-life-balance': 5 },
  "principal-network-engineer": { 'leadership': 6, 'technical-depth': 8 },
  "principal-product-manager": { 'creativity': 5 },
  "principal-security-consultant": { 'ai-exposure': 6, 'technical-depth': 7 },
  "principal-software-engineer": { 'leadership': 6 },
  "principal-technical-program-manager": { 'technical-depth': 5 },
  "principal-telecom-consultant": { 'work-life-balance': 5 },
  "private-equity-associate": { 'technical-depth': 6 },
  "private-equity-lawyer": { 'independence': 6 },
  "private-equity-vp": { 'leadership': 8, 'problem-solving': 7, 'technical-depth': 6 },
  "private-music-tutor": { 'creativity': 5, 'problem-solving': 6 },
  "private-tutor": { 'problem-solving': 5 },
  "probation-officer": { 'problem-solving': 8 },
  "process-operator": { 'people-interaction': 5 },
  "product-director-consumer": { 'ai-exposure': 6, 'creativity': 5, 'technical-depth': 4 },
  "product-manager-tech": { 'leadership': 7 },
  "product-strategy-lead": { 'creativity': 5, 'leadership': 6, 'technical-depth': 4 },
  "professor": { 'leadership': 8 },
  "project-manager": { 'technical-depth': 4 },
  "prompt-engineer": { 'technical-depth': 5 },
  "proofreader": { 'ai-exposure': 5 },
  "property-administrator": { 'ai-exposure': 5, 'technical-depth': 2 },
  "property-developer": { 'creativity': 6, 'independence': 8, 'leadership': 7, 'problem-solving': 8, 'technical-depth': 4 },
  "property-inspector": { 'creativity': 2 },
  "property-lawyer": { 'creativity': 5 },
  "property-manager": { 'ai-exposure': 4, 'leadership': 5 },
  "property-valuer": { 'creativity': 2, 'people-interaction': 4 },
  "prosecutor": { 'creativity': 4, 'people-interaction': 6, 'technical-depth': 7 },
  "protection-and-control-technician": { 'ai-exposure': 4 },
  "psychotherapist": { 'ai-exposure': 2 },
  "public-health-social-worker": { 'leadership': 6 },
  "public-health-specialist": { 'ai-exposure': 5, 'technical-depth': 5 },
  "public-order-officer": { 'ai-exposure': 2, 'work-life-balance': 4 },
  "pump-technician": { 'creativity': 3 },
  "quality-assurance-engineer": { 'ai-exposure': 5, 'creativity': 3 },
  "quality-assurance-food": { 'ai-exposure': 5 },
  "quantity-surveyor": { 'ai-exposure': 4 },
  "quarry-worker": { 'technical-depth': 4 },
  "radiologic-technologist": { 'leadership': 2 },
  "rail-signalling-technician": { 'technical-depth': 7 },
  "rail-systems-technician": { 'technical-depth': 7 },
  "rally-driver": { 'ai-exposure': 3, 'people-interaction': 5, 'problem-solving': 8 },
  "ranch-worker": { 'ai-exposure': 2 },
  "real-estate-agent": { 'independence': 7 },
  "real-estate-appraiser": { 'ai-exposure': 4, 'people-interaction': 4 },
  "real-estate-broker": { 'leadership': 8 },
  "real-estate-consultant": { 'ai-exposure': 6, 'creativity': 6 },
  "real-estate-photographer": { 'creativity': 7 },
  "real-estate-sales-manager": { 'work-life-balance': 5 },
  "real-estate-valuer": { 'people-interaction': 4 },
  "recycling-plant-operator": { 'ai-exposure': 5 },
  "refuge-worker": { 'creativity': 5, 'work-life-balance': 2 },
  "regional-director": { 'creativity': 5, 'independence': 7, 'people-interaction': 7 },
  "rehabilitation-worker": { 'ai-exposure': 3, 'technical-depth': 4 },
  "reinforcement-learning-researcher": { 'independence': 7 },
  "renewable-energy-director": { 'ai-exposure': 6 },
  "renewable-energy-tech": { 'problem-solving': 7, 'technical-depth': 8 },
  "residential-care-worker": { 'work-life-balance': 2 },
  "respiratory-therapist": { 'technical-depth': 6 },
  "restaurant-manager": { 'ai-exposure': 3 },
  "restaurant-owner": { 'independence': 9, 'leadership': 8 },
  "retail-assistant": { 'ai-exposure': 2, 'leadership': 1 },
  "rheumatologist": { 'creativity': 3 },
  "risk-analyst": { 'ai-exposure': 7, 'technical-depth': 7 },
  "risk-and-compliance-director": { 'ai-exposure': 6, 'technical-depth': 6 },
  "rock-climbing-guide": { 'ai-exposure': 2 },
  "roofer": { 'ai-exposure': 2 },
  "rotating-equipment-specialist": { 'leadership': 2 },
  "rov-pilot-technician": { 'technical-depth': 7 },
  "rte": { 'technical-depth': 4 },
  "rugby-player": { 'ai-exposure': 3 },
  "safeguarding-officer": { 'ai-exposure': 3 },
  "sales-director": { 'creativity': 5 },
  "satellite-engineer": { 'ai-exposure': 6 },
  "saturation-diver": { 'technical-depth': 7 },
  "scada-technician": { 'people-interaction': 5 },
  "scaffolder": { 'people-interaction': 5 },
  "school-counsellor": { 'ai-exposure': 3 },
  "scrum-master": { 'leadership': 7 },
  "scuba-diving-instructor": { 'ai-exposure': 3 },
  "search-and-rescue-operator": { 'ai-exposure': 4, 'work-life-balance': 3 },
  "secondary-teacher": { 'ai-exposure': 4 },
  "security-guard": { 'technical-depth': 3, 'work-life-balance': 3 },
  "security-operations-director": { 'technical-depth': 6 },
  "security-operations-manager": { 'work-life-balance': 4 },
  "senior-engineering-manager": { 'technical-depth': 5 },
  "senior-lecturer": { 'leadership': 7 },
  "senior-legal-counsel": { 'people-interaction': 6, 'problem-solving': 6, 'technical-depth': 7 },
  "senior-product-manager": { 'ai-exposure': 4, 'creativity': 5, 'technical-depth': 4 },
  "senior-software-engineer": { 'technical-depth': 8 },
  "senior-wind-turbine-technician": { 'leadership': 8 },
  "session-musician": { 'ai-exposure': 3, 'work-life-balance': 4 },
  "sewer-maintenance-worker": { 'technical-depth': 4 },
  "shepherd": { 'ai-exposure': 2, 'leadership': 1 },
  "ships-electrical-engineer": { 'work-life-balance': 3 },
  "short-form-video-creator": { 'problem-solving': 7 },
  "site-manager": { 'ai-exposure': 5 },
  "site-reliability-engineer": { 'creativity': 5, 'problem-solving': 8, 'work-life-balance': 4 },
  "ski-patrol-officer": { 'ai-exposure': 2 },
  "skincare-specialist": { 'problem-solving': 6 },
  "skydiving-instructor": { 'ai-exposure': 2 },
  "smokejumper": { 'ai-exposure': 2 },
  "sniper": { 'ai-exposure': 2, 'creativity': 2, 'independence': 6, 'people-interaction': 3, 'technical-depth': 6 },
  "soc-analyst": { 'creativity': 2, 'people-interaction': 4 },
  "social-services-manager": { 'ai-exposure': 4, 'independence': 7, 'problem-solving': 7 },
  "social-studies-teacher": { 'ai-exposure': 4, 'creativity': 5 },
  "social-worker": { 'work-life-balance': 3 },
  "software-developer": { 'technical-depth': 7 },
  "soldier": { 'ai-exposure': 2, 'creativity': 2, 'technical-depth': 2 },
  "sommelier": { 'ai-exposure': 2, 'technical-depth': 6 },
  "sound-editor": { 'technical-depth': 7 },
  "sound-engineer": { 'problem-solving': 7 },
  "sovereign-wealth-fund-manager": { 'ai-exposure': 7 },
  "space-mission-planner": { 'ai-exposure': 6 },
  "space-systems-engineer": { 'ai-exposure': 6 },
  "spacecraft-pilot": { 'problem-solving': 9, 'technical-depth': 8, 'work-life-balance': 3 },
  "spacewalk-specialist": { 'problem-solving': 8, 'work-life-balance': 3 },
  "special-forces-operator": { 'ai-exposure': 2, 'creativity': 6, 'problem-solving': 8 },
  "special-needs-assistant": { 'ai-exposure': 3 },
  "specialist-inspection-contractor": { 'creativity': 6 },
  "speech-language-therapist": { 'creativity': 6, 'technical-depth': 6 },
  "spinal-surgeon": { 'technical-depth': 8 },
  "sponsorship-manager": { 'leadership': 6 },
  "sports-coach": { 'ai-exposure': 4, 'leadership': 7 },
  "sports-commentator": { 'people-interaction': 2, 'work-life-balance': 4 },
  "sports-event-coordinator": { 'work-life-balance': 3 },
  "sports-event-manager": { 'creativity': 6, 'problem-solving': 9, 'work-life-balance': 3 },
  "sports-marketing-manager": { 'people-interaction': 8, 'work-life-balance': 5 },
  "sports-medicine-physician": { 'ai-exposure': 3 },
  "sports-nutritionist": { 'ai-exposure': 5 },
  "sports-photographer": { 'creativity': 7, 'independence': 8, 'people-interaction': 2 },
  "sports-physiotherapist": { 'problem-solving': 7 },
  "sports-psychologist": { 'ai-exposure': 4 },
  "staff-engineer": { 'leadership': 6, 'technical-depth': 8 },
  "steam-turbine-technician": { 'creativity': 3, 'people-interaction': 4, 'technical-depth': 8 },
  "strategic-partnerships-lead": { 'people-interaction': 7 },
  "structured-finance-specialist": { 'technical-depth': 7 },
  "studio-director": { 'problem-solving': 7 },
  "studio-photographer": { 'ai-exposure': 4, 'creativity': 6, 'technical-depth': 6 },
  "stunt-performer": { 'ai-exposure': 2, 'work-life-balance': 3 },
  "submarine-officer": { 'leadership': 6, 'people-interaction': 6, 'technical-depth': 7 },
  "subsea-technician": { 'technical-depth': 6 },
  "substance-abuse-counsellor": { 'creativity': 5, 'independence': 7, 'work-life-balance': 3 },
  "substation-technician": { 'ai-exposure': 4 },
  "subtitler": { 'technical-depth': 5 },
  "support-worker": { 'ai-exposure': 3, 'leadership': 2 },
  "surgeon": { 'technical-depth': 8 },
  "surveillance-officer": { 'work-life-balance': 4 },
  "surveyor": { 'creativity': 3, 'technical-depth': 7 },
  "swim-instructor": { 'ai-exposure': 3 },
  "systems-biologist": { 'creativity': 6 },
  "systems-engineer": { 'ai-exposure': 4 },
  "tank-commander": { 'technical-depth': 6 },
  "tattoo-artist": { 'ai-exposure': 4 },
  "tax-inspector": { 'creativity': 3, 'technical-depth': 6 },
  "tax-lawyer": { 'technical-depth': 7 },
  "tech-reviewer": { 'technical-depth': 5 },
  "technical-architect": { 'leadership': 7 },
  "technical-director": { 'creativity': 6, 'problem-solving': 8 },
  "technical-director-gaming": { 'ai-exposure': 5, 'creativity': 5 },
  "technical-program-manager": { 'problem-solving': 8, 'technical-depth': 5 },
  "technology-director": { 'work-life-balance': 5 },
  "technology-founder": { 'creativity': 8 },
  "technology-strategy-consultant": { 'technical-depth': 6 },
  "technology-transformation-lead": { 'people-interaction': 6 },
  "telco-agile-coach": { 'leadership': 7 },
  "telco-ai-ml-engineer": { 'creativity': 7 },
  "telco-billing-specialist": { 'creativity': 3, 'technical-depth': 5 },
  "telco-catalog-manager": { 'ai-exposure': 5, 'technical-depth': 5 },
  "telco-change-manager": { 'leadership': 5 },
  "telco-compliance-manager": { 'ai-exposure': 4, 'work-life-balance': 5 },
  "telco-cpq-architect": { 'leadership': 6 },
  "telco-customer-success-manager": { 'leadership': 5, 'problem-solving': 5 },
  "telco-customer-support-engineer": { 'technical-depth': 7 },
  "telco-fulfilment-head": { 'technical-depth': 5 },
  "telco-ip-network-engineer": { 'people-interaction': 5 },
  "telco-it-systems-engineer": { 'ai-exposure': 5 },
  "telco-network-engineer": { 'creativity': 4 },
  "telco-noc-engineer": { 'technical-depth': 5, 'work-life-balance': 3 },
  "telco-operations-director": { 'ai-exposure': 5, 'problem-solving': 7 },
  "telco-optical-network-engineer": { 'creativity': 4 },
  "telco-orchestration-architect": { 'technical-depth': 6 },
  "telco-pmo-analyst": { 'problem-solving': 5 },
  "telco-pricing-analyst": { 'people-interaction': 5 },
  "telco-programme-manager": { 'people-interaction': 8 },
  "telco-revenue-assurance-mgr": { 'creativity': 2, 'technical-depth': 5 },
  "telco-safe-rte": { 'technical-depth': 5 },
  "telco-sales-engineer": { 'creativity': 5 },
  "telco-scrum-master": { 'ai-exposure': 4, 'technical-depth': 3 },
  "telco-service-assurance-engineer": { 'people-interaction': 4 },
  "telco-sre": { 'problem-solving': 8 },
  "telco-transformation-lead": { 'creativity': 6 },
  "telco-transmission-engineer": { 'creativity': 4 },
  "telecom-enterprise-architect": { 'creativity': 5 },
  "telecom-practice-lead": { 'creativity': 5 },
  "telecom-strategy-consultant": { 'work-life-balance': 5 },
  "telecommunications-consultant": { 'work-life-balance': 5 },
  "tennis-player": { 'leadership': 2, 'people-interaction': 2, 'work-life-balance': 2 },
  "thoracic-surgeon": { 'ai-exposure': 5, 'technical-depth': 8 },
  "ticketing-manager": { 'leadership': 5 },
  "tiktok-creator": { 'ai-exposure': 6, 'creativity': 6 },
  "title-officer": { 'work-life-balance': 6 },
  "tour-manager": { 'work-life-balance': 2 },
  "trader": { 'ai-exposure': 7, 'work-life-balance': 4 },
  "transcriptionist": { 'problem-solving': 3, 'technical-depth': 3 },
  "transformation-consultant": { 'ai-exposure': 6 },
  "translator": { 'ai-exposure': 5, 'people-interaction': 2 },
  "transplant-surgeon": { 'ai-exposure': 5, 'independence': 7, 'problem-solving': 8, 'technical-depth': 8 },
  "trauma-surgeon": { 'technical-depth': 8 },
  "treasury-director": { 'ai-exposure': 5 },
  "tribunal-judge": { 'creativity': 4, 'problem-solving': 8, 'technical-depth': 7 },
  "truck-driver": { 'ai-exposure': 5 },
  "tugboat-crew": { 'ai-exposure': 2 },
  "tunnel-boring-machine-technician": { 'technical-depth': 7 },
  "ui-designer": { 'creativity': 8, 'problem-solving': 6, 'technical-depth': 4 },
  "umpire": { 'ai-exposure': 4 },
  "undercover-officer": { 'ai-exposure': 4, 'creativity': 5, 'work-life-balance': 2 },
  "urban-planner": { 'creativity': 7 },
  "utility-network-commissioning-technician": { 'people-interaction': 6 },
  "ux-researcher": { 'creativity': 7, 'technical-depth': 5 },
  "vascular-surgeon": { 'ai-exposure': 5, 'creativity': 3, 'technical-depth': 8 },
  "venture-capital-principal": { 'technical-depth': 6 },
  "vessel-maintenance-supervisor": { 'creativity': 3 },
  "veterinary-assistant": { 'ai-exposure': 2 },
  "video-content-producer": { 'problem-solving': 5 },
  "video-editor": { 'people-interaction': 3 },
  "videographer": { 'ai-exposure': 5, 'creativity': 6, 'technical-depth': 5 },
  "vocal-coach": { 'ai-exposure': 3, 'technical-depth': 7 },
  "vocalist": { 'ai-exposure': 3, 'creativity': 8, 'people-interaction': 7 },
  "voice-over-artist": { 'people-interaction': 6 },
  "vp-engineering": { 'leadership': 9 },
  "vp-marketing": { 'leadership': 8 },
  "vp-of-ai": { 'leadership': 8 },
  "vp-product": { 'leadership': 9 },
  "vp-sales": { 'leadership': 9 },
  "vp-technology": { 'leadership': 9 },
  "warehouse-manager": { 'ai-exposure': 6 },
  "warehouse-picker": { 'ai-exposure': 4, 'technical-depth': 3 },
  "warehouse-worker": { 'ai-exposure': 4, 'people-interaction': 5, 'technical-depth': 3 },
  "wastewater-systems-technician": { 'problem-solving': 6, 'technical-depth': 7 },
  "water-treatment-plant-technician": { 'technical-depth': 7 },
  "wealth-manager": { 'leadership': 6 },
  "weapons-specialist": { 'ai-exposure': 5 },
  "wedding-videographer": { 'creativity': 6 },
  "welder": { 'ai-exposure': 2, 'creativity': 2 },
  "whitewater-rafting-guide": { 'ai-exposure': 2, 'independence': 4 },
  "wildland-firefighter": { 'ai-exposure': 2, 'creativity': 3, 'work-life-balance': 3 },
  "wildlife-crime-investigator": { 'people-interaction': 4 },
  "wildlife-photographer": { 'ai-exposure': 3, 'independence': 8, 'people-interaction': 2 },
  "wind-commissioning-technician": { 'creativity': 3, 'technical-depth': 7 },
  "wind-service-supervisor": { 'creativity': 3 },
  "windsurfing-instructor": { 'ai-exposure': 3 },
  "wingsuit-pilot": { 'creativity': 6, 'independence': 9, 'leadership': 2, 'people-interaction': 2, 'work-life-balance': 2 },
  "workforce-strategy-director": { 'creativity': 5, 'independence': 6 },
  "wrestler": { 'ai-exposure': 3 },
  "yoga-instructor": { 'ai-exposure': 2 },
  "youth-worker": { 'work-life-balance': 4 },
  "youtube-video-editor": { 'problem-solving': 5 },
};
