/**
 * Career-employer REALISM overrides — AI-focused additions (2026-06-15).
 * Employer lists for the ~58 AI-focused careers added alongside the Career
 * Radar "AI-Focused Roles" filter rebuild. Norway-first, real.
 */
import type { Employer } from './career-employers';

export const REALISM_EMPLOYERS_AI: Record<string, Employer[]> = {
  // ─── Robotics roles (2026-06-18) — Norway-first, real employers. ───
  "mechatronics-engineer": [
    { name: "Kongsberg Gruppen", industry: "Defence, maritime & automation", size: "large" },
    { name: "ABB", industry: "Industrial automation & robotics", size: "large" },
    { name: "AutoStore", industry: "Warehouse robotics", size: "large" },
    { name: "Aker Solutions", industry: "Energy engineering", size: "large" },
    { name: "Equinor", industry: "Energy", size: "large" },
    { name: "Universal Robots", industry: "Collaborative robots", size: "medium" },
  ],
  "controls-engineer": [
    { name: "Kongsberg Maritime", industry: "Maritime automation", size: "large" },
    { name: "ABB", industry: "Industrial automation", size: "large" },
    { name: "Equinor", industry: "Energy", size: "large" },
    { name: "Aker BP", industry: "Energy", size: "large" },
    { name: "Cognite", industry: "Industrial software", size: "large" },
    { name: "AutoStore", industry: "Warehouse robotics", size: "large" },
  ],
  "ros-developer": [
    { name: "1X Technologies", industry: "Humanoid robotics", size: "medium" },
    { name: "AutoStore", industry: "Warehouse robotics", size: "large" },
    { name: "Saga Robotics", industry: "Agricultural robotics", size: "small" },
    { name: "Zivid", industry: "3D machine vision", size: "small" },
    { name: "Kongsberg Maritime", industry: "Autonomous vessels", size: "large" },
    { name: "Sevendof", industry: "Drone systems", size: "small" },
  ],
  "robotics-research-scientist": [
    { name: "SINTEF", industry: "Research institute", size: "large" },
    { name: "NTNU", industry: "University research", size: "large" },
    { name: "1X Technologies", industry: "Humanoid robotics", size: "medium" },
    { name: "Kongsberg Gruppen", industry: "Defence & robotics R&D", size: "large" },
    { name: "University of Oslo", industry: "University research", size: "large" },
    { name: "Equinor Research", industry: "Energy R&D", size: "large" },
  ],
  "robotics-professor": [
    { name: "NTNU", industry: "University", size: "large" },
    { name: "University of Oslo", industry: "University", size: "large" },
    { name: "UiT The Arctic University", industry: "University", size: "large" },
    { name: "OsloMet", industry: "University", size: "large" },
    { name: "NMBU", industry: "University", size: "medium" },
    { name: "SINTEF", industry: "Research institute", size: "large" },
  ],
  "industrial-robotics-programmer": [
    { name: "AutoStore", industry: "Warehouse robotics", size: "large" },
    { name: "ABB", industry: "Industrial robotics", size: "large" },
    { name: "Kongsberg Automotive", industry: "Automotive manufacturing", size: "large" },
    { name: "Benteler", industry: "Manufacturing", size: "large" },
    { name: "Nammo", industry: "Defence manufacturing", size: "large" },
    { name: "Hydro", industry: "Aluminium manufacturing", size: "large" },
  ],
  "field-applications-engineer": [
    { name: "Nordic Semiconductor", industry: "Semiconductors", size: "large" },
    { name: "ABB", industry: "Automation & electrification", size: "large" },
    { name: "Kongsberg Gruppen", industry: "Defence & maritime", size: "large" },
    { name: "Schneider Electric", industry: "Energy management", size: "large" },
    { name: "Siemens", industry: "Industrial technology", size: "large" },
    { name: "Texas Instruments", industry: "Semiconductors", size: "large" },
  ],
  "robotics-entrepreneur": [
    { name: "Your own startup", industry: "Founder", size: "varies" },
    { name: "StartupLab Oslo", industry: "Deep-tech incubator", size: "small" },
    { name: "Antler", industry: "Startup investor", size: "medium" },
    { name: "Katapult", industry: "Impact accelerator", size: "small" },
    { name: "Construct Venture", industry: "Robotics/construction VC", size: "small" },
    { name: "Varies / many employers", industry: "Deep-tech startups", size: "varies" },
  ],
  "simulation-engineer": [
    { name: "DNV", industry: "Risk & assurance", size: "large" },
    { name: "Kongsberg Gruppen", industry: "Defence & maritime", size: "large" },
    { name: "Equinor", industry: "Energy", size: "large" },
    { name: "Cognite", industry: "Industrial software", size: "large" },
    { name: "SINTEF", industry: "Research institute", size: "large" },
    { name: "Aker Solutions", industry: "Energy engineering", size: "large" },
  ],
  "digital-twin-engineer": [
    { name: "Cognite", industry: "Industrial software", size: "large" },
    { name: "DNV", industry: "Risk & assurance", size: "large" },
    { name: "Kongsberg Digital", industry: "Industrial digital twins", size: "large" },
    { name: "Equinor", industry: "Energy", size: "large" },
    { name: "Aker BP", industry: "Energy", size: "large" },
    { name: "Siemens", industry: "Industrial technology", size: "large" },
  ],
  "humanoid-robotics-engineer": [
    { name: "1X Technologies", industry: "Humanoid robotics (Norwegian)", size: "medium" },
    { name: "Kongsberg Gruppen", industry: "Robotics R&D", size: "large" },
    { name: "NTNU", industry: "University research", size: "large" },
    { name: "SINTEF", industry: "Research institute", size: "large" },
    { name: "Tesla (Optimus)", industry: "Humanoid robotics", size: "large" },
    { name: "Boston Dynamics", industry: "Robotics", size: "large" },
  ],
  "agricultural-robotics-specialist": [
    { name: "Saga Robotics (Thorvald)", industry: "Agricultural robotics (Norwegian)", size: "small" },
    { name: "Kverneland Group", industry: "Agricultural machinery", size: "large" },
    { name: "Yara", industry: "Agriculture & fertiliser", size: "large" },
    { name: "NMBU", industry: "Agritech research", size: "medium" },
    { name: "NIBIO", industry: "Bioeconomy research", size: "medium" },
    { name: "Sevendof", industry: "Drone systems", size: "small" },
  ],
  "warehouse-automation-engineer": [
    { name: "AutoStore", industry: "Warehouse robotics (Norwegian)", size: "large" },
    { name: "Element Logic", industry: "Warehouse automation", size: "large" },
    { name: "Swisslog", industry: "Warehouse automation", size: "large" },
    { name: "Posten Bring", industry: "Logistics", size: "large" },
    { name: "ASKO", industry: "Wholesale & logistics", size: "large" },
    { name: "Dematic", industry: "Intralogistics", size: "large" },
  ],
  "service-robotics-developer": [
    { name: "1X Technologies", industry: "Service & humanoid robotics", size: "medium" },
    { name: "AutoStore", industry: "Robotics", size: "large" },
    { name: "Zivid", industry: "3D machine vision", size: "small" },
    { name: "Kongsberg Gruppen", industry: "Robotics & autonomy", size: "large" },
    { name: "Probot", industry: "Service robotics", size: "small" },
    { name: "Varies / many employers", industry: "Robotics", size: "varies" },
  ],
  "swarm-robotics-researcher": [
    { name: "SINTEF", industry: "Research institute", size: "large" },
    { name: "NTNU", industry: "University research", size: "large" },
    { name: "University of Oslo", industry: "University research", size: "large" },
    { name: "Kongsberg Gruppen", industry: "Defence & autonomy R&D", size: "large" },
    { name: "Nordic Unmanned", industry: "Drone systems", size: "medium" },
    { name: "FFI (Norwegian Defence Research)", industry: "Defence research", size: "large" },
  ],
  "ai-adoption-consultant": [
    { name: "Bekk", industry: "Technology consulting", size: "large" },
    { name: "Sopra Steria", industry: "Technology consulting", size: "large" },
    { name: "Capgemini", industry: "Technology consulting", size: "large" },
    { name: "Computas", industry: "AI consulting", size: "medium" },
    { name: "Knowit", industry: "Technology consulting", size: "large" },
    { name: "Varies / many employers", industry: "Consulting", size: "varies" },
  ],
  "ai-agent-architect": [
    { name: "Cognite", industry: "Industrial software", size: "large" },
    { name: "Computas", industry: "AI consulting", size: "medium" },
    { name: "Bekk", industry: "Technology consulting", size: "large" },
    { name: "Capgemini", industry: "Technology consulting", size: "large" },
    { name: "Sopra Steria", industry: "Technology consulting", size: "large" },
    { name: "Visma", industry: "Software", size: "large" },
  ],
  "ai-agent-developer": [
    { name: "Cognite", industry: "Industrial software", size: "large" },
    { name: "Computas", industry: "AI consulting", size: "medium" },
    { name: "Bekk", industry: "Technology consulting", size: "large" },
    { name: "Iterate", industry: "Software studio", size: "medium" },
    { name: "Schibsted", industry: "Media & technology", size: "large" },
    { name: "Visma", industry: "Software", size: "large" },
  ],
  "ai-agent-engineer": [
    { name: "Cognite", industry: "Industrial AI software", size: "large" },
    { name: "Iterate", industry: "Product & technology studio", size: "medium" },
    { name: "Bekk", industry: "Consulting & technology", size: "medium" },
    { name: "Schibsted", industry: "Media & marketplaces", size: "large" },
    { name: "Computas", industry: "AI & software consulting", size: "medium" },
    { name: "Varies / many employers", industry: "Multiple sectors", size: "varies" },
  ],
  "ai-agent-operations-specialist": [
    { name: "Cognite", industry: "Industrial software", size: "large" },
    { name: "Computas", industry: "AI consulting", size: "medium" },
    { name: "Visma", industry: "Software", size: "large" },
    { name: "Schibsted", industry: "Media & technology", size: "large" },
    { name: "Bekk", industry: "Technology consulting", size: "large" },
    { name: "Iterate", industry: "Software studio", size: "medium" },
  ],
  "ai-agent-product-manager": [
    { name: "Schibsted", industry: "Media & technology", size: "large" },
    { name: "Cognite", industry: "Industrial software", size: "large" },
    { name: "Visma", industry: "Software", size: "large" },
    { name: "DNB", industry: "Banking & finance", size: "large" },
    { name: "Telenor", industry: "Telecommunications", size: "large" },
    { name: "Iterate", industry: "Software studio", size: "medium" },
  ],
  "ai-auditor": [
    { name: "Sopra Steria", industry: "Technology consulting", size: "large" },
    { name: "Capgemini", industry: "Technology consulting", size: "large" },
    { name: "DNB", industry: "Banking & finance", size: "large" },
    { name: "Knowit", industry: "Technology consulting", size: "large" },
    { name: "Computas", industry: "AI consulting", size: "medium" },
    { name: "Varies / many employers", industry: "Audit & consulting", size: "varies" },
  ],
  "ai-automation-engineer": [
    { name: "Visma", industry: "Business software", size: "large" },
    { name: "Sopra Steria", industry: "Consulting & IT services", size: "large" },
    { name: "Computas", industry: "AI & software consulting", size: "medium" },
    { name: "Knowit", industry: "Consulting & technology", size: "large" },
    { name: "DNB", industry: "Banking & finance", size: "large" },
    { name: "Varies / many employers", industry: "Multiple sectors", size: "varies" },
  ],
  "ai-business-analyst": [
    { name: "DNB", industry: "Banking & finance", size: "large" },
    { name: "Visma", industry: "Business software", size: "large" },
    { name: "Sopra Steria", industry: "Consulting & IT services", size: "large" },
    { name: "Telenor", industry: "Telecommunications", size: "large" },
    { name: "Knowit", industry: "Consulting & technology", size: "large" },
    { name: "Varies / many employers", industry: "Multiple sectors", size: "varies" },
  ],
  "ai-cloud-architect": [
    { name: "Cognite", industry: "Industrial software", size: "large" },
    { name: "Equinor", industry: "Energy", size: "large" },
    { name: "Telenor", industry: "Telecommunications", size: "large" },
    { name: "Bekk", industry: "Technology consulting", size: "large" },
    { name: "Capgemini", industry: "Technology consulting", size: "large" },
    { name: "Sopra Steria", industry: "Technology consulting", size: "large" },
  ],
  "ai-compliance-officer": [
    { name: "DNB", industry: "Banking & finance", size: "large" },
    { name: "Telenor", industry: "Telecommunications", size: "large" },
    { name: "Equinor", industry: "Energy", size: "large" },
    { name: "Visma", industry: "Software", size: "large" },
    { name: "Sopra Steria", industry: "Technology consulting", size: "large" },
    { name: "Varies / many employers", industry: "Public & private sector", size: "varies" },
  ],
  "ai-customer-success-manager": [
    { name: "Visma", industry: "Software", size: "large" },
    { name: "Cognite", industry: "Industrial software", size: "large" },
    { name: "Schibsted", industry: "Media & technology", size: "large" },
    { name: "Telenor", industry: "Telecommunications", size: "large" },
    { name: "Iterate", industry: "Software studio", size: "medium" },
    { name: "Varies / many employers", industry: "Software & SaaS", size: "varies" },
  ],
  "ai-data-center-engineer": [
    { name: "Green Mountain", industry: "Data centres", size: "large" },
    { name: "Bulk Infrastructure", industry: "Data centres", size: "large" },
    { name: "Equinor", industry: "Energy", size: "large" },
    { name: "Telenor", industry: "Telecommunications", size: "large" },
    { name: "Cognite", industry: "Industrial software", size: "large" },
    { name: "Varies / many employers", industry: "Data centres", size: "varies" },
  ],
  "ai-devops-engineer": [
    { name: "Cognite", industry: "Industrial AI software", size: "large" },
    { name: "Schibsted", industry: "Media & marketplaces", size: "large" },
    { name: "Telenor", industry: "Telecommunications", size: "large" },
    { name: "Visma", industry: "Business software", size: "large" },
    { name: "DNB", industry: "Banking & finance", size: "large" },
    { name: "Bekk", industry: "Consulting & technology", size: "medium" },
  ],
  "ai-enterprise-architect": [
    { name: "Cognite", industry: "Industrial AI software", size: "large" },
    { name: "DNB", industry: "Banking & finance", size: "large" },
    { name: "Equinor", industry: "Energy", size: "large" },
    { name: "Sopra Steria", industry: "Consulting & IT services", size: "large" },
    { name: "Capgemini", industry: "Consulting & technology", size: "large" },
    { name: "Visma", industry: "Business software", size: "large" },
  ],
  "ai-governance-specialist": [
    { name: "DNB", industry: "Banking & finance", size: "large" },
    { name: "Telenor", industry: "Telecommunications", size: "large" },
    { name: "Equinor", industry: "Energy", size: "large" },
    { name: "Sopra Steria", industry: "Technology consulting", size: "large" },
    { name: "Bekk", industry: "Technology consulting", size: "large" },
    { name: "Varies / many employers", industry: "Public & private sector", size: "varies" },
  ],
  "ai-innovation-lead": [
    { name: "Iterate", industry: "Product & technology studio", size: "medium" },
    { name: "Schibsted", industry: "Media & marketplaces", size: "large" },
    { name: "Cognite", industry: "Industrial AI software", size: "large" },
    { name: "Telenor", industry: "Telecommunications", size: "large" },
    { name: "Bekk", industry: "Consulting & technology", size: "medium" },
    { name: "Varies / many employers", industry: "Multiple sectors", size: "varies" },
  ],
  "ai-integration-architect": [
    { name: "Computas", industry: "AI & software consulting", size: "medium" },
    { name: "Sopra Steria", industry: "Consulting & IT services", size: "large" },
    { name: "Capgemini", industry: "Consulting & technology", size: "large" },
    { name: "Knowit", industry: "Consulting & technology", size: "large" },
    { name: "Visma", industry: "Business software", size: "large" },
    { name: "Varies / many employers", industry: "Multiple sectors", size: "varies" },
  ],
  "ai-knowledge-engineer": [
    { name: "Cognite", industry: "Industrial AI software", size: "large" },
    { name: "Computas", industry: "AI & software consulting", size: "medium" },
    { name: "Equinor", industry: "Energy", size: "large" },
    { name: "Sopra Steria", industry: "Consulting & IT services", size: "large" },
    { name: "DNB", industry: "Banking & finance", size: "large" },
    { name: "Varies / many employers", industry: "Multiple sectors", size: "varies" },
  ],
  "ai-orchestration-engineer": [
    { name: "Cognite", industry: "Industrial software", size: "large" },
    { name: "Schibsted", industry: "Media & technology", size: "large" },
    { name: "Computas", industry: "AI consulting", size: "medium" },
    { name: "Bekk", industry: "Technology consulting", size: "large" },
    { name: "Visma", industry: "Software", size: "large" },
    { name: "Iterate", industry: "Software studio", size: "medium" },
  ],
  "ai-partner-manager": [
    { name: "Cognite", industry: "Industrial software", size: "large" },
    { name: "Visma", industry: "Software", size: "large" },
    { name: "Telenor", industry: "Telecommunications", size: "large" },
    { name: "Schibsted", industry: "Media & technology", size: "large" },
    { name: "Capgemini", industry: "Technology consulting", size: "large" },
    { name: "Varies / many employers", industry: "Software & SaaS", size: "varies" },
  ],
  "ai-platform-architect": [
    { name: "Cognite", industry: "Industrial AI software", size: "large" },
    { name: "Schibsted", industry: "Media & marketplaces", size: "large" },
    { name: "Telenor", industry: "Telecommunications", size: "large" },
    { name: "Visma", industry: "Business software", size: "large" },
    { name: "Bekk", industry: "Consulting & technology", size: "medium" },
    { name: "DNB", industry: "Banking & finance", size: "large" },
  ],
  "ai-platform-operations-engineer": [
    { name: "Cognite", industry: "Industrial software", size: "large" },
    { name: "Visma", industry: "Software", size: "large" },
    { name: "Schibsted", industry: "Media & technology", size: "large" },
    { name: "Telenor", industry: "Telecommunications", size: "large" },
    { name: "Bekk", industry: "Technology consulting", size: "large" },
    { name: "Iterate", industry: "Software studio", size: "medium" },
  ],
  "ai-practice-lead": [
    { name: "Bekk", industry: "Consulting & technology", size: "medium" },
    { name: "Computas", industry: "AI & software consulting", size: "medium" },
    { name: "Knowit", industry: "Consulting & technology", size: "large" },
    { name: "Sopra Steria", industry: "Consulting & IT services", size: "large" },
    { name: "Capgemini", industry: "Consulting & technology", size: "large" },
    { name: "Iterate", industry: "Product & technology studio", size: "medium" },
  ],
  "ai-program-manager": [
    { name: "Telenor", industry: "Telecommunications", size: "large" },
    { name: "DNB", industry: "Banking & finance", size: "large" },
    { name: "Cognite", industry: "Industrial AI software", size: "large" },
    { name: "Sopra Steria", industry: "Consulting & IT services", size: "large" },
    { name: "Capgemini", industry: "Consulting & technology", size: "large" },
    { name: "Equinor", industry: "Energy", size: "large" },
  ],
  "ai-project-manager": [
    { name: "Sopra Steria", industry: "Consulting & IT services", size: "large" },
    { name: "Capgemini", industry: "Consulting & technology", size: "large" },
    { name: "Knowit", industry: "Consulting & technology", size: "large" },
    { name: "Visma", industry: "Business software", size: "large" },
    { name: "Telenor", industry: "Telecommunications", size: "large" },
    { name: "Varies / many employers", industry: "Multiple sectors", size: "varies" },
  ],
  "ai-risk-manager": [
    { name: "DNB", industry: "Banking & finance", size: "large" },
    { name: "Equinor", industry: "Energy", size: "large" },
    { name: "Telenor", industry: "Telecommunications", size: "large" },
    { name: "Sopra Steria", industry: "Technology consulting", size: "large" },
    { name: "Capgemini", industry: "Technology consulting", size: "large" },
    { name: "Varies / many employers", industry: "Finance & enterprise", size: "varies" },
  ],
  "ai-sales-engineer": [
    { name: "Cognite", industry: "Industrial software", size: "large" },
    { name: "Visma", industry: "Software", size: "large" },
    { name: "Schibsted", industry: "Media & technology", size: "large" },
    { name: "Telenor", industry: "Telecommunications", size: "large" },
    { name: "Computas", industry: "AI consulting", size: "medium" },
    { name: "Varies / many employers", industry: "Software & SaaS", size: "varies" },
  ],
  "ai-security-architect": [
    { name: "DNB", industry: "Banking & finance", size: "large" },
    { name: "Telenor", industry: "Telecommunications", size: "large" },
    { name: "Kongsberg Gruppen", industry: "Defence & maritime technology", size: "large" },
    { name: "Sopra Steria", industry: "Consulting & IT services", size: "large" },
    { name: "Equinor", industry: "Energy", size: "large" },
    { name: "Capgemini", industry: "Consulting & technology", size: "large" },
  ],
  "ai-site-reliability-engineer": [
    { name: "Cognite", industry: "Industrial software", size: "large" },
    { name: "Schibsted", industry: "Media & technology", size: "large" },
    { name: "Visma", industry: "Software", size: "large" },
    { name: "Telenor", industry: "Telecommunications", size: "large" },
    { name: "DNB", industry: "Banking & finance", size: "large" },
    { name: "Bekk", industry: "Technology consulting", size: "large" },
  ],
  "ai-solutions-consultant": [
    { name: "Capgemini", industry: "Consulting & technology", size: "large" },
    { name: "Sopra Steria", industry: "Consulting & IT services", size: "large" },
    { name: "Computas", industry: "AI & software consulting", size: "medium" },
    { name: "Knowit", industry: "Consulting & technology", size: "large" },
    { name: "Bekk", industry: "Consulting & technology", size: "medium" },
    { name: "Cognite", industry: "Industrial AI software", size: "large" },
  ],
  "ai-solutions-engineer": [
    { name: "Cognite", industry: "Industrial software", size: "large" },
    { name: "Computas", industry: "AI consulting", size: "medium" },
    { name: "Visma", industry: "Software", size: "large" },
    { name: "Bekk", industry: "Technology consulting", size: "large" },
    { name: "Iterate", industry: "Software studio", size: "medium" },
    { name: "Knowit", industry: "Technology consulting", size: "large" },
  ],
  "ai-strategy-director": [
    { name: "Capgemini", industry: "Consulting & technology", size: "large" },
    { name: "Sopra Steria", industry: "Consulting & IT services", size: "large" },
    { name: "DNB", industry: "Banking & finance", size: "large" },
    { name: "Telenor", industry: "Telecommunications", size: "large" },
    { name: "Equinor", industry: "Energy", size: "large" },
    { name: "Knowit", industry: "Consulting & technology", size: "large" },
  ],
  "ai-systems-administrator": [
    { name: "Cognite", industry: "Industrial software", size: "large" },
    { name: "NTNU", industry: "Research & education", size: "large" },
    { name: "Visma", industry: "Software", size: "large" },
    { name: "Telenor", industry: "Telecommunications", size: "large" },
    { name: "Sopra Steria", industry: "Technology consulting", size: "large" },
    { name: "Varies / many employers", industry: "IT operations", size: "varies" },
  ],
  "ai-technical-account-manager": [
    { name: "Cognite", industry: "Industrial software", size: "large" },
    { name: "Visma", industry: "Software", size: "large" },
    { name: "Telenor", industry: "Telecommunications", size: "large" },
    { name: "Schibsted", industry: "Media & technology", size: "large" },
    { name: "Computas", industry: "AI consulting", size: "medium" },
    { name: "Varies / many employers", industry: "Software & SaaS", size: "varies" },
  ],
  "ai-transformation-consultant": [
    { name: "Bekk", industry: "Technology consulting", size: "large" },
    { name: "Sopra Steria", industry: "Technology consulting", size: "large" },
    { name: "Capgemini", industry: "Technology consulting", size: "large" },
    { name: "Knowit", industry: "Technology consulting", size: "large" },
    { name: "Computas", industry: "AI consulting", size: "medium" },
    { name: "DNB", industry: "Banking & finance", size: "large" },
  ],
  "ai-transformation-director": [
    { name: "Sopra Steria", industry: "Consulting & IT services", size: "large" },
    { name: "Capgemini", industry: "Consulting & technology", size: "large" },
    { name: "Bekk", industry: "Consulting & technology", size: "medium" },
    { name: "Visma", industry: "Business software", size: "large" },
    { name: "Telenor", industry: "Telecommunications", size: "large" },
    { name: "Varies / many employers", industry: "Multiple sectors", size: "varies" },
  ],
  "ai-workflow-engineer": [
    { name: "Visma", industry: "Business software", size: "large" },
    { name: "Cognite", industry: "Industrial AI software", size: "large" },
    { name: "Knowit", industry: "Consulting & technology", size: "large" },
    { name: "Sopra Steria", industry: "Consulting & IT services", size: "large" },
    { name: "Computas", industry: "AI & software consulting", size: "medium" },
    { name: "Telenor", industry: "Telecommunications", size: "large" },
  ],
  "analytics-engineer": [
    { name: "Schibsted", industry: "Media & marketplaces", size: "large" },
    { name: "DNB", industry: "Banking & finance", size: "large" },
    { name: "Visma", industry: "Business software", size: "large" },
    { name: "Telenor", industry: "Telecommunications", size: "large" },
    { name: "Cognite", industry: "Industrial AI software", size: "large" },
    { name: "Varies / many employers", industry: "Multiple sectors", size: "varies" },
  ],
  "autonomous-vehicle-engineer": [
    { name: "Kongsberg Maritime", industry: "Autonomous vessels", size: "large" },
    { name: "Kongsberg", industry: "Robotics & defence", size: "large" },
    { name: "Applied Autonomy", industry: "Autonomous mobility", size: "small" },
    { name: "NTNU", industry: "Research & education", size: "large" },
    { name: "SINTEF", industry: "Research", size: "large" },
    { name: "Varies / many employers", industry: "Autonomy", size: "varies" },
  ],
  "autonomous-workflow-designer": [
    { name: "Visma", industry: "Software", size: "large" },
    { name: "Computas", industry: "AI consulting", size: "medium" },
    { name: "Bekk", industry: "Technology consulting", size: "large" },
    { name: "Sopra Steria", industry: "Technology consulting", size: "large" },
    { name: "Iterate", industry: "Software studio", size: "medium" },
    { name: "Varies / many employers", industry: "Software & consulting", size: "varies" },
  ],
  "computer-vision-researcher": [
    { name: "SimulaMet", industry: "Research institute", size: "medium" },
    { name: "NTNU", industry: "University & research", size: "large" },
    { name: "Kongsberg Gruppen", industry: "Defence & maritime technology", size: "large" },
    { name: "Cognite", industry: "Industrial AI software", size: "large" },
    { name: "Equinor", industry: "Energy", size: "large" },
    { name: "NORA (Norwegian AI Research Consortium)", industry: "AI research network", size: "medium" },
  ],
  "deep-learning-engineer": [
    { name: "Cognite", industry: "Industrial AI software", size: "large" },
    { name: "Kongsberg Gruppen", industry: "Defence & maritime technology", size: "large" },
    { name: "Schibsted", industry: "Media & marketplaces", size: "large" },
    { name: "SimulaMet", industry: "Research institute", size: "medium" },
    { name: "Equinor", industry: "Energy", size: "large" },
    { name: "Telenor", industry: "Telecommunications", size: "large" },
  ],
  "director-of-ai": [
    { name: "DNB", industry: "Banking & finance", size: "large" },
    { name: "Telenor", industry: "Telecommunications", size: "large" },
    { name: "Cognite", industry: "Industrial AI software", size: "large" },
    { name: "Visma", industry: "Business software", size: "large" },
    { name: "Equinor", industry: "Energy", size: "large" },
    { name: "Capgemini", industry: "Consulting & technology", size: "large" },
  ],
  "drone-systems-engineer": [
    { name: "Kongsberg", industry: "Robotics & defence", size: "large" },
    { name: "Kongsberg Maritime", industry: "Autonomous systems", size: "large" },
    { name: "Nordic Unmanned", industry: "Drone services", size: "medium" },
    { name: "NTNU", industry: "Research & education", size: "large" },
    { name: "Equinor", industry: "Energy", size: "large" },
    { name: "Varies / many employers", industry: "Drones & autonomy", size: "varies" },
  ],
  "feature-engineering-specialist": [
    { name: "Cognite", industry: "Industrial AI software", size: "large" },
    { name: "DNB", industry: "Banking & finance", size: "large" },
    { name: "Schibsted", industry: "Media & marketplaces", size: "large" },
    { name: "Telenor", industry: "Telecommunications", size: "large" },
    { name: "Visma", industry: "Business software", size: "large" },
    { name: "Equinor", industry: "Energy", size: "large" },
  ],
  "generative-ai-architect": [
    { name: "Cognite", industry: "Industrial AI software", size: "large" },
    { name: "Schibsted", industry: "Media & marketplaces", size: "large" },
    { name: "Bekk", industry: "Consulting & technology", size: "medium" },
    { name: "Iterate", industry: "Product & technology studio", size: "medium" },
    { name: "Computas", industry: "AI & software consulting", size: "medium" },
    { name: "Capgemini", industry: "Consulting & technology", size: "large" },
  ],
  "generative-ai-research-scientist": [
    { name: "SimulaMet", industry: "Research institute", size: "medium" },
    { name: "NTNU", industry: "University & research", size: "large" },
    { name: "NORA (Norwegian AI Research Consortium)", industry: "AI research network", size: "medium" },
    { name: "Schibsted", industry: "Media & marketplaces", size: "large" },
    { name: "Cognite", industry: "Industrial AI software", size: "large" },
    { name: "Telenor Research", industry: "Telecommunications research", size: "large" },
  ],
  "gpu-infrastructure-engineer": [
    { name: "Cognite", industry: "Industrial software", size: "large" },
    { name: "Equinor", industry: "Energy", size: "large" },
    { name: "NTNU", industry: "Research & education", size: "large" },
    { name: "SimulaMet", industry: "Research", size: "medium" },
    { name: "Telenor", industry: "Telecommunications", size: "large" },
    { name: "Varies / many employers", industry: "Cloud & data centres", size: "varies" },
  ],
  "head-of-ai": [
    { name: "Cognite", industry: "Industrial AI software", size: "large" },
    { name: "DNB", industry: "Banking & finance", size: "large" },
    { name: "Telenor", industry: "Telecommunications", size: "large" },
    { name: "Schibsted", industry: "Media & marketplaces", size: "large" },
    { name: "Equinor", industry: "Energy", size: "large" },
    { name: "Varies / many employers", industry: "Multiple sectors", size: "varies" },
  ],
  "human-robot-interaction-specialist": [
    { name: "Halodi Robotics", industry: "Humanoid robotics", size: "medium" },
    { name: "AutoStore", industry: "Warehouse robotics", size: "large" },
    { name: "NTNU", industry: "Research & education", size: "large" },
    { name: "SINTEF", industry: "Research", size: "large" },
    { name: "Kongsberg", industry: "Robotics & defence", size: "large" },
    { name: "Varies / many employers", industry: "Robotics & research", size: "varies" },
  ],
  "llm-engineer": [
    { name: "Schibsted", industry: "Media & marketplaces", size: "large" },
    { name: "Cognite", industry: "Industrial AI software", size: "large" },
    { name: "DNB", industry: "Banking & finance", size: "large" },
    { name: "Iterate", industry: "Product & technology studio", size: "medium" },
    { name: "Bekk", industry: "Consulting & technology", size: "medium" },
    { name: "Telenor", industry: "Telecommunications", size: "large" },
  ],
  "multi-agent-systems-engineer": [
    { name: "Cognite", industry: "Industrial software", size: "large" },
    { name: "Computas", industry: "AI consulting", size: "medium" },
    { name: "SimulaMet", industry: "Research", size: "medium" },
    { name: "NTNU", industry: "Research & education", size: "large" },
    { name: "Bekk", industry: "Technology consulting", size: "large" },
    { name: "Iterate", industry: "Software studio", size: "medium" },
  ],
  "nlp-research-scientist": [
    { name: "NTNU", industry: "University & research", size: "large" },
    { name: "SimulaMet", industry: "Research institute", size: "medium" },
    { name: "Schibsted", industry: "Media & marketplaces", size: "large" },
    { name: "NORA (Norwegian AI Research Consortium)", industry: "AI research network", size: "medium" },
    { name: "Telenor Research", industry: "Telecommunications research", size: "large" },
    { name: "Cognite", industry: "Industrial AI software", size: "large" },
  ],
  "reinforcement-learning-researcher": [
    { name: "NTNU", industry: "University & research", size: "large" },
    { name: "SimulaMet", industry: "Research institute", size: "medium" },
    { name: "Kongsberg Gruppen", industry: "Defence & maritime technology", size: "large" },
    { name: "Equinor", industry: "Energy", size: "large" },
    { name: "NORA (Norwegian AI Research Consortium)", industry: "AI research network", size: "medium" },
    { name: "Cognite", industry: "Industrial AI software", size: "large" },
  ],
  "responsible-ai-lead": [
    { name: "Telenor", industry: "Telecommunications", size: "large" },
    { name: "DNB", industry: "Banking & finance", size: "large" },
    { name: "Schibsted", industry: "Media & technology", size: "large" },
    { name: "Equinor", industry: "Energy", size: "large" },
    { name: "NTNU", industry: "Research & education", size: "large" },
    { name: "SimulaMet", industry: "Research", size: "medium" },
  ],
  "robotics-software-engineer": [
    { name: "AutoStore", industry: "Warehouse robotics", size: "large" },
    { name: "Zivid", industry: "3D machine vision", size: "medium" },
    { name: "Halodi Robotics", industry: "Humanoid robotics", size: "medium" },
    { name: "Kongsberg", industry: "Robotics & defence", size: "large" },
    { name: "NTNU", industry: "Research & education", size: "large" },
    { name: "Varies / many employers", industry: "Robotics", size: "varies" },
  ],
  "vp-of-ai": [
    { name: "Schibsted", industry: "Media & marketplaces", size: "large" },
    { name: "Telenor", industry: "Telecommunications", size: "large" },
    { name: "DNB", industry: "Banking & finance", size: "large" },
    { name: "Cognite", industry: "Industrial AI software", size: "large" },
    { name: "Kongsberg Gruppen", industry: "Defence & maritime technology", size: "large" },
    { name: "Varies / many employers", industry: "Multiple sectors", size: "varies" },
  ],
};
