/**
 * Career-employer REALISM overrides — fast-growing careers (2026-06-19).
 * Norway-first, real employers for the careers added alongside the Career
 * Radar "Fast-Growing" preset broadening. Wired into getTopEmployers().
 */
import type { Employer } from "./career-employers";

export const REALISM_EMPLOYERS_FASTGROW: Record<string, Employer[]> = {
  "cloud-network-architect": [
    { name: "Telenor", industry: "Telecommunications", size: "large" },
    { name: "Telia", industry: "Telecommunications", size: "large" },
    { name: "Tietoevry", industry: "IT services", size: "large" },
    { name: "Amazon Web Services", industry: "Cloud computing", size: "large" },
    { name: "Microsoft", industry: "Cloud computing", size: "large" },
    { name: "Cisco", industry: "Networking technology", size: "large" },
  ],
  "telco-solutions-architect": [
    { name: "Telenor", industry: "Telecommunications", size: "large" },
    { name: "Telia", industry: "Telecommunications", size: "large" },
    { name: "Ericsson", industry: "Telecom equipment", size: "large" },
    { name: "Nokia", industry: "Telecom equipment", size: "large" },
    { name: "Accenture", industry: "Consulting", size: "large" },
    { name: "Capgemini", industry: "Consulting", size: "large" },
  ],
  "sd-wan-architect": [
    { name: "Telenor", industry: "Telecommunications", size: "large" },
    { name: "Telia", industry: "Telecommunications", size: "large" },
    { name: "Cisco", industry: "Networking technology", size: "large" },
    { name: "Tietoevry", industry: "IT services", size: "large" },
    { name: "Accenture", industry: "Consulting", size: "large" },
    { name: "Tata Consultancy Services", industry: "IT services", size: "large" },
  ],
  "network-security-architect": [
    { name: "Telenor", industry: "Telecommunications", size: "large" },
    { name: "Telia", industry: "Telecommunications", size: "large" },
    { name: "Cisco", industry: "Networking technology", size: "large" },
    { name: "Tietoevry", industry: "IT services", size: "large" },
    { name: "Accenture", industry: "Consulting", size: "large" },
    { name: "Capgemini", industry: "Consulting", size: "large" },
  ],
  "private-5g-architect": [
    { name: "Telenor", industry: "Telecommunications", size: "large" },
    { name: "Telia", industry: "Telecommunications", size: "large" },
    { name: "Ericsson", industry: "Telecom equipment", size: "large" },
    { name: "Nokia", industry: "Telecom equipment", size: "large" },
    { name: "Ice", industry: "Telecommunications", size: "medium" },
    { name: "Cisco", industry: "Networking technology", size: "large" },
  ],
  "servicenow-telecom-consultant": [
    { name: "Telenor", industry: "Telecommunications", size: "large" },
    { name: "Telia", industry: "Telecommunications", size: "large" },
    { name: "ServiceNow", industry: "Software", size: "large" },
    { name: "Tietoevry", industry: "IT services", size: "large" },
    { name: "Accenture", industry: "Consulting", size: "large" },
    { name: "Tata Consultancy Services", industry: "IT services", size: "large" },
  ],
  "digital-operations-architect": [
    { name: "Telenor", industry: "Telecommunications", size: "large" },
    { name: "Telia", industry: "Telecommunications", size: "large" },
    { name: "Tietoevry", industry: "IT services", size: "large" },
    { name: "Ericsson", industry: "Telecom equipment", size: "large" },
    { name: "Accenture", industry: "Consulting", size: "large" },
    { name: "Analysys Mason", industry: "Consulting", size: "medium" },
  ],
  "solar-energy-engineer": [
    { name: "Scatec", industry: "Renewable energy", size: "large" },
    { name: "Statkraft", industry: "Renewable energy", size: "large" },
    { name: "Otovo", industry: "Solar energy", size: "medium" },
    { name: "Equinor", industry: "Energy", size: "large" },
    { name: "Fortum", industry: "Energy", size: "large" },
    { name: "ABB", industry: "Electrical engineering", size: "large" },
  ],
  "energy-systems-engineer": [
    { name: "Statkraft", industry: "Renewable energy", size: "large" },
    { name: "Equinor", industry: "Energy", size: "large" },
    { name: "Eviny", industry: "Energy", size: "large" },
    { name: "Fortum", industry: "Energy", size: "large" },
    { name: "Siemens", industry: "Engineering", size: "large" },
    { name: "ABB", industry: "Electrical engineering", size: "large" },
  ],
  "battery-storage-engineer": [
    { name: "Morrow Batteries", industry: "Battery manufacturing", size: "medium" },
    { name: "Freyr", industry: "Battery manufacturing", size: "medium" },
    { name: "Corvus Energy", industry: "Energy storage", size: "medium" },
    { name: "Hydro", industry: "Materials and energy", size: "large" },
    { name: "ABB", industry: "Electrical engineering", size: "large" },
    { name: "Siemens", industry: "Engineering", size: "large" },
  ],
  "ev-infrastructure-engineer": [
    { name: "Eviny", industry: "Energy", size: "large" },
    { name: "Fortum", industry: "Energy", size: "large" },
    { name: "Statkraft", industry: "Renewable energy", size: "large" },
    { name: "ABB", industry: "Electrical engineering", size: "large" },
    { name: "Siemens", industry: "Engineering", size: "large" },
    { name: "Schneider Electric", industry: "Energy management", size: "large" },
  ],
  "industrial-automation-technician": [
    { name: "ABB", industry: "Electrical engineering", size: "large" },
    { name: "Siemens", industry: "Engineering", size: "large" },
    { name: "Hydro", industry: "Materials and energy", size: "large" },
    { name: "Aker Solutions", industry: "Industrial engineering", size: "large" },
    { name: "Schneider Electric", industry: "Energy management", size: "large" },
    { name: "Equinor", industry: "Energy", size: "large" },
  ],
  "renewable-energy-installer": [
    { name: "Otovo", industry: "Solar energy", size: "medium" },
    { name: "Eviny", industry: "Energy", size: "large" },
    { name: "Fjordkraft", industry: "Energy", size: "medium" },
    { name: "Scatec", industry: "Renewable energy", size: "large" },
    { name: "Schneider Electric", industry: "Energy management", size: "large" },
    { name: "Bravida", industry: "Building installation", size: "large" },
  ],
  "data-center-technician": [
    { name: "Green Mountain", industry: "Data centres", size: "medium" },
    { name: "Bulk Infrastructure", industry: "Data centres", size: "medium" },
    { name: "Equinix", industry: "Data centres", size: "large" },
    { name: "Telenor", industry: "Telecommunications", size: "large" },
    { name: "Schneider Electric", industry: "Energy management", size: "large" },
    { name: "ABB", industry: "Electrical engineering", size: "large" },
  ],
  "fintech-specialist": [
    { name: "DNB", industry: "Banking", size: "large" },
    { name: "Vipps", industry: "Payments", size: "large" },
    { name: "Sbanken", industry: "Banking", size: "medium" },
    { name: "Storebrand", industry: "Finance and insurance", size: "large" },
    { name: "Klarna", industry: "Payments", size: "large" },
    { name: "Tripletex", industry: "Financial software", size: "medium" },
  ],
  "customer-success-manager": [
    { name: "Visma", industry: "Software", size: "large" },
    { name: "Cognite", industry: "Industrial software", size: "medium" },
    { name: "Tripletex", industry: "Financial software", size: "medium" },
    { name: "Kahoot", industry: "EdTech", size: "medium" },
    { name: "Microsoft", industry: "Software", size: "large" },
    { name: "Klarna", industry: "Payments", size: "large" },
  ],
  "revenue-operations-manager": [
    { name: "Cognite", industry: "Industrial software", size: "medium" },
    { name: "Visma", industry: "Software", size: "large" },
    { name: "Kahoot", industry: "EdTech", size: "medium" },
    { name: "Tripletex", industry: "Financial software", size: "medium" },
    { name: "Klarna", industry: "Payments", size: "large" },
    { name: "Microsoft", industry: "Software", size: "large" },
  ],
  "data-governance-manager": [
    { name: "Cognite", industry: "Industrial software", size: "medium" },
    { name: "DNB", industry: "Banking", size: "large" },
    { name: "Storebrand", industry: "Finance and insurance", size: "large" },
    { name: "Visma", industry: "Software", size: "large" },
    { name: "NAV", industry: "Public services", size: "large" },
    { name: "Microsoft", industry: "Software", size: "large" },
  ],
  "telemedicine-specialist": [
    { name: "Helse Sør-Øst", industry: "Public health trust", size: "large" },
    { name: "Helse Vest", industry: "Public health trust", size: "large" },
    { name: "Dr.Dropin", industry: "Private healthcare", size: "medium" },
    { name: "Kry", industry: "Digital healthcare", size: "medium" },
    { name: "Aleris", industry: "Private healthcare", size: "large" },
    { name: "NAV", industry: "Public services", size: "large" },
  ],
  "learning-experience-designer": [
    { name: "Kahoot", industry: "EdTech", size: "medium" },
    { name: "Coursera", industry: "Online learning", size: "large" },
    { name: "BI Norwegian Business School", industry: "Higher education", size: "large" },
    { name: "NTNU", industry: "Higher education", size: "large" },
    { name: "Folkeuniversitetet", industry: "Adult education", size: "medium" },
    { name: "Visma", industry: "Software", size: "large" },
  ],
  "ai-education-specialist": [
    { name: "Kahoot", industry: "EdTech", size: "medium" },
    { name: "NTNU", industry: "Higher education", size: "large" },
    { name: "Coursera", industry: "Online learning", size: "large" },
    { name: "Folkeuniversitetet", industry: "Adult education", size: "medium" },
    { name: "Microsoft", industry: "Software", size: "large" },
    { name: "Google", industry: "Technology", size: "large" },
  ],
  "workforce-development-specialist": [
    { name: "NAV", industry: "Public services", size: "large" },
    { name: "Folkeuniversitetet", industry: "Adult education", size: "medium" },
    { name: "BI Norwegian Business School", industry: "Higher education", size: "large" },
    { name: "NTNU", industry: "Higher education", size: "large" },
    { name: "Coursera", industry: "Online learning", size: "large" },
    { name: "Visma", industry: "Software", size: "large" },
  ],
  "digital-skills-trainer": [
    { name: "Folkeuniversitetet", industry: "Adult education", size: "medium" },
    { name: "NAV", industry: "Public services", size: "large" },
    { name: "Kahoot", industry: "EdTech", size: "medium" },
    { name: "Microsoft", industry: "Software", size: "large" },
    { name: "Coursera", industry: "Online learning", size: "large" },
    { name: "Visma", industry: "Software", size: "large" },
  ],
};
