/**
 * Career-employer REALISM overrides — physically-demanding additions (2026-06-15).
 *
 * Employer lists for the ~50 physically-demanding careers added alongside the
 * Career Radar "Physically Demanding Roles" filter rebuild. Norway-first, real
 * employers per role (+ honest "local/self-employed" where the work is mostly
 * small/independent). Consulted by getTopEmployers() so these new careers don't
 * fall to an implausible category fallback.
 */
import type { Employer } from './career-employers';

export const REALISM_EMPLOYERS_PHYSICAL: Record<string, Employer[]> = {
  "arborist": [
    { name: "Local arborist firms & self-employed", industry: "Tree Care", size: "small" },
    { name: "Kommune (parks & green spaces)", industry: "Public Sector", size: "large" },
    { name: "ISS Landscaping", industry: "Facility & Grounds Services", size: "large" },
    { name: "Bymiljøetaten Oslo", industry: "Urban Environment", size: "large" },
    { name: "Norsk Trepleieforum members", industry: "Tree Care", size: "small" },
  ],
  "asphalt-paver": [
    { name: "Veidekke (Veidekke Asfalt)", industry: "Road construction", size: "large", careersUrl: "https://veidekke.no" },
    { name: "NCC Industry", industry: "Asphalt & road", size: "large", careersUrl: "https://ncc.no" },
    { name: "Peab Asfalt", industry: "Asphalt & road", size: "large", careersUrl: "https://peab.no" },
    { name: "Statens vegvesen", industry: "Public roads authority", size: "large", careersUrl: "https://vegvesen.no" },
    { name: "Local firms & self-employed", industry: "Local asfaltfirma", size: "small" },
  ],
  "baggage-handler": [
    { name: "Aviator", industry: "Airport Ground Handling", size: "large", careersUrl: "https://www.aviator.eu/career/" },
    { name: "Menzies Aviation", industry: "Airport Ground Handling", size: "large", careersUrl: "https://www.menziesaviation.com/careers/" },
    { name: "SAS Ground Handling", industry: "Airport Ground Handling", size: "large" },
    { name: "Widerøe Ground Handling", industry: "Airport Ground Handling", size: "medium" },
    { name: "Avinor", industry: "Airport Operations", size: "large", careersUrl: "https://avinor.no/konsern/jobb" },
  ],
  "boxer": [
    { name: "Norges Bokseforbund", industry: "Sports federation", size: "Small" },
    { name: "Local boxing clubs (e.g. Oslo Bokseklubb, BK Sør)", industry: "Sports club", size: "Small" },
    { name: "Clubs & self-employed", industry: "Professional sport", size: "Varies" },
    { name: "Sponsorships & promoters", industry: "Sports marketing", size: "Varies" },
  ],
  "coast-guard-rescue-swimmer": [
    { name: "Kystvakten (Forsvaret)", industry: "Coast Guard", size: "Large" },
    { name: "Redningsselskapet (RS)", industry: "Sea rescue", size: "Medium" },
    { name: "Hovedredningssentralen (HRS)", industry: "Rescue coordination", size: "Medium" },
    { name: "Forsvaret", industry: "Armed forces", size: "Large" },
  ],
  "commercial-fisherman": [
    { name: "Lerøy Seafood Group", industry: "Fishing & Seafood", size: "large", careersUrl: "https://www.leroyseafood.com/en/career/" },
    { name: "Mowi", industry: "Seafood & Aquaculture", size: "large", careersUrl: "https://mowi.com/careers/" },
    { name: "Nergård", industry: "Fishing & Seafood", size: "large" },
    { name: "Norway Pelagic (Pelagia)", industry: "Fishing & Seafood", size: "large" },
    { name: "Local fiskebåt-rederi (coastal vessels)", industry: "Fishing", size: "small" },
    { name: "Self-employed / crew share", industry: "Fishing", size: "varies" },
  ],
  "concrete-finisher": [
    { name: "Veidekke", industry: "Construction", size: "large", careersUrl: "https://veidekke.no" },
    { name: "Skanska Norge", industry: "Construction", size: "large", careersUrl: "https://skanska.no" },
    { name: "Betonmast", industry: "Construction", size: "large", careersUrl: "https://betonmast.no" },
    { name: "Kruse Smith", industry: "Construction", size: "large", careersUrl: "https://krusesmith.no" },
    { name: "Local firms & self-employed", industry: "Local byggefirma", size: "small" },
  ],
  "crane-rigger": [
    { name: "AF Gruppen", industry: "Construction", size: "large", careersUrl: "https://afgruppen.no" },
    { name: "Kranpartner", industry: "Crane services", size: "medium" },
    { name: "Nordic Crane Group", industry: "Crane & lifting", size: "medium", careersUrl: "https://nordiccrane.com" },
    { name: "Veidekke", industry: "Construction", size: "large", careersUrl: "https://veidekke.no" },
    { name: "Local firms & self-employed", industry: "Local kran- og stillasfirma", size: "small" },
  ],
  "deckhand": [
    { name: "Color Line", industry: "Shipping & Ferries", size: "large", careersUrl: "https://www.colorline.no/jobb" },
    { name: "Hurtigruten", industry: "Shipping & Coastal Cruise", size: "large", careersUrl: "https://www.hurtigruten.com/careers" },
    { name: "Torghatten", industry: "Ferries & Transport", size: "large" },
    { name: "Fjord1", industry: "Ferries", size: "large" },
    { name: "Norled", industry: "Ferries", size: "large" },
  ],
  "demolition-worker": [
    { name: "AF Gruppen (AF Decom)", industry: "Demolition & construction", size: "large", careersUrl: "https://afgruppen.no" },
    { name: "Veidekke", industry: "Construction", size: "large", careersUrl: "https://veidekke.no" },
    { name: "Norsk Gjenvinning", industry: "Recycling & demolition", size: "large", careersUrl: "https://norskgjenvinning.no" },
    { name: "Implenia Norge", industry: "Construction", size: "large", careersUrl: "https://implenia.com" },
    { name: "Local firms & self-employed", industry: "Local rivefirma", size: "small" },
  ],
  "dock-worker": [
    { name: "Yilport Oslo", industry: "Port & Terminal Operations", size: "large" },
    { name: "North Sea Terminal", industry: "Port & Terminal Operations", size: "medium" },
    { name: "Bring (Posten)", industry: "Logistics & Terminals", size: "large", careersUrl: "https://www.postennorge.no/en/career" },
    { name: "Port of Oslo (Oslo Havn)", industry: "Port Operations", size: "large" },
    { name: "Local port operators", industry: "Port Operations", size: "small" },
  ],
  "drywall-installer": [
    { name: "Veidekke", industry: "Construction", size: "large", careersUrl: "https://veidekke.no" },
    { name: "Backe", industry: "Construction", size: "large", careersUrl: "https://backe.no" },
    { name: "Peab", industry: "Construction", size: "large", careersUrl: "https://peab.no" },
    { name: "NCC Norge", industry: "Construction", size: "large", careersUrl: "https://ncc.no" },
    { name: "Local firms & self-employed", industry: "Local tømrer- og innredningsfirma", size: "small" },
  ],
  "farmer": [
    { name: "Local farms & self-employed", industry: "Agriculture", size: "small" },
    { name: "Felleskjøpet Agri", industry: "Agriculture", size: "large" },
    { name: "TINE", industry: "Dairy", size: "large" },
    { name: "Nortura", industry: "Meat & Poultry", size: "large" },
    { name: "Norsk Landbruksrådgiving", industry: "Agricultural Advisory", size: "medium" },
  ],
  "forestry-worker": [
    { name: "Glommen Mjøsen Skog", industry: "Forestry", size: "large" },
    { name: "Viken Skog", industry: "Forestry", size: "large" },
    { name: "AT Skog", industry: "Forestry", size: "medium" },
    { name: "Statskog", industry: "Forestry & Land Management", size: "large" },
    { name: "Local skogsentreprenør & self-employed", industry: "Forestry", size: "small" },
  ],
  "foundry-worker": [
    { name: "Elkem", industry: "Silicon & metals", size: "Large", careersUrl: "https://www.elkem.com/careers" },
    { name: "Hydro", industry: "Aluminium smelting & foundry", size: "Large", careersUrl: "https://www.hydro.com/careers" },
    { name: "Eramet Norway", industry: "Manganese alloys", size: "Large" },
    { name: "Benteler Automotive Raufoss", industry: "Metal components", size: "Large" },
    { name: "Local firms & varies", industry: "Foundry & casting", size: "Varies" },
  ],
  "freight-handler": [
    { name: "Bring (Posten Norge)", industry: "Logistics & Freight", size: "large", careersUrl: "https://www.postennorge.no/en/career" },
    { name: "DB Schenker", industry: "Logistics & Freight", size: "large", careersUrl: "https://www.dbschenker.com/global/careers" },
    { name: "PostNord", industry: "Logistics & Freight", size: "large", careersUrl: "https://www.postnord.com/career" },
    { name: "DHL", industry: "Logistics & Freight", size: "large", careersUrl: "https://careers.dhl.com/" },
    { name: "DSV", industry: "Logistics & Freight", size: "large" },
  ],
  "glazier": [
    { name: "Glassmester1", industry: "Glazing specialist", size: "medium", careersUrl: "https://glassmester1.no" },
    { name: "Bilglass / Hurtigruta Carglass", industry: "Glazing", size: "medium" },
    { name: "Veidekke", industry: "Construction", size: "large", careersUrl: "https://veidekke.no" },
    { name: "Skanska Norge", industry: "Construction", size: "large", careersUrl: "https://skanska.no" },
    { name: "Local firms & self-employed", industry: "Local glassmesterfirma", size: "small" },
  ],
  "heavy-equipment-operator": [
    { name: "AF Gruppen", industry: "Construction & civil works", size: "large", careersUrl: "https://afgruppen.no" },
    { name: "Veidekke", industry: "Construction", size: "large", careersUrl: "https://veidekke.no" },
    { name: "Implenia Norge", industry: "Civil engineering", size: "large", careersUrl: "https://implenia.com" },
    { name: "Pon Equipment", industry: "Heavy equipment supplier", size: "large", careersUrl: "https://pon-cat.com" },
    { name: "Local firms & self-employed", industry: "Local maskinentreprenør", size: "small" },
  ],
  "industrial-cleaner": [
    { name: "ISS Facility Services", industry: "Facility services", size: "Large", careersUrl: "https://www.issworld.com" },
    { name: "Coor", industry: "Facility management", size: "Large", careersUrl: "https://www.coor.no" },
    { name: "4Service", industry: "Facility services", size: "Large" },
    { name: "Kaefer Energy", industry: "Industrial services", size: "Large" },
    { name: "Local firms & varies", industry: "Industrial cleaning", size: "Varies" },
  ],
  "irrigation-technician": [
    { name: "Local rørleggerfirma & self-employed", industry: "Plumbing & Water Systems", size: "small" },
    { name: "Kommune (VA-etat)", industry: "Public Sector", size: "large" },
    { name: "Bravida", industry: "Technical Installation", size: "large" },
    { name: "Felleskjøpet Agri", industry: "Agriculture", size: "large" },
    { name: "Norsk Landbruksrådgiving", industry: "Agricultural Advisory", size: "medium" },
  ],
  "logger": [
    { name: "SB Skog", industry: "Forestry", size: "medium" },
    { name: "Glommen Mjøsen Skog", industry: "Forestry", size: "large" },
    { name: "Viken Skog", industry: "Forestry", size: "large" },
    { name: "AT Skog", industry: "Forestry", size: "medium" },
    { name: "Local skogsentreprenør & self-employed", industry: "Forestry", size: "small" },
  ],
  "marine-salvage-diver": [
    { name: "DeepOcean", industry: "Subsea & Marine Services", size: "large", careersUrl: "https://www.deepoceangroup.com/careers" },
    { name: "TechnipFMC", industry: "Subsea Services", size: "large", careersUrl: "https://www.technipfmc.com/en/careers/" },
    { name: "Reach Subsea", industry: "Subsea Services", size: "medium" },
    { name: "Local diving & salvage contractors", industry: "Marine Services", size: "small" },
    { name: "Self-employed / contract diver", industry: "Commercial Diving", size: "varies" },
  ],
  "material-handler": [
    { name: "ASKO", industry: "Wholesale & logistics", size: "Large", careersUrl: "https://www.asko.no" },
    { name: "Posten Bring", industry: "Logistics & postal", size: "Large", careersUrl: "https://www.bring.no/jobb" },
    { name: "NorgesGruppen", industry: "Retail & wholesale", size: "Large" },
    { name: "Elkjøp", industry: "Retail & distribution", size: "Large" },
    { name: "Local firms & varies", industry: "Warehousing", size: "Varies" },
  ],
  "merchant-navy-sailor": [
    { name: "Wallenius Wilhelmsen", industry: "Shipping & Logistics", size: "large", careersUrl: "https://www.walleniuswilhelmsen.com/careers" },
    { name: "Wilson ASA", industry: "Shipping", size: "large", careersUrl: "https://www.wilsonship.no/career" },
    { name: "DOF Group", industry: "Offshore Shipping", size: "large" },
    { name: "Solstad Offshore", industry: "Offshore Shipping", size: "large" },
    { name: "Maersk", industry: "Shipping & Logistics", size: "large", careersUrl: "https://www.maersk.com/careers" },
  ],
  "mine-worker": [
    { name: "Rana Gruber", industry: "Iron ore mining", size: "Medium", careersUrl: "https://www.ranagruber.no" },
    { name: "Store Norske", industry: "Mining (Svalbard)", size: "Medium", careersUrl: "https://www.snsk.no" },
    { name: "Sibelco Nordic", industry: "Industrial minerals", size: "Medium" },
    { name: "Titania", industry: "Ilmenite mining", size: "Medium" },
    { name: "Brønnøy Kalk", industry: "Limestone mining", size: "Medium" },
    { name: "LKAB", industry: "Iron ore mining", size: "Large", careersUrl: "https://www.lkab.com" },
  ],
  "mma-fighter": [
    { name: "Norges Kampsportforbund", industry: "Sports federation", size: "Small" },
    { name: "Frontline Academy", industry: "MMA gym", size: "Small" },
    { name: "Local MMA gyms & clubs", industry: "Sports club", size: "Small" },
    { name: "Clubs & self-employed", industry: "Professional sport", size: "Varies" },
    { name: "Sponsorships & promotions", industry: "Sports marketing", size: "Varies" },
  ],
  "mountain-rescue-specialist": [
    { name: "Røde Kors Hjelpekorps", industry: "Volunteer rescue", size: "Large" },
    { name: "Norsk Folkehjelp", industry: "Volunteer rescue", size: "Large" },
    { name: "Hovedredningssentralen (HRS)", industry: "Rescue coordination", size: "Medium" },
    { name: "Alpine rescue groups (skredgrupper)", industry: "Mountain rescue", size: "Small" },
  ],
  "mover": [
    { name: "Majortrans", industry: "Moving & Relocation", size: "medium", careersUrl: "https://www.majortrans.no/" },
    { name: "Alfa Quality Moving", industry: "Moving & Relocation", size: "medium" },
    { name: "Adams Flyttebyrå", industry: "Moving & Relocation", size: "medium" },
    { name: "Local flyttebyrå", industry: "Moving Services", size: "small" },
    { name: "Self-employed / contract crew", industry: "Moving Services", size: "varies" },
  ],
  "navy-diver": [
    { name: "Forsvaret (Sjøforsvaret)", industry: "Navy", size: "Large" },
    { name: "Minedykkerkommandoen", industry: "Naval diving", size: "Small" },
    { name: "Marinejegerkommandoen (MJK)", industry: "Special operations", size: "Medium" },
  ],
  "offshore-rigger": [
    { name: "Odfjell Drilling", industry: "Offshore Drilling", size: "large", careersUrl: "https://www.odfjelldrilling.com/careers/" },
    { name: "Transocean", industry: "Offshore Drilling", size: "large", careersUrl: "https://www.deepwater.com/careers" },
    { name: "KCA Deutag", industry: "Offshore Drilling", size: "large" },
    { name: "Saipem", industry: "Offshore Energy Services", size: "large" },
    { name: "Seadrill", industry: "Offshore Drilling", size: "large" },
  ],
  "paratrooper": [
    { name: "Forsvaret (Hæren)", industry: "Armed forces", size: "Large" },
    { name: "Forsvarets spesialkommando (FSK)", industry: "Special operations", size: "Medium" },
    { name: "Fallskjermjegertroppen", industry: "Airborne forces", size: "Small" },
  ],
  "quarry-worker": [
    { name: "Franzefoss Minerals", industry: "Aggregates & minerals", size: "Medium", careersUrl: "https://www.franzefoss.no" },
    { name: "NorStone", industry: "Aggregates", size: "Medium" },
    { name: "Velde", industry: "Aggregates & concrete", size: "Medium", careersUrl: "https://www.velde.no" },
    { name: "Sibelco Nordic", industry: "Industrial minerals", size: "Medium" },
    { name: "Local firms & varies", industry: "Quarrying", size: "Varies" },
  ],
  "railway-track-worker": [
    { name: "Bane NOR", industry: "Railway Infrastructure", size: "large", careersUrl: "https://www.banenor.no/jobb" },
    { name: "Baneservice", industry: "Railway Construction & Maintenance", size: "large", careersUrl: "https://www.baneservice.no/" },
    { name: "NRC Group", industry: "Rail & Infrastructure", size: "large" },
    { name: "Spordrift", industry: "Railway Maintenance", size: "large" },
    { name: "Local rail infrastructure contractors", industry: "Rail Construction", size: "small" },
  ],
  "ranch-worker": [
    { name: "Local farms & self-employed", industry: "Agriculture", size: "small" },
    { name: "Nortura", industry: "Meat & Poultry", size: "large" },
    { name: "TINE", industry: "Dairy", size: "large" },
    { name: "Felleskjøpet Agri", industry: "Agriculture", size: "large" },
    { name: "Norsk Landbruksrådgiving", industry: "Agricultural Advisory", size: "medium" },
  ],
  "recycling-plant-operator": [
    { name: "Norsk Gjenvinning", industry: "Recycling & waste", size: "Large", careersUrl: "https://www.norskgjenvinning.no" },
    { name: "Ragn-Sells", industry: "Recycling & waste", size: "Large", careersUrl: "https://www.ragnsells.no" },
    { name: "Stena Recycling", industry: "Recycling & metals", size: "Large", careersUrl: "https://www.stenarecycling.no" },
    { name: "IVAR", industry: "Municipal waste & recycling", size: "Medium", careersUrl: "https://www.ivar.no" },
    { name: "Local firms & varies", industry: "Recycling", size: "Varies" },
  ],
  "refinery-operator": [
    { name: "Equinor Mongstad", industry: "Oil refining", size: "Large", careersUrl: "https://www.equinor.com/careers" },
    { name: "Esso Slagentangen", industry: "Oil refining", size: "Large" },
    { name: "Yara Porsgrunn", industry: "Chemicals & fertiliser", size: "Large", careersUrl: "https://www.yara.com/careers" },
    { name: "INEOS", industry: "Petrochemicals", size: "Large" },
    { name: "Borealis", industry: "Petrochemicals", size: "Large" },
  ],
  "roofer": [
    { name: "Veidekke", industry: "Construction", size: "large", careersUrl: "https://veidekke.no" },
    { name: "Skanska Norge", industry: "Construction", size: "large", careersUrl: "https://skanska.no" },
    { name: "Icopal Tak", industry: "Roofing specialist", size: "medium" },
    { name: "Protan", industry: "Roofing membranes", size: "medium", careersUrl: "https://protan.no" },
    { name: "Local firms & self-employed", industry: "Local taktekkerfirma", size: "small" },
  ],
  "rugby-player": [
    { name: "Norges Rugbyforbund", industry: "Sports federation", size: "Small" },
    { name: "Oslo RK", industry: "Rugby club", size: "Small" },
    { name: "Stavanger Rugbyklubb", industry: "Rugby club", size: "Small" },
    { name: "Clubs & self-employed", industry: "Amateur sport", size: "Varies" },
  ],
  "sewer-maintenance-worker": [
    { name: "Kommune (VA-etat)", industry: "Public Sector", size: "large" },
    { name: "Oslo VAV (Vann- og avløpsetaten)", industry: "Public Water Utility", size: "large" },
    { name: "IVAR", industry: "Water & Waste Utility", size: "large" },
    { name: "Bravida", industry: "Technical Installation", size: "large" },
    { name: "Local rørleggerfirma & self-employed", industry: "Plumbing & Water Systems", size: "small" },
  ],
  "shepherd": [
    { name: "Local farms & self-employed", industry: "Agriculture", size: "small" },
    { name: "Nortura", industry: "Meat & Wool", size: "large" },
    { name: "Norsk Sau og Geit", industry: "Sheep & Goat Farming", size: "medium" },
    { name: "Norsk Landbruksrådgiving", industry: "Agricultural Advisory", size: "medium" },
    { name: "Felleskjøpet Agri", industry: "Agriculture", size: "large" },
  ],
  "ski-patrol-officer": [
    { name: "SkiStar (Trysil, Hemsedal)", industry: "Ski resorts", size: "Large" },
    { name: "Trysil", industry: "Ski resort", size: "Large" },
    { name: "Hemsedal Skisenter", industry: "Ski resort", size: "Medium" },
    { name: "Røde Kors Hjelpekorps", industry: "Volunteer rescue", size: "Large" },
  ],
  "smokejumper": [
    { name: "Sivilforsvaret (skogbrannberedskap)", industry: "Civil protection", size: "Large" },
    { name: "Local fire & rescue services (brann og redning)", industry: "Emergency services", size: "Varies" },
    { name: "International smokejumper agencies (e.g. US Forest Service)", industry: "Wildfire aviation", size: "Large" },
    { name: "Varies (seasonal/international)", industry: "Wildfire response", size: "Varies" },
  ],
  "steel-erector": [
    { name: "AF Gruppen", industry: "Construction", size: "large", careersUrl: "https://afgruppen.no" },
    { name: "Implenia Norge", industry: "Construction", size: "large", careersUrl: "https://implenia.com" },
    { name: "Betonmast", industry: "Construction", size: "large", careersUrl: "https://betonmast.no" },
    { name: "NCC Norge", industry: "Construction", size: "large", careersUrl: "https://ncc.no" },
    { name: "Local firms & self-employed", industry: "Local stålmontasjefirma", size: "small" },
  ],
  "stonemason": [
    { name: "Veidekke", industry: "Construction", size: "large", careersUrl: "https://veidekke.no" },
    { name: "AF Gruppen", industry: "Construction", size: "large", careersUrl: "https://afgruppen.no" },
    { name: "Backe", industry: "Construction", size: "large", careersUrl: "https://backe.no" },
    { name: "Kruse Smith", industry: "Construction", size: "large", careersUrl: "https://krusesmith.no" },
    { name: "Local firms & self-employed", industry: "Local murmesterfirma", size: "small" },
  ],
  "telecom-tower-climber": [
    { name: "Telenor", industry: "Telecommunications", size: "Large" },
    { name: "Telia Norge", industry: "Telecommunications", size: "Large" },
    { name: "Nettpartner", industry: "Infrastructure services", size: "Medium" },
    { name: "Caverion", industry: "Technical building services", size: "Large" },
    { name: "Relacom", industry: "Network field services", size: "Medium" },
    { name: "Cellnex (mast operator)", industry: "Tower infrastructure", size: "Large" },
  ],
  "tree-climber": [
    { name: "Local arborist firms & self-employed", industry: "Tree Care", size: "small" },
    { name: "Kommune (parks & green spaces)", industry: "Public Sector", size: "large" },
    { name: "ISS Landscaping", industry: "Facility & Grounds Services", size: "large" },
    { name: "Bymiljøetaten Oslo", industry: "Urban Environment", size: "large" },
    { name: "Norsk Trepleieforum members", industry: "Tree Care", size: "small" },
  ],
  "tugboat-crew": [
    { name: "Buksér og Berging", industry: "Towage & Marine Services", size: "medium", careersUrl: "https://www.bube.no/" },
    { name: "Østensjø Rederi", industry: "Towage & Offshore", size: "medium" },
    { name: "Norled", industry: "Maritime Transport", size: "large" },
    { name: "Boa Offshore", industry: "Towage & Heavy Transport", size: "medium" },
    { name: "Local harbour towage operators", industry: "Marine Services", size: "small" },
  ],
  "water-network-technician": [
    { name: "Kommune (VA-etat)", industry: "Public Sector", size: "large" },
    { name: "Oslo VAV (Vann- og avløpsetaten)", industry: "Public Water Utility", size: "large" },
    { name: "IVAR", industry: "Water & Waste Utility", size: "large" },
    { name: "Bravida", industry: "Technical Installation", size: "large" },
    { name: "Local rørleggerfirma & self-employed", industry: "Plumbing & Water Systems", size: "small" },
  ],
  "wildland-firefighter": [
    { name: "Local fire & rescue services (brann og redning)", industry: "Emergency services", size: "Varies" },
    { name: "Sivilforsvaret", industry: "Civil protection", size: "Large" },
    { name: "Skogbrannhelikopter / aerial fire support", industry: "Wildfire aviation", size: "Small" },
    { name: "Varies (seasonal)", industry: "Wildfire response", size: "Varies" },
  ],
  "wrestler": [
    { name: "Norges Bryteforbund", industry: "Sports federation", size: "Small" },
    { name: "Local wrestling clubs (e.g. SK Vidar, IL Sverre)", industry: "Sports club", size: "Small" },
    { name: "Olympiatoppen (elite support)", industry: "Elite sport support", size: "Medium" },
    { name: "Clubs & self-employed", industry: "Amateur sport", size: "Varies" },
  ],
};
