/**
 * Hospitality Career Cards
 * Front-of-house, kitchen, accommodation, events, wellness, and travel roles
 * across the hospitality industry. Suitable for youth ages 15-23 exploring
 * entry points into hospitality careers.
 */

type HospitalityCareer = {
  roleName: string;
  summary: string;
  traits: string[];
  dayInLife: string[];
  realityCheck: string;
  salaryBand: string;
  companies: string[];
  certifications: string[];
  nextSteps: string[];
  tags: string[];
  order: number;
};

const baseTags = ['hospitality'];

export const hospitalityCareerCards: HospitalityCareer[] = [
  {
    roleName: 'Hotel Manager',
    summary: 'Run an entire hotel — from guest experience to staff, budgets, and brand standards. The buck stops with you.',
    traits: ['Leader', 'Calm under pressure', 'Commercial', 'People-first'],
    dayInLife: [
      'Review occupancy, revenue and guest feedback',
      'Walk the property and check standards',
      'Lead department head meetings',
      'Handle escalated guest issues',
      'Plan budgets, marketing and staffing',
    ],
    realityCheck: 'Long hours, on-call for emergencies, and you own every problem in the building. Years of climbing the ladder usually required.',
    salaryBand: '500-900k NOK/year',
    companies: ['Scandic', 'Nordic Choice', 'Thon Hotels', 'Radisson', 'Marriott'],
    certifications: ['Degree in Hospitality Management helpful', 'Years of progressive hotel experience', 'Leadership training'],
    nextSteps: [
      'Start in front office or F&B and learn every department',
      'Take a hospitality management course',
      'Find a mentor who already runs a hotel',
      'Shadow a duty manager for a week',
    ],
    tags: [...baseTags, 'leadership', 'hotels', 'career-goal'],
    order: 100,
  },
  {
    roleName: 'Assistant Hotel Manager',
    summary: 'Right-hand to the GM. You make the hotel run day-to-day and step in when the manager is off.',
    traits: ['Organised', 'Diplomatic', 'Hands-on', 'Detail-oriented'],
    dayInLife: [
      'Cover shifts across departments as needed',
      'Coach team leaders and resolve staffing gaps',
      'Audit standards and guest satisfaction scores',
      'Run morning briefings',
      'Report issues and ideas to the GM',
    ],
    realityCheck: 'You absorb pressure from above and below. Weekends, evenings and crisis-mode are normal.',
    salaryBand: '450-650k NOK/year',
    companies: ['Scandic', 'Nordic Choice', 'Thon', 'Radisson'],
    certifications: ['Hospitality diploma or degree', '3-5 years hotel experience'],
    nextSteps: [
      'Work as a supervisor in reception or F&B first',
      'Volunteer to cover duty manager shifts',
      'Learn basic hotel revenue terms (RevPAR, ADR)',
    ],
    tags: [...baseTags, 'leadership', 'hotels'],
    order: 101,
  },
  {
    roleName: 'Front Office Manager',
    summary: 'Lead the reception and guest services team — the face of the hotel.',
    traits: ['Friendly', 'Decisive', 'Multitasker', 'Tech-savvy'],
    dayInLife: [
      'Schedule reception staff and review handovers',
      'Train team on the property management system',
      'Handle VIP arrivals and complaints',
      'Track check-in metrics and upsells',
      'Coordinate with housekeeping on room readiness',
    ],
    realityCheck: 'You answer for every bad check-in. Shifts cover early mornings and late nights.',
    salaryBand: '400-550k NOK/year',
    companies: ['Scandic', 'Radisson', 'Thon', 'Marriott'],
    certifications: ['Hospitality background', 'PMS systems (Opera, Mews)'],
    nextSteps: [
      'Become a strong receptionist first',
      'Learn the hotel PMS deeply',
      'Practice handling tough guest scenarios',
    ],
    tags: [...baseTags, 'hotels', 'customer-service'],
    order: 102,
  },
  {
    roleName: 'Receptionist',
    summary: 'Welcome guests, check them in and out, answer questions, and solve problems on the spot.',
    traits: ['Welcoming', 'Calm', 'Organised', 'Good communicator'],
    dayInLife: [
      'Check guests in and out',
      'Answer phones and emails',
      'Handle bookings and changes',
      'Recommend things to do locally',
      'Pass issues to housekeeping or maintenance',
    ],
    realityCheck: 'Smile no matter what. Night shifts and weekends are normal. Difficult guests come with the job.',
    salaryBand: '180-230 NOK/hour',
    companies: ['Scandic', 'Thon', 'Radisson', 'Independent hotels', 'Hostels'],
    certifications: ['No formal education required', 'English a must, second language a plus', 'PMS training on the job'],
    nextSteps: [
      'Apply directly at hotels — bring a smile and a CV',
      'Practice answering the phone professionally',
      'Learn a second language',
    ],
    tags: [...baseTags, 'hotels', 'entry-level', 'first-job', 'customer-service'],
    order: 103,
  },
  {
    roleName: 'Concierge',
    summary: 'The local expert. Book restaurants, arrange tours, find the impossible, and make guest stays unforgettable.',
    traits: ['Knowledgeable', 'Resourceful', 'Polished', 'Curious'],
    dayInLife: [
      'Recommend restaurants, shows and experiences',
      'Book taxis, tours and tickets',
      'Arrange special requests and surprises',
      'Build a network of local contacts',
      'Greet returning guests warmly',
    ],
    realityCheck: 'Guests expect miracles. You need a great memory, a black book of contacts, and patience.',
    salaryBand: '200-280 NOK/hour + tips',
    companies: ['Luxury hotels', 'Boutique properties', 'Cruise lines'],
    certifications: ['Les Clefs d\'Or membership (advanced)', 'Strong local knowledge'],
    nextSteps: [
      'Start as a receptionist at a hotel with a concierge desk',
      'Explore your city — restaurants, museums, hidden gems',
      'Learn languages spoken by your hotel\'s guests',
    ],
    tags: [...baseTags, 'hotels', 'customer-service', 'tips'],
    order: 104,
  },
  {
    roleName: 'Porter / Bellhop',
    summary: 'Carry luggage, escort guests to rooms, and make first impressions count.',
    traits: ['Friendly', 'Physically fit', 'Helpful', 'Discreet'],
    dayInLife: [
      'Welcome guests at the door',
      'Carry and store luggage',
      'Escort guests to rooms and explain features',
      'Run errands around the property',
      'Hail taxis and load cars',
    ],
    realityCheck: 'Lots of standing, lifting, and being on your feet. Tips can be a real boost in tourist hotels.',
    salaryBand: '170-210 NOK/hour + tips',
    companies: ['Mid- and high-end hotels', 'Resorts'],
    certifications: ['No formal education required', 'On-the-job training'],
    nextSteps: [
      'Apply at larger hotels with bell desks',
      'Practice carrying yourself with confidence',
      'Learn a few welcome phrases in different languages',
    ],
    tags: [...baseTags, 'hotels', 'entry-level', 'first-job', 'physical', 'tips'],
    order: 105,
  },
  {
    roleName: 'Guest Relations Manager',
    summary: 'Look after VIPs, fix complaints, and make sure every guest leaves happy.',
    traits: ['Empathetic', 'Diplomatic', 'Polished', 'Problem-solver'],
    dayInLife: [
      'Greet VIP arrivals personally',
      'Resolve complaints with calm and creativity',
      'Track guest preferences for return visits',
      'Coordinate special touches in rooms',
      'Report trends to the GM',
    ],
    realityCheck: 'You are a complaints magnet by design. Emotional resilience matters more than anything.',
    salaryBand: '420-600k NOK/year',
    companies: ['Luxury hotels', 'Resorts', 'Cruise lines'],
    certifications: ['Hospitality background', 'Conflict resolution training'],
    nextSteps: [
      'Build front-office experience first',
      'Learn how to defuse upset people calmly',
      'Read guest review platforms to understand pain points',
    ],
    tags: [...baseTags, 'hotels', 'customer-service', 'leadership'],
    order: 106,
  },
  {
    roleName: 'Housekeeping Manager',
    summary: 'Lead the team that keeps every room and public area spotless.',
    traits: ['Organised', 'Detail-obsessed', 'Fair leader', 'Practical'],
    dayInLife: [
      'Schedule room attendants and assign sections',
      'Inspect rooms against brand standards',
      'Order linens, supplies and chemicals',
      'Train staff on safety and efficiency',
      'Coordinate with front office on room readiness',
    ],
    realityCheck: 'You manage a large, often non-Norwegian-speaking team under tight deadlines. Physically demanding.',
    salaryBand: '380-520k NOK/year',
    companies: ['All hotel chains', 'Resorts', 'Cruise lines'],
    certifications: ['Years of housekeeping experience', 'Leadership training'],
    nextSteps: [
      'Start as a room attendant',
      'Learn the chemicals, equipment and timings',
      'Practice giving clear instructions',
    ],
    tags: [...baseTags, 'hotels', 'leadership'],
    order: 107,
  },
  {
    roleName: 'Housekeeper',
    summary: 'Keep rooms and public areas clean, fresh and ready. Quiet, important work that guests notice immediately.',
    traits: ['Hardworking', 'Reliable', 'Detailed', 'Quick'],
    dayInLife: [
      'Clean assigned rooms to standard',
      'Restock toiletries and linens',
      'Report damage or maintenance issues',
      'Help with laundry and storage',
      'Tidy lobbies and corridors',
    ],
    realityCheck: 'Physically tough — bending, lifting, on your feet all day. Time pressure on every room.',
    salaryBand: '170-210 NOK/hour',
    companies: ['Hotels', 'Resorts', 'Apartment-hotels', 'Cleaning agencies'],
    certifications: ['No formal education required', 'On-the-job training'],
    nextSteps: [
      'Apply at any hotel — they almost always need housekeeping',
      'Get used to early starts',
      'Learn to work fast without cutting corners',
    ],
    tags: [...baseTags, 'hotels', 'entry-level', 'first-job', 'physical'],
    order: 108,
  },
  {
    roleName: 'Room Attendant',
    summary: 'Specialist housekeeper focused on turning guest rooms over quickly and perfectly.',
    traits: ['Efficient', 'Independent', 'Detail-oriented', 'Discreet'],
    dayInLife: [
      'Strip and remake beds',
      'Clean bathrooms to spec',
      'Replace amenities and mini-bar items',
      'Vacuum and dust',
      'Log issues for maintenance',
    ],
    realityCheck: 'You\'re measured on rooms-per-shift. Body aches are part of the deal early on.',
    salaryBand: '170-210 NOK/hour',
    companies: ['All hotel chains', 'Resorts'],
    certifications: ['No formal education required'],
    nextSteps: [
      'Apply to hotels directly',
      'Build stamina and a steady pace',
      'Learn the brand\'s "perfect room" standard',
    ],
    tags: [...baseTags, 'hotels', 'entry-level', 'first-job', 'physical'],
    order: 109,
  },
  {
    roleName: 'Executive Chef',
    summary: 'Lead an entire kitchen — design menus, manage costs, and keep standards sky-high.',
    traits: ['Creative', 'Disciplined', 'Leader', 'Resilient'],
    dayInLife: [
      'Plan menus and source ingredients',
      'Cost dishes and manage food margins',
      'Lead the brigade and run service',
      'Train sous chefs and line cooks',
      'Meet suppliers and the GM',
    ],
    realityCheck: 'Brutal hours, intense pressure, and full responsibility for hygiene, cost and quality. Years to reach.',
    salaryBand: '550-900k NOK/year',
    companies: ['Hotels', 'Fine dining', 'Resorts', 'Cruise lines'],
    certifications: ['Vocational chef training (kokk)', 'Years through the brigade', 'Leadership skills'],
    nextSteps: [
      'Start as a commis chef',
      'Train as a kokk via vocational school',
      'Stage in respected kitchens to learn',
    ],
    tags: [...baseTags, 'kitchen', 'leadership', 'career-goal'],
    order: 110,
  },
  {
    roleName: 'Sous Chef',
    summary: 'Second-in-command in the kitchen. Run service, lead the line, and back up the head chef.',
    traits: ['Strong cook', 'Organised', 'Calm under fire', 'Mentor'],
    dayInLife: [
      'Run the pass during service',
      'Cover any station that needs help',
      'Order produce and check deliveries',
      'Coach junior chefs',
      'Step in for the head chef when away',
    ],
    realityCheck: 'You take heat from both directions. Long evenings, hot kitchens, constant pressure.',
    salaryBand: '420-600k NOK/year',
    companies: ['Hotels', 'Restaurants', 'Cruise lines'],
    certifications: ['Vocational chef training', '4+ years kitchen experience'],
    nextSteps: [
      'Build experience across stations as a chef de partie',
      'Get really good at one cuisine first',
      'Practice leading a small team in a calm voice',
    ],
    tags: [...baseTags, 'kitchen', 'leadership'],
    order: 111,
  },
  {
    roleName: 'Chef de Partie',
    summary: 'Run a single station in the kitchen — sauce, grill, fish, larder. Specialist territory.',
    traits: ['Skilled', 'Fast', 'Consistent', 'Team player'],
    dayInLife: [
      'Prep your station before service',
      'Cook every order from your section',
      'Keep your station clean and stocked',
      'Communicate with the pass',
      'Mentor commis chefs',
    ],
    realityCheck: 'Speed and consistency are everything. Burns and cuts are normal at first.',
    salaryBand: '320-450k NOK/year',
    companies: ['Restaurants', 'Hotels', 'Catering'],
    certifications: ['Vocational chef training', '2+ years kitchen experience'],
    nextSteps: [
      'Train as a kokk (chef apprenticeship in Norway)',
      'Try every station to find your strength',
      'Watch experienced chefs and copy their flow',
    ],
    tags: [...baseTags, 'kitchen'],
    order: 112,
  },
  {
    roleName: 'Commis Chef',
    summary: 'Junior chef learning the ropes. Prep, basic cooking, and watching the pros work.',
    traits: ['Eager', 'Hardworking', 'Coachable', 'Tough'],
    dayInLife: [
      'Wash, peel and chop produce',
      'Help prep the day\'s mise en place',
      'Assist senior chefs on stations',
      'Keep stations clean',
      'Soak up everything you see',
    ],
    realityCheck: 'You\'re bottom of the food chain. Long hours, low pay, and high standards. Best people learn fastest.',
    salaryBand: '180-220 NOK/hour',
    companies: ['Hotels', 'Restaurants', 'Catering'],
    certifications: ['Often part of vocational kokk apprenticeship', 'No prior experience required'],
    nextSteps: [
      'Apply to a kitchen with a learning culture',
      'Sign up for the kokk apprenticeship',
      'Learn knife skills at home',
    ],
    tags: [...baseTags, 'kitchen', 'entry-level', 'first-job', 'apprenticeship'],
    order: 113,
  },
  {
    roleName: 'Pastry Chef',
    summary: 'Specialist in desserts, breads and showpieces. Precision, creativity and patience meet.',
    traits: ['Precise', 'Creative', 'Patient', 'Early riser'],
    dayInLife: [
      'Bake breads and pastries early morning',
      'Plate desserts during service',
      'Decorate cakes and showpieces',
      'Manage stocks of butter, flour, chocolate',
      'Develop new desserts',
    ],
    realityCheck: 'Early starts (4am common). Pastry is unforgiving — measurements matter.',
    salaryBand: '320-500k NOK/year',
    companies: ['Hotels', 'Bakeries', 'Fine dining', 'Patisseries'],
    certifications: ['Vocational baker (baker) or chef training', 'Specialist pastry courses'],
    nextSteps: [
      'Bake at home — start with classic recipes',
      'Apply to bakeries or hotel pastry sections',
      'Look into the baker apprenticeship',
    ],
    tags: [...baseTags, 'kitchen', 'creative'],
    order: 114,
  },
  {
    roleName: 'Kitchen Porter',
    summary: 'Wash up, prep basics, and keep the kitchen running. The unsung hero of every restaurant.',
    traits: ['Hardworking', 'Reliable', 'Helpful', 'Quick'],
    dayInLife: [
      'Wash dishes, pots and utensils',
      'Help with basic prep',
      'Take out rubbish and recycling',
      'Mop and clean the kitchen',
      'Restock chefs as needed',
    ],
    realityCheck: 'Hot, wet, fast and physical. Often late nights. A great way into the kitchen world.',
    salaryBand: '170-200 NOK/hour',
    companies: ['Restaurants', 'Hotels', 'Catering', 'Cafés'],
    certifications: ['No formal education required'],
    nextSteps: [
      'Apply at any busy kitchen',
      'Show up reliably — that alone gets you promoted',
      'Ask chefs to teach you basic prep',
    ],
    tags: [...baseTags, 'kitchen', 'entry-level', 'first-job', 'physical'],
    order: 115,
  },
  {
    roleName: 'Restaurant Manager',
    summary: 'Run the front of house — staff, service, bookings, money, and guest happiness.',
    traits: ['Leader', 'Calm', 'Commercial', 'Hospitable'],
    dayInLife: [
      'Open and close the restaurant',
      'Brief the team before service',
      'Handle bookings and walk-ins',
      'Resolve guest issues',
      'Track revenue, costs and tips',
    ],
    realityCheck: 'Evenings and weekends are your prime time. You own every empty table.',
    salaryBand: '420-650k NOK/year',
    companies: ['Restaurant groups', 'Hotels', 'Independents'],
    certifications: ['Hospitality background', 'Alcohol service training (kunnskapsprøven)'],
    nextSteps: [
      'Work as a waiter, then headwaiter, then supervisor',
      'Learn basic restaurant accounting',
      'Practice running pre-service briefings',
    ],
    tags: [...baseTags, 'restaurants', 'leadership'],
    order: 116,
  },
  {
    roleName: 'Assistant Restaurant Manager',
    summary: 'Run shifts, lead the floor team, and back up the manager.',
    traits: ['Organised', 'Hands-on', 'Team-focused', 'Friendly'],
    dayInLife: [
      'Run a shift end-to-end',
      'Coach servers and bar staff',
      'Handle complaints on the floor',
      'Cash up at the end of the night',
      'Cover for the manager when off',
    ],
    realityCheck: 'You\'re the buffer between staff and management. Late nights are standard.',
    salaryBand: '350-500k NOK/year',
    companies: ['Restaurant groups', 'Hotels', 'Independents'],
    certifications: ['Floor experience', 'Alcohol service training'],
    nextSteps: [
      'Become a confident waiter first',
      'Volunteer to lead small teams on shift',
    ],
    tags: [...baseTags, 'restaurants', 'leadership'],
    order: 117,
  },
  {
    roleName: 'Waiter / Waitress',
    summary: 'Take orders, serve food and drink, and look after guests during their visit.',
    traits: ['Friendly', 'Quick', 'Memory like a sponge', 'Calm under pressure'],
    dayInLife: [
      'Set up tables before service',
      'Greet guests and take orders',
      'Serve food and drinks',
      'Recommend dishes and upsell gently',
      'Clear and reset tables',
    ],
    realityCheck: 'Long evenings on your feet. Tips help. Bad nights happen — shake them off.',
    salaryBand: '180-230 NOK/hour + tips',
    companies: ['Restaurants', 'Hotels', 'Cafés', 'Catering'],
    certifications: ['No formal education required', 'Alcohol service training (18+) helpful'],
    nextSteps: [
      'Apply locally — restaurants almost always need staff',
      'Practice carrying multiple plates',
      'Learn the menu inside out',
    ],
    tags: [...baseTags, 'restaurants', 'entry-level', 'first-job', 'tips'],
    order: 118,
  },
  {
    roleName: 'Bartender',
    summary: 'Make drinks, run the bar, and create the vibe. Part craft, part performance.',
    traits: ['Personable', 'Fast', 'Creative', 'Trustworthy'],
    dayInLife: [
      'Set up the bar and stock fridges',
      'Make cocktails, beers and soft drinks',
      'Chat with guests',
      'Cash up and reconcile',
      'Clean down at end of night',
    ],
    realityCheck: 'Late nights, loud rooms, and difficult customers. Must be 18+ in Norway.',
    salaryBand: '190-260 NOK/hour + tips',
    companies: ['Bars', 'Hotels', 'Restaurants', 'Cruise lines'],
    certifications: ['18+', 'Kunnskapsprøven (Norwegian alcohol service test)', 'Bartending courses optional'],
    nextSteps: [
      'Start as a barback or waiter',
      'Take a basic cocktail course',
      'Practice making 5 classic drinks',
    ],
    tags: [...baseTags, 'restaurants', 'bars', '18+', 'tips'],
    order: 119,
  },
  {
    roleName: 'Bar Manager',
    summary: 'Run a bar end-to-end — drinks list, stock, staff, and atmosphere.',
    traits: ['Leader', 'Creative', 'Numerate', 'Sociable'],
    dayInLife: [
      'Build cocktail and drinks menus',
      'Order spirits, beers and wines',
      'Schedule and train bar staff',
      'Track stock and wastage',
      'Run the floor on busy nights',
    ],
    realityCheck: 'Nights, weekends, and tight margins. Theft and stock control are constant headaches.',
    salaryBand: '400-600k NOK/year',
    companies: ['Bars', 'Hotel bars', 'Restaurant groups'],
    certifications: ['Alcohol service training', 'Years behind the bar'],
    nextSteps: [
      'Become an excellent bartender first',
      'Learn how stocktakes and margins work',
    ],
    tags: [...baseTags, 'bars', 'leadership', '18+'],
    order: 120,
  },
  {
    roleName: 'Sommelier',
    summary: 'Wine specialist. Pair wines with food, build wine lists, and guide guests through tastings.',
    traits: ['Curious', 'Refined palate', 'Confident', 'Studious'],
    dayInLife: [
      'Recommend wines to guests',
      'Pour and serve at the table',
      'Manage the cellar and stock',
      'Train waiters on the wine list',
      'Taste new wines with suppliers',
    ],
    realityCheck: 'Years of study, exams, and constant tasting. Mostly fine-dining environments.',
    salaryBand: '380-650k NOK/year',
    companies: ['Fine dining', 'Hotels', 'Wine bars'],
    certifications: ['WSET levels 1-4', 'Court of Master Sommeliers', '18+'],
    nextSteps: [
      'Work as a waiter in a wine-focused restaurant',
      'Take WSET Level 1',
      'Read about wine regions in your spare time',
    ],
    tags: [...baseTags, 'restaurants', '18+', 'specialist'],
    order: 121,
  },
  {
    roleName: 'Host / Hostess',
    summary: 'Welcome guests, manage the bookings and seating, and set the tone for the visit.',
    traits: ['Warm', 'Organised', 'Calm', 'Well-presented'],
    dayInLife: [
      'Greet guests and check reservations',
      'Seat tables and hand out menus',
      'Manage the waiting list',
      'Answer phones and take bookings',
      'Coordinate with servers',
    ],
    realityCheck: 'Standing for long shifts. Angry guests on busy nights aim at you first.',
    salaryBand: '170-210 NOK/hour',
    companies: ['Restaurants', 'Hotels', 'Event venues'],
    certifications: ['No formal education required'],
    nextSteps: [
      'Apply at busy restaurants',
      'Practice a calm, warm greeting',
    ],
    tags: [...baseTags, 'restaurants', 'entry-level', 'first-job', 'customer-service'],
    order: 122,
  },
  {
    roleName: 'Event Manager',
    summary: 'Plan and deliver weddings, conferences, parties and corporate events end-to-end.',
    traits: ['Organised', 'Creative', 'Calm', 'Detail-obsessed'],
    dayInLife: [
      'Meet clients and design events',
      'Build budgets and timelines',
      'Book suppliers and venues',
      'Run events on the day',
      'Debrief and follow up after',
    ],
    realityCheck: 'Long days on event days, lots of email between. Things go wrong — you fix them invisibly.',
    salaryBand: '420-650k NOK/year',
    companies: ['Hotels', 'Event agencies', 'Venues', 'Conference centres'],
    certifications: ['Events or hospitality background', 'Project management skills'],
    nextSteps: [
      'Volunteer at festivals or events',
      'Help run a school or community event',
      'Apply as an events coordinator',
    ],
    tags: [...baseTags, 'events', 'leadership', 'organised'],
    order: 123,
  },
  {
    roleName: 'Event Coordinator',
    summary: 'The doer behind every event. Logistics, suppliers, and details, all on time.',
    traits: ['Organised', 'Practical', 'Calm', 'Friendly'],
    dayInLife: [
      'Build run sheets and checklists',
      'Coordinate suppliers and deliveries',
      'Set up and break down spaces',
      'Be the on-the-ground contact on event day',
      'Handle last-minute changes',
    ],
    realityCheck: 'Last-minute pivots are normal. Long event days, often weekends.',
    salaryBand: '320-450k NOK/year',
    companies: ['Hotels', 'Agencies', 'Venues'],
    certifications: ['No formal education required to start', 'Events diploma helpful'],
    nextSteps: [
      'Volunteer at events to build experience',
      'Apply to hotel events teams',
    ],
    tags: [...baseTags, 'events', 'entry-level'],
    order: 124,
  },
  {
    roleName: 'Banquet Manager',
    summary: 'Run large sit-down events — weddings, galas, conferences. Food, service and timing.',
    traits: ['Leader', 'Calm', 'Detail-driven', 'Stamina'],
    dayInLife: [
      'Brief banquet staff before each event',
      'Coordinate kitchen, service and AV',
      'Run the timing of courses and speeches',
      'Handle VIP and dietary requests',
      'Reset rooms for the next event',
    ],
    realityCheck: 'Huge rooms, hundreds of guests, tight timings. Late nights are normal.',
    salaryBand: '400-580k NOK/year',
    companies: ['Hotels', 'Conference centres', 'Function venues'],
    certifications: ['F&B experience', 'Leadership training'],
    nextSteps: [
      'Work in hotel F&B at large-event venues',
      'Volunteer for big functions early',
    ],
    tags: [...baseTags, 'events', 'restaurants', 'leadership'],
    order: 125,
  },
  {
    roleName: 'Catering Manager',
    summary: 'Run off-site food and drink for events, schools, hospitals or corporate clients.',
    traits: ['Logistical', 'Organised', 'Calm', 'Numerate'],
    dayInLife: [
      'Plan menus with chefs',
      'Build quotes for clients',
      'Coordinate deliveries and equipment',
      'Lead on-site service teams',
      'Handle invoicing and follow-up',
    ],
    realityCheck: 'Lots of moving parts in unfamiliar venues. Things you forget on the truck haunt you.',
    salaryBand: '400-600k NOK/year',
    companies: ['Catering companies', 'Hotels', 'Contract caterers'],
    certifications: ['Hospitality background', 'Food hygiene certificate'],
    nextSteps: [
      'Work for a catering company in any role',
      'Learn how event quotes are built',
    ],
    tags: [...baseTags, 'events', 'kitchen', 'leadership'],
    order: 126,
  },
  {
    roleName: 'Spa Manager',
    summary: 'Lead a spa or wellness centre — therapists, treatments, retail and guest experience.',
    traits: ['Calming', 'Commercial', 'Leader', 'Wellness-minded'],
    dayInLife: [
      'Schedule therapists and treatments',
      'Train team on protocols',
      'Track retail sales and bookings',
      'Handle VIP guests',
      'Manage stock of products',
    ],
    realityCheck: 'You balance calm vibes with hard sales targets.',
    salaryBand: '420-600k NOK/year',
    companies: ['Hotel spas', 'Wellness centres', 'Resorts', 'Cruise lines'],
    certifications: ['Spa therapy background', 'Leadership training'],
    nextSteps: [
      'Train as a spa therapist first',
      'Learn basic retail and KPIs',
    ],
    tags: [...baseTags, 'wellness', 'leadership'],
    order: 127,
  },
  {
    roleName: 'Spa Therapist',
    summary: 'Give massages, facials and body treatments. Help guests relax and feel cared for.',
    traits: ['Caring', 'Physical stamina', 'Calm', 'Detail-oriented'],
    dayInLife: [
      'Greet guests and take consultations',
      'Perform treatments to spec',
      'Recommend products at the end',
      'Reset rooms between appointments',
      'Restock and clean equipment',
    ],
    realityCheck: 'Physically tiring on hands and back. Mostly female-dominated workplaces.',
    salaryBand: '200-280 NOK/hour + tips',
    companies: ['Hotel spas', 'Wellness centres', 'Day spas', 'Cruise lines'],
    certifications: ['Massage / beauty therapy diploma', 'Specialist treatment certifications'],
    nextSteps: [
      'Train at a beauty / massage school',
      'Apply at hotel spas or wellness centres',
    ],
    tags: [...baseTags, 'wellness', 'tips'],
    order: 128,
  },
  {
    roleName: 'Fitness Instructor',
    summary: 'Lead classes or 1:1 sessions in gyms, hotels and resorts. Help people move and feel better.',
    traits: ['Energetic', 'Motivating', 'Fit', 'Friendly'],
    dayInLife: [
      'Lead group classes',
      'Demo exercises and form',
      'Plan personal sessions',
      'Encourage and adapt for different abilities',
      'Track attendance and progress',
    ],
    realityCheck: 'Early mornings and late evenings. You need genuine energy even on bad days.',
    salaryBand: '200-300 NOK/hour',
    companies: ['Hotel gyms', 'SATS', 'Elixia', 'Resorts', 'Cruise lines'],
    certifications: ['Fitness instructor certification', 'CPR / first aid'],
    nextSteps: [
      'Take a basic fitness instructor course',
      'Volunteer to lead a class at a school or club',
    ],
    tags: [...baseTags, 'wellness', 'physical', 'social'],
    order: 129,
  },
  {
    roleName: 'Lifeguard',
    summary: 'Watch over pools and beaches. Prevent accidents, rescue swimmers, and respond to emergencies.',
    traits: ['Alert', 'Calm', 'Strong swimmer', 'Responsible'],
    dayInLife: [
      'Scan the pool/beach constantly',
      'Enforce safety rules',
      'Respond to incidents and first aid',
      'Test water quality',
      'Help guests with questions',
    ],
    realityCheck: 'Hours of focus required. One mistake matters. Often outdoor in any weather.',
    salaryBand: '180-220 NOK/hour',
    companies: ['Hotel pools', 'Resorts', 'Public pools', 'Cruise lines'],
    certifications: ['Lifeguard certification (livredning)', 'First aid', 'Strong swimming test'],
    nextSteps: [
      'Get a lifeguard certification through Røde Kors / Norges Livredningsselskap',
      'Practice your swimming stamina',
    ],
    tags: [...baseTags, 'wellness', 'safety', 'physical'],
    order: 130,
  },
  {
    roleName: 'Maintenance Technician',
    summary: 'Fix everything that breaks in a hotel — plumbing, electrics, HVAC, doors, you name it.',
    traits: ['Practical', 'Curious', 'Calm', 'Resourceful'],
    dayInLife: [
      'Respond to maintenance requests',
      'Diagnose and fix issues fast',
      'Do preventative checks on equipment',
      'Manage spare parts',
      'Coordinate with external contractors',
    ],
    realityCheck: 'On-call shifts and emergencies. You\'re always behind on requests.',
    salaryBand: '300-450k NOK/year',
    companies: ['Hotels', 'Resorts', 'Conference centres'],
    certifications: ['Trade qualification helpful (electrical, plumbing)', 'Hands-on experience'],
    nextSteps: [
      'Apprentice in a trade',
      'Apply at a hotel as an assistant maintenance worker',
    ],
    tags: [...baseTags, 'hotels', 'practical'],
    order: 131,
  },
  {
    roleName: 'Facilities Manager',
    summary: 'Look after the building itself — safety, contracts, energy, repairs and compliance.',
    traits: ['Practical', 'Organised', 'Numerate', 'Calm'],
    dayInLife: [
      'Audit safety and compliance',
      'Manage contractor relationships',
      'Plan upgrades and refurbishments',
      'Track energy use and costs',
      'Report to the GM and owners',
    ],
    realityCheck: 'You only get noticed when things break. Lots of paperwork.',
    salaryBand: '450-700k NOK/year',
    companies: ['Hotels', 'Resorts', 'Conference centres'],
    certifications: ['Facilities or building background', 'Health & safety training'],
    nextSteps: [
      'Work in maintenance first',
      'Take a basic FM or H&S course',
    ],
    tags: [...baseTags, 'hotels', 'leadership', 'practical'],
    order: 132,
  },
  {
    roleName: 'Revenue Manager',
    summary: 'Set room prices and forecast demand to maximise hotel profit. Data meets hospitality.',
    traits: ['Analytical', 'Numerate', 'Curious', 'Decisive'],
    dayInLife: [
      'Analyse booking data and competitor pricing',
      'Set rates by date, channel and room type',
      'Forecast demand and occupancy',
      'Coordinate with sales and marketing',
      'Report results to the GM',
    ],
    realityCheck: 'Mostly desk work, but huge impact on the hotel\'s success. Spreadsheets all day.',
    salaryBand: '500-800k NOK/year',
    companies: ['Hotel chains', 'Independent hotels', 'Revenue consultancies'],
    certifications: ['Hospitality or business degree helpful', 'Revenue management courses'],
    nextSteps: [
      'Work in reservations or front office',
      'Get comfy with Excel and data',
      'Take a basic revenue management course',
    ],
    tags: [...baseTags, 'hotels', 'analytical'],
    order: 133,
  },
  {
    roleName: 'Reservations Agent',
    summary: 'Handle bookings by phone, email and online — for hotels, restaurants or tours.',
    traits: ['Friendly', 'Organised', 'Detail-oriented', 'Tech-comfortable'],
    dayInLife: [
      'Answer booking enquiries',
      'Enter bookings into the system',
      'Upsell rooms and packages',
      'Handle cancellations and changes',
      'Coordinate with front office',
    ],
    realityCheck: 'Mostly phone and screen work. Repetitive but social on calls.',
    salaryBand: '180-220 NOK/hour',
    companies: ['Hotels', 'Tour operators', 'Cruise lines'],
    certifications: ['No formal education required', 'Strong English / second languages helpful'],
    nextSteps: [
      'Apply directly to hotel reservations teams',
      'Practice clear, calm phone conversation',
    ],
    tags: [...baseTags, 'hotels', 'entry-level', 'first-job', 'customer-service'],
    order: 134,
  },
  {
    roleName: 'Night Auditor',
    summary: 'Run the front desk overnight — check in late guests, balance the day\'s books, and keep watch.',
    traits: ['Calm', 'Independent', 'Numerate', 'Reliable'],
    dayInLife: [
      'Check in late arrivals',
      'Run the day\'s end-of-day reports',
      'Reconcile cash and card payments',
      'Be on-call for any emergencies',
      'Hand over to morning shift',
    ],
    realityCheck: 'Night shifts mess with sleep. Long, quiet stretches with bursts of intensity.',
    salaryBand: '200-260 NOK/hour (night shift premium)',
    companies: ['Hotels', 'Hostels'],
    certifications: ['No formal education required', 'PMS systems training'],
    nextSteps: [
      'Work day reception first to learn the system',
      'Decide if your body can handle nights',
    ],
    tags: [...baseTags, 'hotels', '18+', 'night-shifts'],
    order: 135,
  },
  {
    roleName: 'Security Officer',
    summary: 'Keep guests, staff and property safe. Patrol, watch CCTV, and respond calmly to incidents.',
    traits: ['Calm', 'Observant', 'Fit', 'Trustworthy'],
    dayInLife: [
      'Patrol the building and grounds',
      'Monitor CCTV',
      'Check ID and access',
      'Respond to incidents and complaints',
      'Write incident reports',
    ],
    realityCheck: 'Most shifts are quiet; bad ones are very not. Night shifts common.',
    salaryBand: '200-260 NOK/hour',
    companies: ['Hotels', 'Resorts', 'Event venues', 'Securitas', 'Nokas'],
    certifications: ['Security guard certification (vekterskolen)', '18+'],
    nextSteps: [
      'Look into vekter training',
      'Stay fit and even-tempered',
    ],
    tags: [...baseTags, 'safety', '18+', 'night-shifts'],
    order: 136,
  },
  {
    roleName: 'Tour Guide',
    summary: 'Lead visitors through cities, museums, fjords or attractions. Storytelling is the job.',
    traits: ['Outgoing', 'Storyteller', 'Knowledgeable', 'Multilingual'],
    dayInLife: [
      'Greet a tour group',
      'Lead them through the route',
      'Share history, stories and tips',
      'Answer questions',
      'Keep the group safe and on time',
    ],
    realityCheck: 'Outdoor in any weather. Same script repeated all day. Tourists ask the same questions.',
    salaryBand: '200-300 NOK/hour + tips',
    companies: ['Tour operators', 'Cruise excursions', 'Museums', 'Cities'],
    certifications: ['Tour guide course helpful', 'Languages a huge plus'],
    nextSteps: [
      'Practice telling stories about your home town',
      'Learn or improve a second language',
      'Apply to local tour operators in summer',
    ],
    tags: [...baseTags, 'travel', 'social', 'seasonal', 'tips'],
    order: 137,
  },
  {
    roleName: 'Travel Agent',
    summary: 'Help people plan trips — flights, hotels, tours, and dreams come true.',
    traits: ['Helpful', 'Organised', 'Curious about the world', 'Persuasive'],
    dayInLife: [
      'Listen to what clients want',
      'Research and quote options',
      'Book flights, hotels and activities',
      'Sort out problems mid-trip',
      'Follow up on return',
    ],
    realityCheck: 'Online travel booking has shrunk this job. Specialist and luxury agencies still thrive.',
    salaryBand: '320-500k NOK/year + commission',
    companies: ['Ving', 'Apollo', 'TUI', 'Specialist tour operators'],
    certifications: ['Travel & tourism diploma helpful', 'Strong product knowledge'],
    nextSteps: [
      'Travel as much as you can',
      'Apply to a specialist agency you\'d be a client of',
    ],
    tags: [...baseTags, 'travel', 'customer-service'],
    order: 138,
  },
  {
    roleName: 'Cruise Director',
    summary: 'Lead the entertainment, activities and guest experience on a cruise ship.',
    traits: ['Charismatic', 'Energetic', 'Leader', 'Performer'],
    dayInLife: [
      'Host onboard events and announcements',
      'Coordinate entertainment teams',
      'Greet VIPs',
      'Solve guest issues fast',
      'Plan the next day\'s schedule',
    ],
    realityCheck: 'Months at sea, away from family. On stage all the time. High burnout.',
    salaryBand: '500-900k NOK/year + tips',
    companies: ['Royal Caribbean', 'Carnival', 'Hurtigruten', 'MSC'],
    certifications: ['Years of cruise experience', 'Performance / events background'],
    nextSteps: [
      'Apply for entry-level cruise jobs first',
      'Get comfortable on a stage or microphone',
    ],
    tags: [...baseTags, 'travel', 'cruise', 'leadership', '18+'],
    order: 139,
  },
  {
    roleName: 'Cabin Crew',
    summary: 'Look after passengers on flights — safety first, then service and smiles.',
    traits: ['Calm', 'Friendly', 'Fit', 'Adaptable'],
    dayInLife: [
      'Pre-flight safety briefings',
      'Greet passengers boarding',
      'Demonstrate safety procedures',
      'Serve food and drinks',
      'Handle medical or behavioural incidents',
    ],
    realityCheck: 'Time zones, jet lag, and difficult passengers. Romanticised on Instagram, hard in reality.',
    salaryBand: '380-550k NOK/year',
    companies: ['SAS', 'Norwegian', 'Widerøe', 'KLM', 'Lufthansa'],
    certifications: ['Cabin crew training (provided by airline)', '18+', 'Strong swimming', 'Medical fitness'],
    nextSteps: [
      'Get strong customer service experience',
      'Apply directly to airlines when they recruit',
      'Get comfortable in front of strangers',
    ],
    tags: [...baseTags, 'travel', 'aviation', '18+'],
    order: 140,
  },
  {
    roleName: 'Airport Hospitality Agent',
    summary: 'Welcome travellers in airport lounges, help with bookings, and keep things running smoothly.',
    traits: ['Friendly', 'Calm', 'Multitasker', 'Service-minded'],
    dayInLife: [
      'Greet guests entering the lounge',
      'Restock food and drink areas',
      'Help with flight info and bookings',
      'Handle special requests',
      'Keep the lounge tidy and welcoming',
    ],
    realityCheck: 'Shifts cover early mornings, nights and weekends. Some difficult delayed travellers.',
    salaryBand: '180-230 NOK/hour',
    companies: ['Airport lounges', 'Avinor concessions', 'SSP', 'Plaza Premium'],
    certifications: ['No formal education required', 'Strong English'],
    nextSteps: [
      'Apply at airport lounges directly',
      'Get strong customer service experience first',
    ],
    tags: [...baseTags, 'travel', 'aviation', 'entry-level', 'first-job', 'customer-service'],
    order: 141,
  },
];

/**
 * Function to seed hospitality career cards
 * Call this from main seed.ts
 */
export async function seedHospitalityCareers(prisma: any) {
  console.log('Seeding hospitality career cards...');

  for (const career of hospitalityCareerCards) {
    await prisma.careerCard.upsert({
      where: { roleName: career.roleName },
      update: career,
      create: career,
    });
  }

  console.log(`Seeded ${hospitalityCareerCards.length} hospitality career cards`);
}
