/**
 * Entry-Level Youth Career Cards
 * These are realistic first jobs for Norwegian youth ages 15-20
 * Designed to complement the tech/professional careers with accessible options
 */

export const youthCareerCards = [
  {
    roleName: 'Barista / Café Worker',
    summary: 'Make coffee drinks, serve customers, and create a welcoming atmosphere. Perfect for people who enjoy social interaction and fast-paced environments.',
    traits: ['Friendly', 'Quick learner', 'Multitasker', 'Customer-focused'],
    dayInLife: [
      'Prepare espresso drinks and other beverages',
      'Greet customers and take orders',
      'Keep the café clean and stocked',
      'Handle cash register and payments',
      'Learn to make latte art and specialty drinks',
    ],
    realityCheck: 'Early mornings and weekend shifts are common. Can be stressful during rush hours. Standing for long periods. Great way to build customer service skills.',
    salaryBand: '150-200 NOK/hour (160-180 typical)',
    companies: ['Espresso House', 'Starbucks', 'Kaffebrenneriet', 'Local cafés', 'Baker chains'],
    certifications: [
      'No formal education required',
      'Food handling certificate (matservering) helpful',
      'On-the-job training provided',
    ],
    nextSteps: [
      'Apply to local cafés - bring a friendly attitude',
      'Practice basic customer service phrases',
      'Learn about different coffee types online',
      'Get a food handling certificate (optional but impressive)',
    ],
    tags: ['social', 'customer-service', 'food', 'entry-level', 'part-time', 'first-job'],
    order: 30,
  },
  {
    roleName: 'Retail Sales Associate',
    summary: 'Help customers find products, organize displays, and process sales. Great for building confidence and communication skills.',
    traits: ['Helpful', 'Organized', 'Patient', 'Good communicator'],
    dayInLife: [
      'Greet and assist customers',
      'Stock shelves and organize merchandise',
      'Process purchases at the register',
      'Answer questions about products',
      'Keep the store tidy and presentable',
    ],
    realityCheck: 'Weekend and holiday shifts expected. Dealing with difficult customers occasionally. Lots of standing and walking. Good employee discounts at many stores.',
    salaryBand: '150-190 NOK/hour',
    companies: ['H&M', 'Clas Ohlson', 'XXL Sport', 'Elkjøp', 'Local boutiques'],
    certifications: [
      'No formal education required',
      'Some stores prefer 18+ for cash handling',
      'On-the-job training provided',
    ],
    nextSteps: [
      'Visit stores you like and ask about openings',
      'Create a simple CV highlighting your reliability',
      'Practice greeting customers with confidence',
      'Think about what stores match your interests',
    ],
    tags: ['social', 'customer-service', 'retail', 'entry-level', 'part-time', 'first-job'],
    order: 31,
  },
  {
    roleName: 'Food Delivery Driver',
    summary: 'Deliver food from restaurants to customers using a bike, scooter, or car. Flexible hours and good for independent workers.',
    traits: ['Independent', 'Punctual', 'Good navigator', 'Responsible'],
    dayInLife: [
      'Accept delivery orders through an app',
      'Pick up food from restaurants',
      'Navigate to customer addresses',
      'Deliver orders on time',
      'Manage your own schedule',
    ],
    realityCheck: 'Weather affects the job significantly. Wear and tear on your vehicle/bike. Income varies by how many orders you complete. Very flexible schedule.',
    salaryBand: '120-200 NOK/hour (varies by orders)',
    companies: ['Foodora', 'Wolt', 'Just Eat', 'Local restaurants'],
    certifications: [
      'Must be 18+ for scooter/car delivery',
      'Bicycle delivery possible at 16+',
      'Valid drivers license for vehicle delivery',
      'Own transportation required',
    ],
    nextSteps: [
      'Download Foodora/Wolt app and apply',
      'Ensure your bike or vehicle is in good condition',
      'Learn your city\'s streets and shortcuts',
      'Get a good phone holder for navigation',
    ],
    tags: ['independent', 'flexible', 'outdoor', 'delivery', 'entry-level', 'gig-work'],
    order: 32,
  },
  {
    roleName: 'Babysitter / Childcare Helper',
    summary: 'Care for children while parents are away. Perfect for responsible, nurturing people who enjoy working with kids.',
    traits: ['Responsible', 'Patient', 'Creative', 'Trustworthy'],
    dayInLife: [
      'Play games and activities with children',
      'Prepare simple meals and snacks',
      'Help with homework if needed',
      'Put children to bed at appropriate times',
      'Keep the home tidy',
    ],
    realityCheck: 'Requires high trust from parents. Evening and weekend work common. Can be tiring with active children. Very rewarding when kids enjoy their time with you.',
    salaryBand: '100-180 NOK/hour',
    companies: ['Private families', 'Barnepike.no', 'Care.com', 'Local networks'],
    certifications: [
      'No formal education required',
      'First aid course recommended',
      'References from teachers or family friends helpful',
      'Police certificate (politiattest) may be required',
    ],
    nextSteps: [
      'Ask family and neighbors if they need help',
      'Create a profile on babysitting platforms',
      'Get references from trusted adults',
      'Consider taking a first aid course',
    ],
    tags: ['caring', 'children', 'flexible', 'entry-level', 'part-time', 'trust-based'],
    order: 33,
  },
  {
    roleName: 'Dog Walker / Pet Sitter',
    summary: 'Walk dogs and care for pets while owners are at work or traveling. Great for animal lovers who enjoy being outdoors.',
    traits: ['Animal lover', 'Reliable', 'Active', 'Gentle'],
    dayInLife: [
      'Pick up dogs from their homes',
      'Walk dogs in parks or neighborhoods',
      'Feed and water pets',
      'Clean up after animals',
      'Send updates to owners',
    ],
    realityCheck: 'Works in all weather conditions. Requires physical activity. Must be comfortable with all dog sizes. Very flexible once you build regular clients.',
    salaryBand: '80-150 NOK/hour',
    companies: ['Private clients', 'Rover', 'Local pet services', 'Neighborhood networks'],
    certifications: [
      'No formal education required',
      'Experience with animals helpful',
      'References from pet owners valuable',
    ],
    nextSteps: [
      'Post in local Facebook groups offering services',
      'Create flyers for your neighborhood',
      'Start with friends\' or neighbors\' pets',
      'Build a portfolio with photos of happy dogs',
    ],
    tags: ['animals', 'outdoor', 'flexible', 'entry-level', 'part-time', 'independent'],
    order: 34,
  },
  {
    roleName: 'Grocery Store Worker',
    summary: 'Stock shelves, help customers, and keep the store running smoothly. Reliable work with regular hours.',
    traits: ['Hardworking', 'Organized', 'Team player', 'Dependable'],
    dayInLife: [
      'Stock shelves with products',
      'Check expiration dates',
      'Help customers find items',
      'Work the checkout register',
      'Keep the store clean and organized',
    ],
    realityCheck: 'Physical work with lifting boxes. Early morning or evening shifts common. Repetitive tasks. Good employee discounts and stable hours.',
    salaryBand: '150-180 NOK/hour (tariff rates apply)',
    companies: ['Rema 1000', 'Kiwi', 'Coop', 'Meny', 'Joker'],
    certifications: [
      'No formal education required',
      'Must be 15+ for light work, 18+ for some tasks',
      'Food handling awareness training provided',
    ],
    nextSteps: [
      'Apply directly at stores in your area',
      'Bring a simple CV showing your reliability',
      'Be ready to work early mornings or evenings',
      'Emphasize your dependability',
    ],
    tags: ['reliable', 'team-work', 'retail', 'entry-level', 'part-time', 'first-job', 'grocery'],
    order: 35,
  },
  {
    roleName: 'Fast Food Worker',
    summary: 'Prepare food quickly, serve customers, and maintain cleanliness in a fast-paced restaurant environment.',
    traits: ['Fast learner', 'Stress-tolerant', 'Team player', 'Energetic'],
    dayInLife: [
      'Take customer orders',
      'Prepare food following recipes',
      'Maintain cleanliness standards',
      'Work as part of a team',
      'Handle busy rush periods',
    ],
    realityCheck: 'Very fast-paced during meal times. Can be hot and noisy. Shifts include evenings and weekends. Great for learning to work under pressure.',
    salaryBand: '150-180 NOK/hour',
    companies: ['McDonald\'s', 'Burger King', 'Subway', 'Peppes Pizza', 'Local takeaways'],
    certifications: [
      'No formal education required',
      'Must be 15+ (with restrictions) or 18+',
      'Food handling training provided',
    ],
    nextSteps: [
      'Apply online through restaurant websites',
      'Visit during non-busy hours to ask about openings',
      'Show enthusiasm and willingness to learn',
      'Be flexible about shift times',
    ],
    tags: ['fast-paced', 'team-work', 'food', 'entry-level', 'part-time', 'first-job'],
    order: 36,
  },
  {
    roleName: 'Snow Clearing / Outdoor Helper',
    summary: 'Clear snow, do yard work, and help with outdoor maintenance. Seasonal work that pays well in winter.',
    traits: ['Hardworking', 'Physically fit', 'Reliable', 'Early riser'],
    dayInLife: [
      'Shovel snow from driveways and walkways',
      'Spread salt or sand on icy surfaces',
      'Rake leaves in autumn',
      'Help with garden maintenance',
      'General outdoor cleaning tasks',
    ],
    realityCheck: 'Weather-dependent and seasonal. Physically demanding work. Early morning starts in winter. Can earn good money during snow season.',
    salaryBand: '100-180 NOK/hour (higher during heavy snow)',
    companies: ['Private homeowners', 'Housing cooperatives (borettslag)', 'Property management companies'],
    certifications: [
      'No formal education required',
      'Own equipment can increase earnings',
      'Physical fitness important',
    ],
    nextSteps: [
      'Knock on neighbors\' doors before winter',
      'Post services in local Facebook groups',
      'Join your local borettslag mailing list',
      'Invest in a good shovel and warm clothes',
    ],
    tags: ['outdoor', 'physical', 'seasonal', 'entry-level', 'flexible', 'winter'],
    order: 37,
  },
  {
    roleName: 'Cinema / Entertainment Attendant',
    summary: 'Work at movie theaters or entertainment venues. Sell tickets, serve snacks, and ensure guests have a great experience.',
    traits: ['Friendly', 'Customer-focused', 'Punctual', 'Team player'],
    dayInLife: [
      'Sell tickets and check admissions',
      'Prepare and serve popcorn and drinks',
      'Clean theaters between showings',
      'Help customers with questions',
      'Monitor screenings',
    ],
    realityCheck: 'Evening and weekend work is standard. Can be slow during weekdays. Fun environment and free movies. Good way to meet other young people.',
    salaryBand: '150-180 NOK/hour',
    companies: ['Odeon', 'SF Kino', 'Ringen Kino', 'Local cinemas', 'Bowling alleys'],
    certifications: [
      'No formal education required',
      'Must be 15+ (18+ for some venues)',
      'On-the-job training provided',
    ],
    nextSteps: [
      'Apply through cinema websites',
      'Show enthusiasm for movies/entertainment',
      'Be available for weekend and evening shifts',
      'Highlight customer service skills',
    ],
    tags: ['entertainment', 'social', 'evening-work', 'entry-level', 'part-time', 'fun'],
    order: 38,
  },
  {
    roleName: 'Warehouse Worker',
    summary: 'Pick, pack, and organize products in warehouses. Good physical work with regular hours.',
    traits: ['Organized', 'Physically fit', 'Detail-oriented', 'Dependable'],
    dayInLife: [
      'Pick products for customer orders',
      'Pack items carefully for shipping',
      'Organize inventory on shelves',
      'Use handheld scanners',
      'Load and unload deliveries',
    ],
    realityCheck: 'Physical work with lots of walking and lifting. Can be repetitive. Climate-controlled but may have early shifts. Good option for those who prefer less customer interaction.',
    salaryBand: '160-200 NOK/hour',
    companies: ['PostNord', 'Komplett', 'Amazon logistics', 'Kolonial.no', 'Local warehouses'],
    certifications: [
      'Must be 18+ for most positions',
      'Forklift certification a plus',
      'Physical fitness required',
    ],
    nextSteps: [
      'Apply through staffing agencies like Adecco, Manpower',
      'Check job listings on Finn.no',
      'Be ready for early morning shifts',
      'Highlight your reliability and physical fitness',
    ],
    tags: ['physical', 'logistics', 'organized', 'entry-level', 'full-time-possible', '18+'],
    order: 39,
  },
  {
    roleName: 'Tutor / Study Helper',
    summary: 'Help younger students with homework and studying. Great if you\'re good at explaining things and patient.',
    traits: ['Patient', 'Good communicator', 'Knowledgeable', 'Encouraging'],
    dayInLife: [
      'Meet with students after school',
      'Help with homework in specific subjects',
      'Explain concepts in simple ways',
      'Create practice problems',
      'Track student progress',
    ],
    realityCheck: 'Requires patience and ability to explain things simply. Sessions are usually 1-2 hours. Rewarding when students improve. Flexible scheduling.',
    salaryBand: '150-300 NOK/hour (varies by subject)',
    companies: ['Private families', 'Superprof', 'Tutoring agencies', 'After-school programs'],
    certifications: [
      'Good grades in subjects you teach',
      'No formal certification required',
      'References from teachers helpful',
    ],
    nextSteps: [
      'Identify your strongest subjects',
      'Create a profile on tutoring platforms',
      'Ask teachers if they know families needing help',
      'Start with younger students to build confidence',
    ],
    tags: ['education', 'helping', 'flexible', 'entry-level', 'part-time', 'academic'],
    order: 40,
  },
  {
    roleName: 'Event Staff / Festival Worker',
    summary: 'Work at concerts, sports events, and festivals. Exciting seasonal work with variety.',
    traits: ['Flexible', 'Energetic', 'Team player', 'Adaptable'],
    dayInLife: [
      'Check tickets at entrances',
      'Serve food and drinks',
      'Help with crowd control',
      'Set up and break down events',
      'Answer guest questions',
    ],
    realityCheck: 'Irregular hours - lots of work in summer and during events. Long shifts on your feet. Exciting atmosphere and often free access to events.',
    salaryBand: '160-220 NOK/hour (weekend and holiday rates higher)',
    companies: ['By:Larm', 'Øyafestivalen', 'Sports venues', 'Catering companies', 'Event agencies'],
    certifications: [
      'Must be 18+ for serving alcohol',
      'Responsible beverage service course for bar work',
      'Security certification for crowd control roles',
    ],
    nextSteps: [
      'Register with event staffing agencies',
      'Apply before festival season (spring)',
      'Be available for training sessions',
      'Build experience at smaller events first',
    ],
    tags: ['events', 'social', 'seasonal', 'entry-level', 'exciting', 'summer-job'],
    order: 41,
  },
  {
    roleName: 'Kitchen Helper / Dishwasher',
    summary: 'Support restaurant kitchens by washing dishes, prepping ingredients, and keeping things clean. A classic first step in the food industry.',
    traits: ['Hardworking', 'Stress-tolerant', 'Team player', 'Quick'],
    dayInLife: [
      'Wash dishes and kitchen equipment',
      'Prep simple ingredients',
      'Keep the kitchen clean and organized',
      'Take out trash and recycling',
      'Assist cooks when needed',
    ],
    realityCheck: 'Hot, fast-paced environment. Physically demanding with long periods standing. Can lead to cooking positions. Often includes a staff meal.',
    salaryBand: '150-180 NOK/hour',
    companies: ['Restaurants', 'Hotels', 'Catering companies', 'School cafeterias'],
    certifications: [
      'No formal education required',
      'Must be 15+ (with restrictions)',
      'Food handling awareness is a plus',
    ],
    nextSteps: [
      'Walk into restaurants and ask if they need help',
      'Apply to hotels and larger restaurants',
      'Be ready to start immediately when needed',
      'Show willingness to work hard and learn',
    ],
    tags: ['food', 'physical', 'team-work', 'entry-level', 'first-job', 'kitchen'],
    order: 42,
  },
  {
    roleName: 'Cleaning / Housekeeping',
    summary: 'Clean homes, offices, or hotel rooms. Independent work that\'s always in demand.',
    traits: ['Detail-oriented', 'Reliable', 'Independent', 'Efficient'],
    dayInLife: [
      'Vacuum and mop floors',
      'Clean bathrooms and kitchens',
      'Dust and organize spaces',
      'Change linens in hotels',
      'Report maintenance issues',
    ],
    realityCheck: 'Physical work that can be repetitive. Usually independent with little supervision. Flexible scheduling possible. Always jobs available.',
    salaryBand: '150-200 NOK/hour (higher for private clients)',
    companies: ['Hotels', 'Cleaning companies', 'Private households', 'Offices'],
    certifications: [
      'No formal education required',
      'Police certificate for household work',
      'Own transportation helpful',
    ],
    nextSteps: [
      'Apply to local cleaning companies',
      'Offer services to neighbors and family friends',
      'Create a profile on care.com or similar',
      'Build references through consistent good work',
    ],
    tags: ['independent', 'flexible', 'physical', 'entry-level', 'cleaning', 'always-hiring'],
    order: 43,
  },
  {
    roleName: 'Moving Helper',
    summary: 'Help people move homes by carrying furniture and boxes. Great pay for physically demanding work.',
    traits: ['Strong', 'Careful', 'Team player', 'Problem solver'],
    dayInLife: [
      'Carry boxes and furniture safely',
      'Load and unload moving trucks',
      'Wrap and protect fragile items',
      'Navigate tight spaces carefully',
      'Work efficiently as a team',
    ],
    realityCheck: 'Very physical work - heavy lifting all day. Irregular hours based on demand. Peak seasons are summer and month-ends. Good tips are common.',
    salaryBand: '180-250 NOK/hour',
    companies: ['Flyttebyra', 'Moving companies', 'Gig platforms', 'Private requests'],
    certifications: [
      'Must be 18+ for most companies',
      'Drivers license a major plus',
      'Physical fitness essential',
    ],
    nextSteps: [
      'Apply to moving companies before summer',
      'Register on gig platforms like Finn småjobber',
      'Offer services in local community groups',
      'Build your strength with regular exercise',
    ],
    tags: ['physical', 'team-work', 'good-pay', 'entry-level', 'seasonal', '18+', 'tips'],
    order: 44,
  },
];

/**
 * Function to seed youth career cards
 * Call this from main seed.ts
 */
export async function seedYouthCareers(prisma: any) {
  console.log('Seeding youth career cards...');

  for (const career of youthCareerCards) {
    await prisma.careerCard.upsert({
      where: { roleName: career.roleName },
      update: career,
      create: career,
    });
  }

  console.log(`Seeded ${youthCareerCards.length} youth career cards`);
}
