/**
 * Executive & Senior Leadership Career Cards
 * Telecom & technology executive track — C-suite, EVP, SVP, VP, and Head-of roles
 * Designed to show youth the top of the career ladder and what it takes to get there
 */

export const executiveCareerCards = [
  // ============================================
  // C-SUITE (1–10)
  // ============================================
  {
    roleName: 'Chief Executive Officer (CEO)',
    summary: 'The top leader of the entire company. Sets vision, drives strategy, and is ultimately accountable for every decision. Reports to the board of directors.',
    traits: ['Visionary leadership', 'Strategic thinking', 'Decisiveness', 'Resilience'],
    dayInLife: [
      'Review company performance and financial reports',
      'Meet with the executive leadership team on strategic priorities',
      'Engage with the board of directors, investors, and regulators',
      'Make high-stakes decisions on acquisitions, partnerships, and market entry',
      'Represent the company at industry events and in media',
    ],
    realityCheck: 'Extreme pressure with constant public scrutiny. Work-life balance is difficult — the job never switches off. Every failure lands on your desk. Typically requires 20-30 years of progressive leadership experience.',
    salaryBand: '5M-20M+ NOK (plus equity/bonuses)',
    companies: ['Telenor', 'Telia', 'Deutsche Telekom', 'Vodafone', 'Orange'],
    certifications: [
      'MBA or advanced degree strongly preferred',
      'Extensive board and governance experience',
      'Track record leading large organisations',
      'Deep industry expertise across multiple functions',
    ],
    nextSteps: [
      'Build a strong academic foundation (business, engineering, or economics)',
      'Gain experience across multiple business functions early in career',
      'Seek leadership roles and P&L responsibility as soon as possible',
      'Develop a network across the industry — relationships matter at this level',
    ],
    tags: ['executive', 'leadership', 'strategy', 'c-suite', 'telecom'],
    order: 45,
  },
  {
    roleName: 'Chief Operating Officer (COO)',
    summary: 'Runs the day-to-day operations of the company. Translates the CEO\'s vision into execution across every department. The engine room leader.',
    traits: ['Operational excellence', 'Cross-functional leadership', 'Process-driven', 'Execution-focused'],
    dayInLife: [
      'Oversee operational performance across all business units',
      'Drive efficiency programs and cost optimisation',
      'Align teams on quarterly targets and delivery milestones',
      'Resolve cross-functional bottlenecks and escalations',
      'Report to the CEO on operational health and risks',
    ],
    realityCheck: 'Relentless pace — you are the person who makes things actually happen. Requires deep understanding of every part of the business. Often the hardest-working executive in the building.',
    salaryBand: '3M-10M NOK',
    companies: ['Telenor', 'Telia', 'BT Group', 'Telefónica', 'Swisscom'],
    certifications: [
      'MBA or Master\'s in Engineering/Business',
      'Lean/Six Sigma expertise at senior level',
      'Proven track record running complex operations',
      'Experience managing large teams (1,000+)',
    ],
    nextSteps: [
      'Start in operational roles — project management, service delivery, or logistics',
      'Learn to read a P&L and understand financial drivers',
      'Build expertise in process improvement and efficiency',
      'Take on cross-functional leadership opportunities early',
    ],
    tags: ['executive', 'operations', 'leadership', 'c-suite', 'telecom'],
    order: 46,
  },
  {
    roleName: 'Chief Technology Officer (CTO)',
    summary: 'Leads the technology vision and engineering strategy. Decides what the company builds, how it\'s built, and what technologies to bet on.',
    traits: ['Technical vision', 'Innovation mindset', 'Strategic thinking', 'Team building'],
    dayInLife: [
      'Set technical direction and architecture standards',
      'Evaluate emerging technologies for competitive advantage',
      'Lead R&D and innovation programs',
      'Collaborate with product and commercial teams on technology roadmaps',
      'Present technology strategy to the board and investors',
    ],
    realityCheck: 'Must stay technically sharp while operating at a strategic level. Balancing innovation with reliability is a constant tension. Technology decisions have multi-year consequences.',
    salaryBand: '3M-10M NOK',
    companies: ['Telenor', 'Ericsson', 'Nokia', 'Cisco', 'Telia'],
    certifications: [
      'Master\'s or PhD in Computer Science, Engineering, or related field',
      'Deep hands-on engineering background',
      'TOGAF or enterprise architecture frameworks',
      'Track record of delivering large-scale technology programs',
    ],
    nextSteps: [
      'Build a strong software engineering or network engineering foundation',
      'Contribute to open-source or industry standards bodies',
      'Seek architect and tech lead roles to broaden your view',
      'Develop business acumen alongside your technical skills',
    ],
    tags: ['executive', 'technology', 'innovation', 'c-suite', 'telecom', 'engineering'],
    order: 47,
  },
  {
    roleName: 'Chief Information Officer (CIO)',
    summary: 'Owns the company\'s IT landscape — enterprise systems, data platforms, cybersecurity, and digital workplace. Keeps the digital backbone running.',
    traits: ['Systems thinking', 'Governance-minded', 'Risk management', 'Stakeholder management'],
    dayInLife: [
      'Oversee enterprise IT systems (ERP, CRM, HR platforms)',
      'Drive cybersecurity posture and compliance',
      'Manage IT budgets and vendor relationships',
      'Lead digital workplace and employee productivity initiatives',
      'Ensure business continuity and disaster recovery readiness',
    ],
    realityCheck: 'Often under-appreciated until something breaks. Balancing legacy system maintenance with modernisation is an endless challenge. Security threats never sleep.',
    salaryBand: '2.5M-8M NOK',
    companies: ['Telenor', 'DNB', 'Equinor', 'Telia', 'Nordea'],
    certifications: [
      'Master\'s in IT, Computer Science, or Business',
      'ITIL 4 Strategic Leader or Managing Professional',
      'CISM or CISSP (cybersecurity governance)',
      'TOGAF or enterprise architecture certification',
    ],
    nextSteps: [
      'Start in IT support, systems administration, or development',
      'Learn ITIL frameworks and service management principles',
      'Gain experience managing IT projects and budgets',
      'Understand cybersecurity fundamentals and risk management',
    ],
    tags: ['executive', 'it', 'cybersecurity', 'governance', 'c-suite', 'telecom'],
    order: 48,
  },
  {
    roleName: 'Chief Digital Officer (CDO)',
    summary: 'Leads digital transformation across the business. Responsible for reimagining customer experiences, digitising processes, and driving new digital revenue.',
    traits: ['Change leadership', 'Customer empathy', 'Data-driven', 'Entrepreneurial'],
    dayInLife: [
      'Define and drive the digital transformation roadmap',
      'Champion customer-centric digital experiences',
      'Build digital product teams and agile delivery capability',
      'Measure digital adoption, engagement, and revenue impact',
      'Identify emerging digital trends and competitive threats',
    ],
    realityCheck: 'Organisational resistance to change is the biggest enemy. Must constantly prove ROI. The role can be politically complex, sitting between IT and commercial teams.',
    salaryBand: '2.5M-8M NOK',
    companies: ['Telenor', 'Telia', 'Orange', 'Vodafone', 'A1 Telekom'],
    certifications: [
      'MBA or Master\'s in Digital Business/Technology',
      'Agile/SAFe leadership certifications',
      'Design thinking and UX strategy credentials',
      'Track record of successful digital transformations',
    ],
    nextSteps: [
      'Learn product management and agile delivery methods',
      'Study UX/UI design and customer journey mapping',
      'Build skills in data analytics and digital marketing',
      'Seek roles in digital product teams or innovation labs',
    ],
    tags: ['executive', 'digital', 'transformation', 'innovation', 'c-suite', 'telecom'],
    order: 49,
  },
  {
    roleName: 'Chief Commercial Officer (CCO)',
    summary: 'Owns revenue. Leads sales, marketing, and commercial strategy to grow the business. Responsible for how the company goes to market and wins customers.',
    traits: ['Revenue-driven', 'Market insight', 'Negotiation', 'Competitive instinct'],
    dayInLife: [
      'Review sales pipeline, revenue forecasts, and market share data',
      'Develop go-to-market strategy for new products and segments',
      'Lead pricing, packaging, and partnership decisions',
      'Engage with key enterprise clients and strategic accounts',
      'Align sales, marketing, and product teams on growth targets',
    ],
    realityCheck: 'You live and die by the numbers. Missing revenue targets has real consequences. Requires thick skin and the ability to thrive under constant pressure.',
    salaryBand: '3M-10M NOK',
    companies: ['Telenor', 'Telia', 'Vodafone Business', 'T-Mobile', 'Telefónica'],
    certifications: [
      'MBA or Master\'s in Business/Marketing',
      'Deep sales leadership experience',
      'Enterprise account management track record',
      'Industry certifications in strategic marketing or pricing',
    ],
    nextSteps: [
      'Start in sales, business development, or marketing roles',
      'Learn to read financials — revenue, margin, churn metrics',
      'Build negotiation and presentation skills',
      'Seek exposure to enterprise/B2B sales early in your career',
    ],
    tags: ['executive', 'commercial', 'sales', 'revenue', 'c-suite', 'telecom'],
    order: 50,
  },
  {
    roleName: 'Chief Network Officer (CNO)',
    summary: 'Owns the physical and virtual network — the core product of a telecom company. Responsible for building, operating, and evolving the network.',
    traits: ['Technical depth', 'Infrastructure mindset', 'Long-term planning', 'Reliability-focused'],
    dayInLife: [
      'Oversee network build-out, capacity planning, and rollout programs',
      'Monitor network performance, availability, and SLA compliance',
      'Drive 5G, fibre, and next-generation network investments',
      'Manage vendor relationships with Ericsson, Nokia, Huawei',
      'Report to the CEO and board on network strategy and CAPEX',
    ],
    realityCheck: 'Massive capital expenditure decisions with decade-long consequences. Network outages create national headlines. Must balance cost, coverage, and quality constantly.',
    salaryBand: '3M-10M NOK',
    companies: ['Telenor', 'Telia', 'Deutsche Telekom', 'Vodafone', 'Bharti Airtel'],
    certifications: [
      'Master\'s or PhD in Telecommunications, Electrical Engineering, or related field',
      'Deep hands-on network engineering background',
      '3GPP and ITU standards expertise',
      'Experience managing large-scale network rollout programs',
    ],
    nextSteps: [
      'Study telecommunications engineering or electrical engineering',
      'Start in radio planning, network operations, or transmission engineering',
      'Learn about 5G, fibre, and cloud-native network architectures',
      'Gain certifications from Ericsson, Nokia, or Cisco',
    ],
    tags: ['executive', 'network', 'telecom', 'infrastructure', 'c-suite', '5g'],
    order: 51,
  },
  {
    roleName: 'Chief Strategy Officer (CSO)',
    summary: 'Shapes where the company goes next. Leads strategic planning, competitive analysis, M&A, and portfolio decisions that define the company\'s future.',
    traits: ['Analytical rigour', 'Long-term vision', 'Intellectual curiosity', 'Influence'],
    dayInLife: [
      'Conduct market analysis, competitive intelligence, and scenario planning',
      'Develop 3-5 year corporate strategy and present to the board',
      'Evaluate M&A opportunities, partnerships, and divestments',
      'Facilitate executive strategy offsites and planning workshops',
      'Advise the CEO on strategic bets and portfolio priorities',
    ],
    realityCheck: 'Influence without direct authority — you recommend, others execute. Can feel disconnected from day-to-day operations. Requires exceptional analytical and communication skills.',
    salaryBand: '2.5M-8M NOK',
    companies: ['Telenor', 'Telia', 'Liberty Global', 'Millicom', 'Ooredoo'],
    certifications: [
      'MBA from a top-tier business school',
      'Management consulting background (McKinsey, BCG, Bain typical)',
      'Strong financial modelling and valuation skills',
      'Deep industry expertise across telecom value chain',
    ],
    nextSteps: [
      'Build a strong analytical foundation in business or economics',
      'Consider management consulting as a career accelerator',
      'Learn financial modelling and business case development',
      'Read widely about industry trends, geopolitics, and competitive strategy',
    ],
    tags: ['executive', 'strategy', 'planning', 'mna', 'c-suite', 'telecom'],
    order: 52,
  },
  {
    roleName: 'Chief Transformation Officer',
    summary: 'Leads company-wide change programs — restructuring, cost reduction, culture shifts, and operating model redesigns. The architect of organisational change.',
    traits: ['Change management', 'Stakeholder alignment', 'Pragmatism', 'Courage'],
    dayInLife: [
      'Define and track transformation programs across the organisation',
      'Manage a portfolio of change initiatives with clear milestones',
      'Break down resistance and build coalition for change',
      'Report transformation progress to the CEO and board',
      'Ensure benefits realisation and sustainable change adoption',
    ],
    realityCheck: 'You are often the most unpopular person in the room. Transformation means change, and people resist change. Requires extraordinary resilience and political skill.',
    salaryBand: '2.5M-8M NOK',
    companies: ['Telenor', 'BT Group', 'Vodafone', 'Telefónica', 'KPN'],
    certifications: [
      'MBA or Master\'s in Change Management or Business',
      'Prosci or ADKAR change management certification',
      'Management consulting or transformation delivery background',
      'Experience leading programs worth 100M+ NOK',
    ],
    nextSteps: [
      'Start in project management or management consulting',
      'Study change management methodologies (Prosci, Kotter)',
      'Seek roles in transformation or PMO teams',
      'Develop your ability to influence without direct authority',
    ],
    tags: ['executive', 'transformation', 'change-management', 'c-suite', 'telecom'],
    order: 53,
  },
  {
    roleName: 'Chief Data & AI Officer',
    summary: 'Owns the company\'s data strategy and AI capability. Turns data into a strategic asset and drives AI adoption across the business.',
    traits: ['Data-driven', 'AI literacy', 'Ethical reasoning', 'Cross-functional influence'],
    dayInLife: [
      'Define data governance, quality, and privacy standards',
      'Build and scale AI/ML capabilities across the organisation',
      'Identify high-value use cases for AI in operations, network, and CX',
      'Ensure compliance with data regulations (GDPR, AI Act)',
      'Evangelise data culture and AI literacy across the company',
    ],
    realityCheck: 'Most organisations are still early in their data maturity journey. You will spend significant time on data quality and governance before the exciting AI work. Ethical questions around AI are increasingly complex.',
    salaryBand: '2.5M-8M NOK',
    companies: ['Telenor', 'Telia', 'Orange', 'Deutsche Telekom', 'Singtel'],
    certifications: [
      'Master\'s or PhD in Data Science, AI, Statistics, or Computer Science',
      'Deep hands-on experience with ML/AI systems',
      'Data governance and privacy certifications (CDMP, CIPP/E)',
      'AI ethics and responsible AI frameworks knowledge',
    ],
    nextSteps: [
      'Build a strong foundation in statistics, programming, and machine learning',
      'Learn about data governance, privacy, and regulatory frameworks',
      'Work on real-world AI/ML projects to build practical experience',
      'Understand the business side — how data creates value, not just models',
    ],
    tags: ['executive', 'data', 'ai', 'governance', 'c-suite', 'telecom', 'machine-learning'],
    order: 54,
  },

  // ============================================
  // EXECUTIVE VICE PRESIDENTS (11–15)
  // ============================================
  {
    roleName: 'EVP Technology',
    summary: 'Leads the technology organisation at the executive level. Owns engineering, architecture, and technology delivery across the company.',
    traits: ['Technical breadth', 'Organisational leadership', 'Strategic execution', 'Talent development'],
    dayInLife: [
      'Lead a technology organisation of hundreds or thousands of engineers',
      'Set technical strategy and architecture direction',
      'Manage multi-billion NOK technology budgets and vendor contracts',
      'Drive modernisation programs (cloud, automation, DevOps)',
      'Represent technology in executive committee and board discussions',
    ],
    realityCheck: 'Managing at this scale means less hands-on technical work and more people, budget, and politics. Must translate deeply technical topics for non-technical executives.',
    salaryBand: '2.5M-6M NOK',
    companies: ['Telenor', 'Telia', 'Ericsson', 'Nokia', 'Infosys'],
    certifications: [
      'Master\'s in Engineering, Computer Science, or related field',
      'Extensive engineering leadership background (15+ years)',
      'Enterprise architecture certifications (TOGAF)',
      'Cloud platform expertise (AWS, Azure, GCP)',
    ],
    nextSteps: [
      'Start as a software or network engineer and master your craft',
      'Move into tech lead and architect roles to broaden scope',
      'Develop people management skills — leading teams is different from coding',
      'Build business understanding alongside technical depth',
    ],
    tags: ['executive', 'technology', 'engineering', 'evp', 'telecom', 'leadership'],
    order: 55,
  },
  {
    roleName: 'EVP Networks',
    summary: 'Leads the network organisation — radio, core, transport, and fixed access. Owns the most capital-intensive part of a telecom operator.',
    traits: ['Infrastructure leadership', 'CAPEX management', 'Vendor negotiation', 'Regulatory awareness'],
    dayInLife: [
      'Oversee network rollout programs (5G, fibre, satellite)',
      'Manage vendor relationships and multi-year contracts',
      'Drive network quality, coverage, and capacity targets',
      'Coordinate with regulators on spectrum and infrastructure sharing',
      'Present network investment cases to the board',
    ],
    realityCheck: 'Network investments are measured in billions and take years to pay back. Regulatory and geopolitical factors add complexity. Must think in 5-10 year horizons.',
    salaryBand: '2.5M-6M NOK',
    companies: ['Telenor', 'Telia', 'Deutsche Telekom', 'Vodafone', 'Bharti Airtel'],
    certifications: [
      'Master\'s in Telecommunications or Electrical Engineering',
      'Deep network engineering background (radio, core, transport)',
      'Vendor-specific certifications (Ericsson, Nokia, Cisco)',
      'Regulatory and spectrum management knowledge',
    ],
    nextSteps: [
      'Study telecommunications or electrical engineering',
      'Start in radio planning, network operations, or transmission',
      'Build expertise in 5G architecture and cloud-native networks',
      'Seek vendor-side or operator-side roles to understand both perspectives',
    ],
    tags: ['executive', 'network', 'infrastructure', 'evp', 'telecom', '5g'],
    order: 56,
  },
  {
    roleName: 'EVP IT & Digital',
    summary: 'Leads IT systems, digital platforms, and business support systems. Bridges technology and business to enable digital-first operations.',
    traits: ['Platform thinking', 'Business-IT alignment', 'Modernisation drive', 'Agile leadership'],
    dayInLife: [
      'Lead IT and digital platform teams across the organisation',
      'Drive BSS/OSS modernisation and cloud migration programs',
      'Manage digital channel development (apps, web, self-service)',
      'Align IT delivery with business priorities and revenue targets',
      'Oversee IT security, compliance, and operational resilience',
    ],
    realityCheck: 'Legacy systems are the constant challenge — replacing them while keeping the business running. Must satisfy both technical teams and impatient business leaders.',
    salaryBand: '2.5M-6M NOK',
    companies: ['Telenor', 'Telia', 'Orange', 'Swisscom', 'Proximus'],
    certifications: [
      'Master\'s in IT, Computer Science, or Digital Business',
      'ITIL, SAFe, or agile delivery certifications',
      'Cloud platform certifications (AWS, Azure)',
      'BSS/OSS and TM Forum frameworx knowledge',
    ],
    nextSteps: [
      'Start in software development, IT operations, or digital product teams',
      'Learn about BSS/OSS systems and telecom-specific IT',
      'Build agile delivery and product management skills',
      'Understand cloud-native architectures and API-first design',
    ],
    tags: ['executive', 'it', 'digital', 'platforms', 'evp', 'telecom', 'bss-oss'],
    order: 57,
  },
  {
    roleName: 'EVP Commercial',
    summary: 'Leads the commercial engine — consumer, enterprise, and wholesale sales. Responsible for market share, revenue growth, and customer satisfaction.',
    traits: ['Commercial acumen', 'Market leadership', 'Customer focus', 'Competitive drive'],
    dayInLife: [
      'Review revenue, churn, ARPU, and market share metrics daily',
      'Lead go-to-market strategy for consumer and enterprise segments',
      'Drive pricing, promotions, and channel strategy',
      'Manage key enterprise accounts and partnership deals',
      'Align marketing, sales, and customer experience teams',
    ],
    realityCheck: 'Quarterly revenue pressure is relentless. Telecom markets are mature and competitive — growth is hard-won. Must balance short-term targets with long-term brand building.',
    salaryBand: '2.5M-6M NOK',
    companies: ['Telenor', 'Telia', 'Vodafone', 'T-Mobile', 'Telefónica'],
    certifications: [
      'MBA or Master\'s in Business/Marketing',
      'Extensive B2C and/or B2B sales leadership',
      'Digital marketing and CX certifications',
      'Track record of growing revenue in competitive markets',
    ],
    nextSteps: [
      'Start in sales, marketing, or customer service roles',
      'Learn commercial metrics — ARPU, churn, LTV, CAC',
      'Build experience in both consumer and enterprise segments',
      'Develop strong presentation and negotiation skills',
    ],
    tags: ['executive', 'commercial', 'sales', 'marketing', 'evp', 'telecom'],
    order: 58,
  },
  {
    roleName: 'EVP Enterprise / Wholesale',
    summary: 'Leads the B2B and wholesale business — selling connectivity, cloud, IoT, and managed services to enterprises and other operators.',
    traits: ['B2B expertise', 'Solution selling', 'Relationship management', 'Contract negotiation'],
    dayInLife: [
      'Lead enterprise and wholesale sales teams and strategy',
      'Manage major account relationships and multi-year contracts',
      'Develop ICT, IoT, and managed service propositions',
      'Drive wholesale agreements with MVNOs and partner operators',
      'Build strategic partnerships with hyperscalers and technology vendors',
    ],
    realityCheck: 'Enterprise sales cycles are long — 6-18 months for major deals. Requires deep technical understanding to sell complex solutions. Wholesale margins are thin and heavily regulated.',
    salaryBand: '2.5M-6M NOK',
    companies: ['Telenor', 'Telia', 'BT Global', 'Vodafone Business', 'Lumen Technologies'],
    certifications: [
      'MBA or Master\'s in Business/Technology',
      'Enterprise sales leadership experience',
      'ICT and cloud solution expertise',
      'Understanding of wholesale regulation and interconnect agreements',
    ],
    nextSteps: [
      'Start in B2B sales, account management, or solution architecture',
      'Learn about enterprise connectivity, SD-WAN, cloud, and IoT',
      'Build experience with complex contract negotiations',
      'Understand wholesale and interconnect business models',
    ],
    tags: ['executive', 'enterprise', 'wholesale', 'b2b', 'evp', 'telecom', 'iot'],
    order: 59,
  },

  // ============================================
  // SENIOR VICE PRESIDENTS (16–20)
  // ============================================
  {
    roleName: 'SVP Technology',
    summary: 'Leads a major technology division — engineering teams, platform delivery, and technology operations. A key step between VP and EVP.',
    traits: ['Technical leadership', 'Delivery excellence', 'Team scaling', 'Strategic thinking'],
    dayInLife: [
      'Lead multiple technology teams and engineering managers',
      'Drive technology delivery against roadmap commitments',
      'Manage significant technology budgets and resources',
      'Set standards for engineering practices, quality, and security',
      'Represent technology in cross-functional leadership forums',
    ],
    realityCheck: 'The bridge between hands-on technical leadership and executive strategy. Must be equally comfortable in architecture reviews and boardroom presentations.',
    salaryBand: '2M-4.5M NOK',
    companies: ['Telenor', 'Telia', 'Ericsson', 'Amdocs', 'Accenture'],
    certifications: [
      'Master\'s in Computer Science or Engineering',
      'Extensive engineering leadership experience (12+ years)',
      'Cloud and platform architecture expertise',
      'Agile/SAFe leadership at scale',
    ],
    nextSteps: [
      'Build a strong engineering career with increasing scope',
      'Move from individual contributor to team lead to director',
      'Develop skills in budgeting, hiring, and organisational design',
      'Seek experience leading cross-functional delivery programs',
    ],
    tags: ['senior-leadership', 'technology', 'engineering', 'svp', 'telecom'],
    order: 60,
  },
  {
    roleName: 'SVP Networks',
    summary: 'Leads a major network domain — mobile, fixed, core, or transport. Responsible for network performance, rollout, and evolution.',
    traits: ['Network expertise', 'Program management', 'Vendor management', 'Quality focus'],
    dayInLife: [
      'Oversee network performance and SLA compliance',
      'Lead network rollout and modernisation programs',
      'Manage vendor delivery and contract performance',
      'Drive capacity planning and network evolution strategy',
      'Coordinate with regulatory and spectrum teams',
    ],
    realityCheck: 'Network is the product — when it fails, everyone notices immediately. Massive complexity with thousands of sites and millions of connections. Weather, geography, and regulation all add challenges.',
    salaryBand: '2M-4.5M NOK',
    companies: ['Telenor', 'Telia', 'Deutsche Telekom', 'Vodafone', 'Elisa'],
    certifications: [
      'Master\'s in Telecommunications or Electrical Engineering',
      'Deep domain expertise in radio, core, or transport networks',
      'Vendor certifications (Ericsson, Nokia)',
      'Program management credentials (PMP, PRINCE2)',
    ],
    nextSteps: [
      'Start in network engineering or operations',
      'Specialise in a domain (radio, core, transport, or fixed)',
      'Build program and vendor management experience',
      'Learn about spectrum regulation and infrastructure economics',
    ],
    tags: ['senior-leadership', 'network', 'infrastructure', 'svp', 'telecom'],
    order: 61,
  },
  {
    roleName: 'SVP IT / OSS / BSS',
    summary: 'Leads the IT systems that run a telecom operator — billing, CRM, provisioning, and operational support. The backbone of every customer interaction.',
    traits: ['Systems architecture', 'Integration expertise', 'Vendor management', 'Process optimisation'],
    dayInLife: [
      'Oversee BSS (billing, CRM, revenue management) and OSS (network management, provisioning) platforms',
      'Lead modernisation and migration programs for legacy systems',
      'Manage system integrator and vendor relationships',
      'Drive automation and zero-touch operations initiatives',
      'Ensure system reliability, performance, and scalability',
    ],
    realityCheck: 'Telecom IT is among the most complex in any industry — hundreds of systems interconnected. Modernising while keeping the business running is like changing engines on a flying plane.',
    salaryBand: '2M-4.5M NOK',
    companies: ['Telenor', 'Telia', 'Amdocs', 'Ericsson Digital Services', 'Netcracker'],
    certifications: [
      'Master\'s in IT, Computer Science, or Telecommunications',
      'TM Forum Open Digital Architecture knowledge',
      'Enterprise architecture certifications (TOGAF)',
      'BSS/OSS domain expertise from vendor or operator side',
    ],
    nextSteps: [
      'Start in software development or IT operations within a telecom',
      'Learn about BSS/OSS systems — billing, provisioning, assurance',
      'Understand TM Forum standards and telecom-specific frameworks',
      'Build experience with system integration and migration projects',
    ],
    tags: ['senior-leadership', 'it', 'bss-oss', 'systems', 'svp', 'telecom'],
    order: 62,
  },
  {
    roleName: 'SVP Product & Platforms',
    summary: 'Leads product strategy and platform development. Defines what the company offers and how it\'s delivered to customers.',
    traits: ['Product vision', 'Platform thinking', 'Customer insight', 'Commercial awareness'],
    dayInLife: [
      'Define product portfolio strategy and roadmap',
      'Lead product and platform development teams',
      'Analyse market trends, customer needs, and competitive landscape',
      'Drive product P&L performance and pricing decisions',
      'Collaborate with technology, commercial, and CX teams',
    ],
    realityCheck: 'Telecom products are increasingly commoditised — differentiation is hard. Must balance innovation with the reality of legacy systems and existing customer base. Stakeholder management is constant.',
    salaryBand: '2M-4.5M NOK',
    companies: ['Telenor', 'Telia', 'Vodafone', 'Three', 'Elisa'],
    certifications: [
      'MBA or Master\'s in Business/Technology',
      'Product management certifications (CPM, Pragmatic Institute)',
      'Agile product delivery experience at scale',
      'Telecom product domain expertise',
    ],
    nextSteps: [
      'Start in product management, business analysis, or marketing',
      'Learn about product-led growth and platform business models',
      'Build skills in customer research and data-driven decision making',
      'Understand telecom product economics — ARPU, churn, bundling',
    ],
    tags: ['senior-leadership', 'product', 'platforms', 'svp', 'telecom', 'strategy'],
    order: 63,
  },
  {
    roleName: 'SVP Operations',
    summary: 'Leads operational delivery — service operations, field force, customer operations, and process excellence. Keeps the machine running smoothly.',
    traits: ['Operational rigour', 'Process excellence', 'Data-driven', 'Continuous improvement'],
    dayInLife: [
      'Oversee service operations, NOC, and field operations',
      'Drive operational KPIs — SLA, MTTR, first-call resolution',
      'Lead automation and process improvement programs',
      'Manage operational budgets and workforce planning',
      'Ensure operational resilience and incident response readiness',
    ],
    realityCheck: 'Operations never sleeps — 24/7 responsibility for service availability. Pressure to reduce costs while improving quality. Requires comfort with data, metrics, and continuous improvement.',
    salaryBand: '2M-4.5M NOK',
    companies: ['Telenor', 'Telia', 'Vodafone', 'Telefónica', 'Axiata'],
    certifications: [
      'Master\'s in Engineering, Operations Management, or Business',
      'Lean/Six Sigma Black Belt',
      'ITIL 4 Managing Professional',
      'Program and project management credentials',
    ],
    nextSteps: [
      'Start in service delivery, NOC, or field operations',
      'Learn Lean and Six Sigma methodologies',
      'Build experience with operational KPIs and reporting',
      'Develop skills in workforce management and process automation',
    ],
    tags: ['senior-leadership', 'operations', 'service-delivery', 'svp', 'telecom'],
    order: 64,
  },

  // ============================================
  // MANAGING DIRECTORS & VPs (21–25)
  // ============================================
  {
    roleName: 'Managing Director (Country / Region)',
    summary: 'Runs an entire country or regional operation as a mini-CEO. Full P&L responsibility for all commercial, network, and operational activities in that market.',
    traits: ['General management', 'P&L ownership', 'Cultural intelligence', 'Regulatory navigation'],
    dayInLife: [
      'Lead all business functions in a country or region',
      'Own the full P&L — revenue, cost, profitability, and investment',
      'Engage with local regulators, government, and industry bodies',
      'Adapt group strategy to local market conditions',
      'Build and lead a high-performing local leadership team',
    ],
    realityCheck: 'True general management — responsible for everything. Must navigate local politics, regulation, and culture. Often far from group HQ, requiring self-sufficiency and judgement.',
    salaryBand: '2.5M-6M NOK',
    companies: ['Telenor (Asia/Nordics)', 'Telia', 'Vodafone', 'Orange', 'MTN Group'],
    certifications: [
      'MBA or Master\'s in Business/Economics',
      'Extensive leadership experience across multiple functions',
      'Cultural competency and international experience',
      'Regulatory and government relations expertise',
    ],
    nextSteps: [
      'Build experience across multiple functions — not just one specialism',
      'Seek international assignments or cross-market projects',
      'Develop P&L literacy and commercial leadership skills',
      'Learn about local regulation, culture, and market dynamics',
    ],
    tags: ['executive', 'general-management', 'country-lead', 'md', 'telecom', 'international'],
    order: 65,
  },
  {
    roleName: 'Managing Director (Business Unit)',
    summary: 'Leads a specific business unit — such as enterprise, consumer, digital services, or tower company. Full ownership of that unit\'s strategy and performance.',
    traits: ['Business ownership', 'Strategic focus', 'Commercial drive', 'Organisational leadership'],
    dayInLife: [
      'Own the business unit\'s strategy, P&L, and growth targets',
      'Lead a dedicated team across product, sales, operations, and finance',
      'Make investment and prioritisation decisions within the unit',
      'Report to group executive team on unit performance',
      'Drive competitive positioning and market differentiation',
    ],
    realityCheck: 'Accountable for results but dependent on shared services (network, IT, HR). Must influence without full control. Success requires both commercial results and organisational alignment.',
    salaryBand: '2M-5M NOK',
    companies: ['Telenor', 'Telia', 'BT', 'Vodafone', 'Liberty Global'],
    certifications: [
      'MBA or Master\'s in relevant field',
      'P&L management experience',
      'Domain expertise in the business unit\'s sector',
      'Track record of growing a business or launching new ventures',
    ],
    nextSteps: [
      'Build deep expertise in one business domain first',
      'Seek roles with increasing scope and P&L exposure',
      'Develop skills across strategy, operations, and commercial',
      'Learn to navigate matrix organisations and influence shared services',
    ],
    tags: ['executive', 'general-management', 'business-unit', 'md', 'telecom'],
    order: 66,
  },
  {
    roleName: 'VP OSS / BSS Transformation',
    summary: 'Leads the modernisation of operational and business support systems. Transforms legacy stacks into cloud-native, API-first platforms.',
    traits: ['Transformation leadership', 'Architecture vision', 'Vendor management', 'Stakeholder alignment'],
    dayInLife: [
      'Lead BSS/OSS modernisation and migration programs',
      'Define target architecture aligned with TM Forum Open Digital Architecture',
      'Manage system integrator partnerships and delivery milestones',
      'Drive adoption of cloud-native, microservices-based platforms',
      'Coordinate with commercial and operations teams on cutover planning',
    ],
    realityCheck: 'BSS/OSS transformation is notoriously difficult — high failure rates industry-wide. Involves replacing systems that touch every customer and every transaction. Requires patience, rigour, and excellent stakeholder management.',
    salaryBand: '1.8M-3.5M NOK',
    companies: ['Telenor', 'Telia', 'Amdocs', 'Ericsson', 'Netcracker'],
    certifications: [
      'Master\'s in IT, Computer Science, or Telecommunications',
      'TM Forum certifications and Open API knowledge',
      'Enterprise architecture (TOGAF) and cloud certifications',
      'Program management credentials (PMP, SAFe)',
    ],
    nextSteps: [
      'Start in software development or IT within a telecom operator',
      'Learn about BSS/OSS systems and TM Forum frameworks',
      'Build experience with large-scale migration and transformation projects',
      'Develop vendor management and system integration skills',
    ],
    tags: ['leadership', 'bss-oss', 'transformation', 'vp', 'telecom', 'architecture'],
    order: 67,
  },
  {
    roleName: 'VP Network Engineering',
    summary: 'Leads network design and engineering across radio, core, and transport domains. Translates network strategy into technical blueprints and standards.',
    traits: ['Deep technical expertise', 'Standards-driven', 'Design leadership', 'Innovation focus'],
    dayInLife: [
      'Lead network design, dimensioning, and architecture teams',
      'Define technology standards and network evolution roadmaps',
      'Evaluate new technologies (Open RAN, network slicing, edge compute)',
      'Collaborate with vendors on feature development and testing',
      'Ensure network designs meet coverage, capacity, and quality targets',
    ],
    realityCheck: 'Must stay technically current in a fast-evolving field while managing large teams. Design decisions have long-term consequences and massive cost implications. Standards processes can be slow and political.',
    salaryBand: '1.8M-3.5M NOK',
    companies: ['Telenor', 'Telia', 'Ericsson', 'Nokia', 'Samsung Networks'],
    certifications: [
      'Master\'s or PhD in Telecommunications or Electrical Engineering',
      'Deep expertise in radio, core, or transport engineering',
      'Vendor certifications (Ericsson, Nokia, Cisco)',
      '3GPP standards participation experience',
    ],
    nextSteps: [
      'Study telecommunications or electrical engineering at university',
      'Start in radio planning, core engineering, or network design',
      'Build deep expertise in one domain, then broaden to others',
      'Engage with standards bodies and industry forums (3GPP, GSMA)',
    ],
    tags: ['leadership', 'network', 'engineering', 'vp', 'telecom', '5g', 'architecture'],
    order: 68,
  },
  {
    roleName: 'VP Cloud & Infrastructure',
    summary: 'Leads cloud strategy, data centre operations, and infrastructure platforms. Drives the shift from traditional infrastructure to cloud-native operations.',
    traits: ['Cloud expertise', 'Infrastructure leadership', 'Automation mindset', 'Cost optimisation'],
    dayInLife: [
      'Define cloud strategy and migration roadmap',
      'Lead data centre and infrastructure operations teams',
      'Manage hybrid/multi-cloud environments (AWS, Azure, GCP, private)',
      'Drive infrastructure automation and infrastructure-as-code adoption',
      'Optimise infrastructure costs and capacity planning',
    ],
    realityCheck: 'Cloud migration in telecom is complex — not everything moves easily. Must balance cloud-native ambitions with legacy infrastructure realities. Security and compliance add layers of complexity.',
    salaryBand: '1.8M-3.5M NOK',
    companies: ['Telenor', 'Telia', 'Ericsson', 'AWS', 'Microsoft'],
    certifications: [
      'Master\'s in Computer Science, IT, or Engineering',
      'Cloud certifications (AWS Solutions Architect, Azure Expert, GCP Pro)',
      'Kubernetes and container orchestration expertise',
      'Infrastructure automation (Terraform, Ansible) experience',
    ],
    nextSteps: [
      'Start in systems administration, DevOps, or cloud engineering',
      'Get certified in major cloud platforms (AWS, Azure, GCP)',
      'Learn infrastructure-as-code and automation tools',
      'Build experience with containerisation and Kubernetes',
    ],
    tags: ['leadership', 'cloud', 'infrastructure', 'vp', 'telecom', 'devops'],
    order: 69,
  },

  // ============================================
  // HEADS OF DEPARTMENT (26–30)
  // ============================================
  {
    roleName: 'Head of Network Operations (NOC)',
    summary: 'Leads the Network Operations Centre — the 24/7 nerve centre that monitors, manages, and restores the network. First responder when things go wrong.',
    traits: ['Crisis leadership', 'Real-time decision making', 'Process discipline', 'Team management'],
    dayInLife: [
      'Oversee 24/7 network monitoring and incident management',
      'Lead major incident response and service restoration',
      'Drive root cause analysis and problem management',
      'Manage NOC team shifts, training, and performance',
      'Report on network availability, MTTR, and SLA compliance',
    ],
    realityCheck: '24/7 responsibility means you get called at 3 AM during major outages. High-pressure environment where speed of response matters. Requires calm under pressure and decisive leadership.',
    salaryBand: '1.2M-2.2M NOK',
    companies: ['Telenor', 'Telia', 'Vodafone', 'Orange', 'BT'],
    certifications: [
      'Bachelor\'s or Master\'s in IT, Telecommunications, or Engineering',
      'ITIL 4 certifications',
      'Network monitoring and management tool expertise',
      'Incident and problem management process experience',
    ],
    nextSteps: [
      'Start in NOC as a network operator or analyst',
      'Learn network monitoring tools and incident management processes',
      'Get ITIL certified to understand service management frameworks',
      'Develop leadership skills for managing shift-based teams',
    ],
    tags: ['leadership', 'network', 'operations', 'noc', 'telecom', 'incident-management'],
    order: 70,
  },
  {
    roleName: 'Head of IT Operations',
    summary: 'Leads IT service operations — keeping enterprise systems, platforms, and infrastructure running reliably. Owns uptime, performance, and IT service delivery.',
    traits: ['Service excellence', 'Reliability focus', 'Automation drive', 'Stakeholder management'],
    dayInLife: [
      'Oversee IT infrastructure, application, and platform operations',
      'Manage IT service desk and incident/problem management',
      'Drive IT operational automation and self-healing capabilities',
      'Ensure compliance with SLAs and operational KPIs',
      'Lead disaster recovery planning and testing',
    ],
    realityCheck: 'IT systems fail at the worst times. Must maintain calm during outages while managing expectations from every department. The better you do your job, the less visible you are — until something breaks.',
    salaryBand: '1.2M-2.2M NOK',
    companies: ['Telenor', 'DNB', 'Equinor', 'Telia', 'Atea'],
    certifications: [
      'Bachelor\'s or Master\'s in IT or Computer Science',
      'ITIL 4 Managing Professional',
      'Cloud operations certifications (AWS SysOps, Azure Admin)',
      'DevOps and SRE practices knowledge',
    ],
    nextSteps: [
      'Start in IT support, systems administration, or DevOps',
      'Learn ITIL service management and operational frameworks',
      'Build skills in monitoring, alerting, and automation',
      'Gain experience with cloud operations and infrastructure management',
    ],
    tags: ['leadership', 'it', 'operations', 'service-management', 'telecom', 'reliability'],
    order: 71,
  },
  {
    roleName: 'Head of Service Delivery',
    summary: 'Leads end-to-end service delivery for enterprise customers. Ensures complex telecom and ICT solutions are delivered on time, on budget, and to specification.',
    traits: ['Project delivery', 'Customer relationship', 'Technical breadth', 'Problem resolution'],
    dayInLife: [
      'Manage a portfolio of enterprise customer delivery projects',
      'Coordinate cross-functional teams (network, IT, field operations)',
      'Ensure SLA compliance and customer satisfaction',
      'Escalate and resolve delivery issues and blockers',
      'Drive process improvement for faster, more reliable delivery',
    ],
    realityCheck: 'Caught between customer expectations and internal delivery capacity. Complex solutions involve many teams who all need to deliver their part. Requires diplomacy, urgency, and attention to detail.',
    salaryBand: '1.2M-2.2M NOK',
    companies: ['Telenor', 'Telia', 'BT', 'Vodafone Business', 'Lumen'],
    certifications: [
      'Bachelor\'s or Master\'s in Engineering, IT, or Business',
      'PMP or PRINCE2 project management certification',
      'ITIL service management fundamentals',
      'Enterprise solution delivery experience',
    ],
    nextSteps: [
      'Start in project coordination, technical delivery, or customer service',
      'Learn project management methodologies (PMP, PRINCE2)',
      'Build understanding of telecom products and enterprise solutions',
      'Develop customer-facing communication and escalation skills',
    ],
    tags: ['leadership', 'service-delivery', 'enterprise', 'project-management', 'telecom'],
    order: 72,
  },
  {
    roleName: 'Head of Architecture (Enterprise / Network)',
    summary: 'Defines the blueprint for how technology systems and networks are designed and evolve. The strategic thinker who ensures everything fits together.',
    traits: ['Systems thinking', 'Strategic vision', 'Technical depth', 'Cross-domain knowledge'],
    dayInLife: [
      'Define and maintain enterprise or network architecture standards',
      'Evaluate technology choices and create architecture decision records',
      'Lead architecture review boards and governance processes',
      'Guide solution architects and development teams on best practices',
      'Drive architecture modernisation — microservices, APIs, cloud-native',
    ],
    realityCheck: 'Influence without authority — architects recommend, others decide. Must balance ideal architecture with practical constraints (budget, timeline, legacy). Can feel removed from hands-on building.',
    salaryBand: '1.2M-2.2M NOK',
    companies: ['Telenor', 'Telia', 'Ericsson', 'Accenture', 'Capgemini'],
    certifications: [
      'Master\'s in Computer Science, IT, or Engineering',
      'TOGAF or equivalent enterprise architecture certification',
      'Cloud architecture certifications (AWS SA Pro, Azure Expert)',
      'Domain-specific expertise (network, BSS/OSS, security)',
    ],
    nextSteps: [
      'Build a strong foundation as a developer or engineer first',
      'Move into solution architect roles to broaden your perspective',
      'Get TOGAF certified to learn architecture frameworks',
      'Study cloud-native patterns, APIs, and modern integration',
    ],
    tags: ['leadership', 'architecture', 'strategy', 'enterprise', 'telecom', 'design'],
    order: 73,
  },
  {
    roleName: 'Head of Product Management',
    summary: 'Leads the product management function — defining what the company builds and sells. Owns product strategy, roadmaps, and lifecycle management.',
    traits: ['Product sense', 'Customer empathy', 'Data literacy', 'Cross-functional leadership'],
    dayInLife: [
      'Define product strategy and prioritise the product roadmap',
      'Lead a team of product managers across multiple product lines',
      'Analyse market trends, customer feedback, and competitive intelligence',
      'Drive product launches, pricing, and go-to-market planning',
      'Collaborate with engineering, design, marketing, and sales teams',
    ],
    realityCheck: 'Everyone has an opinion about the product — managing stakeholders is as important as managing the product. Must make hard trade-off decisions with incomplete data. Success depends on cross-functional alignment.',
    salaryBand: '1.2M-2.2M NOK',
    companies: ['Telenor', 'Telia', 'Vodafone', 'Ericsson', 'Vipps'],
    certifications: [
      'Bachelor\'s or Master\'s in Business, Technology, or Design',
      'Product management certifications (CPM, Pragmatic Institute, Product School)',
      'Agile/Scrum product owner experience',
      'Data analytics and customer research skills',
    ],
    nextSteps: [
      'Start in product analysis, business analysis, or UX research',
      'Learn product management frameworks (Jobs-to-be-Done, OKRs)',
      'Build skills in data analytics and customer interviewing',
      'Take on product owner roles in agile delivery teams',
    ],
    tags: ['leadership', 'product', 'strategy', 'customer', 'telecom', 'roadmap'],
    order: 74,
  },
];

/**
 * Function to seed executive career cards
 * Call this from main seed.ts
 */
export async function seedExecutiveCareers(prisma: any) {
  console.log('Seeding executive & leadership career cards...');

  for (const career of executiveCareerCards) {
    await prisma.careerCard.upsert({
      where: { roleName: career.roleName },
      update: career,
      create: career,
    });
  }

  console.log(`Seeded ${executiveCareerCards.length} executive career cards`);
}
