import type { MetadataRoute } from "next";

/**
 * robots.txt — generated by Next.js App Router metadata API.
 *
 * Strategy: allow public marketing + legal pages; block every
 * authenticated surface, every API route, and every admin / employer /
 * dev / test path. Update this when adding a new public top-level
 * page so search engines can find it.
 */

const PUBLIC_HOST =
  process.env.NEXT_PUBLIC_SITE_URL ||
  (process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : "https://endeavrly.no");

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: [
          "/",
          "/about",
          "/about/research",
          "/about/white-paper",
          "/landing-v3",
          "/for-parents",
          "/parents-paths",
          "/contribute",
          "/legal/terms",
          "/legal/privacy",
          "/legal/cookies",
          "/legal/safety",
          "/legal/disclaimer",
          "/legal/eligibility",
          "/p/", // shareable public career profiles
        ],
        disallow: [
          "/api/",
          "/admin/",
          "/auth/",
          "/dashboard",
          "/dashboard/",
          "/my-journey",
          "/my-journey/",
          "/my-path",
          "/my-path/",
          "/profile",
          "/profile/",
          "/careers",
          "/careers/",
          "/jobs",
          "/jobs/",
          "/employer/",
          "/guardian",
          "/guardian/",
          "/messages/",
          "/applications",
          "/shadows",
          "/shadows/",
          "/dev/",
          "/test/",
          "/explore",
          "/insights",
          "/feedback",
          "/earnings",
          "/reviews",
          "/messages",
          "/goals",
          "/growth",
          "/growth/",
          "/categories",
          "/career-events",
          "/career-advisor",
          "/ask-a-pro",
          "/legal/accept",
          "/not-eligible",
          "/guardian-consent/",
        ],
      },
    ],
    sitemap: `${PUBLIC_HOST}/sitemap.xml`,
    host: PUBLIC_HOST,
  };
}
