import type { MetadataRoute } from "next";

/**
 * sitemap.xml — generated by the App Router metadata API.
 *
 * Mirrors the public allow-list in `robots.ts` (static marketing + legal
 * pages). Authenticated surfaces, API routes and the dynamic shareable
 * profile pages (`/p/*`) are intentionally excluded. Keep this in step
 * with the robots allow-list when adding a public top-level page.
 */

const PUBLIC_HOST =
  process.env.NEXT_PUBLIC_SITE_URL ||
  (process.env.VERCEL_URL
    ? `https://${process.env.VERCEL_URL}`
    : "https://endeavrly.com");

const PUBLIC_PATHS = [
  "",
  "/about",
  "/about/research",
  "/about/white-paper",
  "/for-parents",
  "/parents-paths",
  "/contribute",
  "/legal/terms",
  "/legal/privacy",
  "/legal/cookies",
  "/legal/safety",
  "/legal/disclaimer",
  "/legal/eligibility",
] as const;

export default function sitemap(): MetadataRoute.Sitemap {
  return PUBLIC_PATHS.map((path) => ({
    url: `${PUBLIC_HOST}${path}`,
    changeFrequency: "monthly",
    priority: path === "" ? 1 : 0.7,
  }));
}
