/**
 * Guardian Invite Claim API
 * POST - Guardian claims an invite code generated by a youth worker
 */

import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { z } from "zod";

const claimSchema = z.object({
  inviteCode: z.string().min(6, "Invalid invite code"),
});

export async function POST(req: NextRequest) {
  try {
    const session = await getServerSession(authOptions);

    if (!session?.user?.id) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    // Verify user has a guardian profile
    const guardianProfile = await prisma.guardianProfile.findUnique({
      where: { userId: session.user.id },
    });

    if (!guardianProfile) {
      return NextResponse.json(
        { error: "You must create a guardian profile first", code: "NO_PROFILE" },
        { status: 400 }
      );
    }

    const body = await req.json();
    const validated = claimSchema.parse(body);

    // Find the link with this invite code
    const link = await prisma.workerGuardianLink.findUnique({
      where: { inviteCode: validated.inviteCode.toUpperCase() },
      include: {
        worker: {
          select: {
            id: true,
            youthProfile: { select: { displayName: true } },
          },
        },
      },
    });

    if (!link) {
      return NextResponse.json(
        { error: "Invalid invite code" },
        { status: 404 }
      );
    }

    if (link.status !== "PENDING") {
      return NextResponse.json(
        { error: "This invite code has already been used" },
        { status: 400 }
      );
    }

    // Check if invite has expired
    if (link.inviteExpiresAt && new Date() > link.inviteExpiresAt) {
      return NextResponse.json(
        { error: "This invite code has expired" },
        { status: 400 }
      );
    }

    // Check if guardian already has a link with this worker
    const existingLink = await prisma.workerGuardianLink.findFirst({
      where: {
        workerId: link.workerId,
        guardianId: guardianProfile.id,
        status: { in: ["PENDING", "ACTIVE"] },
      },
    });

    if (existingLink) {
      return NextResponse.json(
        { error: "You already have a link with this worker" },
        { status: 400 }
      );
    }

    // Claim the invite - update the link with guardian info and activate
    const updatedLink = await prisma.workerGuardianLink.update({
      where: { id: link.id },
      data: {
        guardianId: guardianProfile.id,
        status: "ACTIVE",
        consentGivenAt: new Date(),
        inviteCode: null, // Clear the code so it can't be reused
        inviteExpiresAt: null,
      },
    });

    // Notify the worker
    await prisma.notification.create({
      data: {
        userId: link.workerId,
        type: "GUARDIAN_LINK_ACCEPTED",
        title: "Guardian Linked",
        message: `${guardianProfile.fullName} has linked as your ${guardianProfile.relationship.toLowerCase()}`,
        link: "/profile/guardian-settings",
      },
    });

    return NextResponse.json({
      message: "Successfully linked as guardian",
      linkId: updatedLink.id,
      worker: {
        id: link.worker.id,
        displayName: link.worker.youthProfile?.displayName || "Unknown",
      },
    });
  } catch (error) {
    if (error instanceof z.ZodError) {
      return NextResponse.json(
        { error: "Validation error", details: error.errors },
        { status: 400 }
      );
    }
    console.error("[Guardian Invite Claim] Error:", error);
    return NextResponse.json(
      { error: "Failed to claim invite" },
      { status: 500 }
    );
  }
}
